// Generated by `cargo xtask codegen`. Do not edit directly.
import type { CSSDirectiveSourceReference } from './css-directives.js'

export type MasterCSSMixinParameterSyntax = 'integer' | 'number' | 'string' | 'custom-ident'

export interface MasterCSSMixinParameter {
  name: string
  syntax?: MasterCSSMixinParameterSyntax
  default?: string
  source?: CSSDirectiveSourceReference
}

export type MasterCSSMixinValue = (
  | { type: 'text'; value: string }
  | { type: 'function'; name: string; value: MasterCSSMixinValue }
)[]

export type MasterCSSMixinNode =
  | { type: 'declaration'; property: string; value: MasterCSSMixinValue; source?: CSSDirectiveSourceReference }
  | { type: 'rule'; selector: string; body: MasterCSSMixinNode[] }
  | { type: 'condition'; condition: string; body: MasterCSSMixinNode[] }
  | { type: 'apply'; name: string; arguments: MasterCSSMixinValue[]; contents?: MasterCSSMixinNode[]; source?: CSSDirectiveSourceReference }
  | { type: 'contents'; fallback: MasterCSSMixinNode[] }

export interface MasterCSSMixinDefinition {
  name: string
  parameters?: MasterCSSMixinParameter[]
  body: MasterCSSMixinNode[]
  source?: CSSDirectiveSourceReference
}
