// Generated by `cargo xtask codegen`. Do not edit directly.

export const MASTER_CSS_ENGINE_TRANSITION_VERSION = 1 as const
export const MASTER_CSS_VALIDATOR_BATCH_VERSION = 1 as const
export const MASTER_CSS_DIAGNOSTICS_REPORT_VERSION = 1 as const
export const MASTER_CSS_LINT_BATCH_VERSION = 1 as const
export const MASTER_CSS_LANGUAGE_BATCH_VERSION = 1 as const

export type MasterCSSBackend = 'auto' | 'native' | 'wasm'
export type MasterCSSResolvedBackend = Exclude<MasterCSSBackend, 'auto'>
export type MasterCSSRuleTarget =
  | 'theme'
  | 'base'
  | 'defaults'
  | 'components'
  | 'utilities'
  | 'keyframes'

export interface MasterCSSSourceRange {
  start: number
  end: number
}

export interface MasterCSSEngineInsertMutationIR {
  op: 'insert'
  target: MasterCSSRuleTarget
  index: number
  key: string
  text: string
  rule?: import('./hydration-manifest').MasterCSSGeneratedRuleIR
}

export interface MasterCSSEngineDeleteMutationIR {
  op: 'delete'
  target: MasterCSSRuleTarget
  index: number
  key: string
}

export type MasterCSSEngineMutationIR =
  | MasterCSSEngineInsertMutationIR
  | MasterCSSEngineDeleteMutationIR

export interface MasterCSSEngineTransitionIR {
  version: typeof MASTER_CSS_ENGINE_TRANSITION_VERSION
  mutations: MasterCSSEngineMutationIR[]
}

export interface MasterCSSEngineSnapshotIR {
  version: 1
  rules: import('./hydration-manifest').MasterCSSGeneratedRuleIR[]
  text: string
}

export interface MasterCSSEngineInspectionIR {
  version: 1
  className: string
  valid: boolean
  rules: import('./hydration-manifest').MasterCSSGeneratedRuleIR[]
}

export interface MasterCSSNativeDeclarationCandidateIR {
  className: string
  property: string
  value: string
}

export interface MasterCSSValidatorClassIR {
  className: string
  matched: boolean
  rules: import('./hydration-manifest').MasterCSSGeneratedRuleIR[]
}

export interface MasterCSSValidatorBatchIR {
  version: typeof MASTER_CSS_VALIDATOR_BATCH_VERSION
  classes: MasterCSSValidatorClassIR[]
}

export interface MasterCSSLintClassConflictIR {
  className: string
  conflicts: string[]
}

export interface MasterCSSLintPartialClassConflictIR {
  className: string
  replacement: string
  conflict: string
}

export interface MasterCSSLintBatchIR {
  version: typeof MASTER_CSS_LINT_BATCH_VERSION
  sortedClassNames: string[]
  conflicts: MasterCSSLintClassConflictIR[]
  partialConflicts: MasterCSSLintPartialClassConflictIR[]
}

export interface MasterCSSLintRawValueCandidateIR {
  className: string
  key: string
  segments: string[]
  properties: string[]
}

export interface MasterCSSLintRawValueCandidatesIR {
  version: typeof MASTER_CSS_LINT_BATCH_VERSION
  candidates: MasterCSSLintRawValueCandidateIR[]
}

export interface MasterCSSLintCanonicalClassNameOptionsIR {
  preferStaticUtilities: boolean
  preferThemeTokens: boolean
  preferPropertyAliases: boolean
  preferVariableReferences: boolean
  preferMultiValueTokens: boolean
  preferConditionOrder: boolean
}

export interface MasterCSSLintCanonicalClassSuggestionIR {
  className: string
  recommended: string
}

export interface MasterCSSLintCanonicalClassSuggestionsIR {
  version: typeof MASTER_CSS_LINT_BATCH_VERSION
  suggestions: MasterCSSLintCanonicalClassSuggestionIR[]
}

export interface MasterCSSLintEditIR {
  range: MasterCSSSourceRange
  text: string
}

export interface MasterCSSLintDiagnosticIR {
  ruleId: 'sort-classes' | 'no-invalid-classes' | 'no-conflicting-classes' | 'no-unapproved-raw-values'
  code:
    | 'invalid-class-order'
    | 'invalid-class'
    | 'unknown-class'
    | 'conflicting-class'
    | 'partially-conflicting-class'
    | 'unapproved-raw-value'
  message: string
  range: MasterCSSSourceRange
  data?: Record<string, string | string[]>
  fix?: MasterCSSLintEditIR
}

export interface MasterCSSLintClassListIR {
  version: typeof MASTER_CSS_LINT_BATCH_VERSION
  analysis: MasterCSSLintBatchIR
  diagnostics: MasterCSSLintDiagnosticIR[]
  sortEdit?: MasterCSSLintEditIR
  conflictEdit?: MasterCSSLintEditIR
  conflictRange?: MasterCSSSourceRange
}

export type MasterCSSLanguageClassKind =
  | 'unknown'
  | 'component'
  | 'semantic'
  | 'pattern'
  | 'declaration'

export interface MasterCSSLanguageClassIR {
  className: string
  kind: MasterCSSLanguageClassKind
  matcherTypes: ('static' | 'pattern' | 'key' | 'variable' | 'value')[]
  keyToken?: string
  valueToken?: string
  stateToken?: string
  important: boolean
}

export interface MasterCSSLanguageClassificationsIR {
  version: typeof MASTER_CSS_LANGUAGE_BATCH_VERSION
  classes: MasterCSSLanguageClassIR[]
}

export interface MasterCSSLanguageInspectionIR {
  version: typeof MASTER_CSS_LANGUAGE_BATCH_VERSION
  className: string
  kind: MasterCSSLanguageClassKind
  text: string
}

export type MasterCSSLanguageCompletionKind = 'property' | 'value'

export interface MasterCSSLanguageCompletionEntryIR {
  label: string
  kind: MasterCSSLanguageCompletionKind
  detail?: string
  documentationText?: string
  sortText?: string
  triggerSuggest: boolean
}

export interface MasterCSSLanguageCompletionIndexIR {
  version: typeof MASTER_CSS_LANGUAGE_BATCH_VERSION
  classEntries: MasterCSSLanguageCompletionEntryIR[]
}

export interface MasterCSSLanguageColorPresentationIR {
  version: typeof MASTER_CSS_LANGUAGE_BATCH_VERSION
  colorToken: string
  space?: string
}

export interface MasterCSSLanguageColorCandidateInputIR {
  className: string
  start: number
}

export interface MasterCSSLanguageColorTokenIR {
  range: MasterCSSSourceRange
  value: string
  alpha?: number
}

export interface MasterCSSLanguageColorTokensIR {
  version: typeof MASTER_CSS_LANGUAGE_BATCH_VERSION
  tokens: MasterCSSLanguageColorTokenIR[]
}

export type MasterCSSDirectiveManifestInputIR =
  import('./css-directives').CSSDirectiveManifestInput

export type MasterCSSDirectiveVariableDefinitionIR =
  import('./css-directives').CSSDirectiveVariableDefinition

export interface MasterCSSRegexIR {
  source: string
  flags: string
}

export interface MasterCSSDirectiveExtractionPolicyIR {
  include: string[]
  exclude: string[]
  safelist: string[]
  blocklist: (string | MasterCSSRegexIR)[]
  preserveNative: boolean
}

export interface MasterCSSDirectiveCompilationIR {
  manifestInput: MasterCSSDirectiveManifestInputIR
  extractionPolicy: MasterCSSDirectiveExtractionPolicyIR
  classNames: string[]
  nativeClassNames: string[]
  warnings: string[]
  nativeCSS: string
  css: string
  generatedCSS: string
  dependencies: string[]
  styleDefinitions?: import('./css-directives').CSSDirectiveStyleDefinition[]
  references?: (import('./css-directives').CSSDirectiveReference & {
    start: number
    end: number
    statement: string
  })[]
}

export interface MasterCSSCompileManifestOptionsIR {
  baseManifest?: import('./manifest').MasterCSSManifest
}

export interface MasterCSSCompileManifestResultIR {
  manifest: import('./manifest').MasterCSSManifest
}

export interface MasterCSSCompileDefaultPresetRequestIR {
  manifestInput: MasterCSSDirectiveManifestInputIR
  styleDefinitions?: import('./css-directives').CSSDirectiveStyleDefinition[]
}

export interface MasterCSSCompileDefaultPresetResultIR {
  manifest: import('./manifest').MasterCSSManifest
  json: string
}

export interface MasterCSSServerRenderIR {
  classes: string[]
  snapshot: MasterCSSEngineSnapshotIR
  hydrationManifest: import('./hydration-manifest').MasterCSSHydrationManifest
}

export interface MasterCSSImportGraphEdgeIR {
  from: string
  specifier: string
  resolved: string
}

export interface MasterCSSImportGraphRequestIR {
  entry: string
  files: Record<string, string>
  edges: MasterCSSImportGraphEdgeIR[]
}

export interface MasterCSSResolvedImportGraphIR {
  source: string
  dependencies: string[]
  references?: MasterCSSDirectiveCompilationIR['references']
}

export type MasterCSSErrorCode =
{{MASTER_CSS_ERROR_CODES}}

export interface MasterCSSDiagnostic {
  code: MasterCSSErrorCode
  message: string
  source?: string
  range?: MasterCSSSourceRange
  notes?: string[]
}
