packages:
  - 'packages/*'
  - 'examples/*'
  - 'benchmarks'
  - 'shared'
  - 'internal'
  - 'site'

allowBuilds:
  '@aronrepo/*': true
  '@firebase/util': true
  '@parcel/watcher': true
  '@swc/core': true
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
  lmdb: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
  workerd: true

minimumReleaseAgeExclude:
  - '@aronrepo/*'

supportedArchitectures:
  os:
    - win32
    - darwin
    - linux
  cpu:
    - x64
    - arm64
    - arm
  libc:
    - glibc
    - musl

verifyDepsBeforeRun: false
