packages:
  - 'packages/*'
  - 'examples/*'
  - 'benchmarks/*'
  - 'shared'
  - 'internal'
  - 'site'

supportedArchitectures:
  os:
    - win32
    - darwin
    - linux
  cpu:
    - x64
    - arm64
    - arm
  libc:
    - glibc
    - musl

verifyDepsBeforeRun: false
