use super::*;

pub(crate) fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("workspace root exists")
}

pub(crate) fn generated_contract() -> String {
    let error_codes = mastercss_schema::ErrorCode::ALL
        .iter()
        .map(|code| format!("  | '{}'", code.as_wire_code()))
        .collect::<Vec<_>>()
        .join("\n");
    GENERATED_CONTRACT_TEMPLATE
        .replace(
            "{{MASTER_CSS_LANGUAGE_VERSION}}",
            &mastercss_schema::LANGUAGE_VERSION.to_string(),
        )
        .replace(
            "{{MASTER_CSS_BINDING_ABI_VERSION}}",
            &mastercss_schema::BINDING_ABI_VERSION.to_string(),
        )
        .replace(
            "{{MASTER_CSS_MANIFEST_VERSION}}",
            &mastercss_schema::MANIFEST_VERSION.to_string(),
        )
        .replace(
            "{{MASTER_CSS_HYDRATION_MANIFEST_VERSION}}",
            &mastercss_schema::HYDRATION_MANIFEST_VERSION.to_string(),
        )
        .replace(
            "{{MASTER_CSS_ENGINE_TRANSITION_VERSION}}",
            &mastercss_schema::ENGINE_TRANSITION_VERSION.to_string(),
        )
        .replace(
            "{{MASTER_CSS_VALIDATOR_BATCH_VERSION}}",
            &mastercss_schema::VALIDATOR_BATCH_VERSION.to_string(),
        )
        .replace(
            "{{MASTER_CSS_DIAGNOSTICS_REPORT_VERSION}}",
            &mastercss_schema::DIAGNOSTICS_REPORT_VERSION.to_string(),
        )
        .replace(
            "{{MASTER_CSS_LINT_BATCH_VERSION}}",
            &mastercss_schema::LINT_BATCH_VERSION.to_string(),
        )
        .replace(
            "{{MASTER_CSS_LANGUAGE_BATCH_VERSION}}",
            &mastercss_schema::LANGUAGE_BATCH_VERSION.to_string(),
        )
        .replace(
            "{{MASTER_CSS_LEXER_BATCH_VERSION}}",
            &mastercss_schema::LEXER_BATCH_VERSION.to_string(),
        )
        .replace(
            "{{MASTER_CSS_SOURCE_BATCH_VERSION}}",
            &mastercss_schema::SOURCE_BATCH_VERSION.to_string(),
        )
        .replace("{{MASTER_CSS_ERROR_CODES}}", &error_codes)
}

pub(crate) fn generated_package_version() -> String {
    format!(
        "// Generated by `cargo xtask codegen`. Do not edit directly.\n\nexport const MASTER_CSS_PACKAGE_VERSION = {:?} as const\n",
        env!("CARGO_PKG_VERSION")
    )
}

pub(crate) fn generated_builtin_registry() -> String {
    let token_namespaces = mastercss_engine::builtin_token_namespaces()
        .iter()
        .map(|(properties, variable_alias_refs)| {
            serde_json::json!({
                "properties": properties,
                "variableAliasRefs": variable_alias_refs,
            })
        })
        .collect::<Vec<_>>();
    let token_families = mastercss_engine::builtin_token_families().map(|(prefix, property, namespaces)| {
        serde_json::json!({"prefix": prefix, "property": property, "namespaces": namespaces.iter().map(|name| name.trim_start_matches('~')).collect::<Vec<_>>()})
    }).collect::<Vec<_>>();
    let token_families =
        serde_json::to_string_pretty(&token_families).expect("token families are serializable");
    let token_namespaces = serde_json::to_string_pretty(&token_namespaces)
        .expect("built-in native-value namespaces are serializable");

    format!(
        r#"// Generated by `cargo xtask codegen`. Do not edit directly.

export interface MasterCSSBuiltinTokenNamespace {{
  readonly properties: readonly string[]
  readonly variableAliasRefs: readonly string[]
}}

export interface MasterCSSBuiltinTokenFamily {{
  readonly prefix: string
  readonly property: string
  readonly namespaces: readonly string[]
}}

export const builtinTokenFamilies: readonly MasterCSSBuiltinTokenFamily[] = Object.freeze(
  {token_families}.map((family) => Object.freeze({{ ...family, namespaces: Object.freeze(family.namespaces) }}))
)

export type MasterCSSBuiltinTokenNamespaces = readonly MasterCSSBuiltinTokenNamespace[]


export const builtinTokenNamespaces = Object.freeze(
  {token_namespaces}.map((namespace) => Object.freeze({{
    properties: Object.freeze(namespace.properties),
    variableAliasRefs: Object.freeze(namespace.variableAliasRefs)
  }}))
) as MasterCSSBuiltinTokenNamespaces
"#
    )
}

pub(crate) fn check_generated_file(path: &Path, generated: &str) -> Result<(), String> {
    let current = fs::read_to_string(path)
        .map_err(|error| format!("Cannot read {}: {error}", path.display()))?;
    if current != generated {
        return Err(format!(
            "{} is stale. Run `cargo xtask codegen`.",
            path.display()
        ));
    }
    Ok(())
}

pub(crate) fn codegen(check: bool) -> Result<(), String> {
    let root = workspace_root();
    let outputs = [
        (
            root.join("packages/schema/src/keyframes.ts"),
            include_str!("../templates/keyframes.ts").to_owned(),
        ),
        (
            root.join("packages/schema/src/mixin.ts"),
            include_str!("../templates/mixin.ts").to_owned(),
        ),
        (
            root.join("packages/binding/src/protocol.ts"),
            generated_contract(),
        ),
        (
            root.join("packages/binding/src/version.ts"),
            generated_package_version(),
        ),
        (
            root.join("packages/tooling/src/builtins.ts"),
            generated_builtin_registry(),
        ),
    ];
    if check {
        for (output, generated) in &outputs {
            check_generated_file(output, generated)?;
        }
        return Ok(());
    }
    for (output, generated) in outputs {
        fs::write(&output, generated)
            .map_err(|error| format!("Cannot write {}: {error}", output.display()))?;
    }
    Ok(())
}
