use super::*;

pub(crate) fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("workspace root exists")
}

pub(crate) fn generated_contract() -> String {
    let error_codes = mastercss_schema::ErrorCode::ALL
        .iter()
        .map(|code| format!("  | '{}'", code.as_wire_code()))
        .collect::<Vec<_>>()
        .join("\n");
    GENERATED_CONTRACT_TEMPLATE
        .replace(
            "{{MASTER_CSS_BINDING_ABI_VERSION}}",
            &mastercss_schema::BINDING_ABI_VERSION.to_string(),
        )
        .replace(
            "{{MASTER_CSS_MANIFEST_VERSION}}",
            &mastercss_schema::MANIFEST_VERSION.to_string(),
        )
        .replace(
            "{{MASTER_CSS_HYDRATION_MANIFEST_VERSION}}",
            &mastercss_schema::HYDRATION_MANIFEST_VERSION.to_string(),
        )
        .replace(
            "{{MASTER_CSS_ENGINE_TRANSITION_VERSION}}",
            &mastercss_schema::ENGINE_TRANSITION_VERSION.to_string(),
        )
        .replace(
            "{{MASTER_CSS_VALIDATOR_BATCH_VERSION}}",
            &mastercss_schema::VALIDATOR_BATCH_VERSION.to_string(),
        )
        .replace(
            "{{MASTER_CSS_DIAGNOSTICS_REPORT_VERSION}}",
            &mastercss_schema::DIAGNOSTICS_REPORT_VERSION.to_string(),
        )
        .replace(
            "{{MASTER_CSS_LINT_BATCH_VERSION}}",
            &mastercss_schema::LINT_BATCH_VERSION.to_string(),
        )
        .replace(
            "{{MASTER_CSS_LANGUAGE_BATCH_VERSION}}",
            &mastercss_schema::LANGUAGE_BATCH_VERSION.to_string(),
        )
        .replace(
            "{{MASTER_CSS_LEXER_BATCH_VERSION}}",
            &mastercss_schema::LEXER_BATCH_VERSION.to_string(),
        )
        .replace(
            "{{MASTER_CSS_SOURCE_BATCH_VERSION}}",
            &mastercss_schema::SOURCE_BATCH_VERSION.to_string(),
        )
        .replace("{{MASTER_CSS_ERROR_CODES}}", &error_codes)
}

pub(crate) fn generated_package_version() -> String {
    format!(
        "// Generated by `cargo xtask codegen`. Do not edit directly.\n\nexport const MASTER_CSS_PACKAGE_VERSION = {:?} as const\n",
        env!("CARGO_PKG_VERSION")
    )
}

pub(crate) fn generated_builtin_registry() -> String {
    let key_aliases = mastercss_engine::builtin_key_aliases()
        .iter()
        .copied()
        .collect::<std::collections::BTreeMap<_, _>>();
    let native_value_namespaces = mastercss_engine::builtin_native_value_namespaces()
        .iter()
        .map(|(properties, variable_alias_refs)| {
            serde_json::json!({
                "properties": properties,
                "variableAliasRefs": variable_alias_refs,
            })
        })
        .collect::<Vec<_>>();
    let key_aliases =
        serde_json::to_string_pretty(&key_aliases).expect("built-in key aliases are serializable");
    let native_value_namespaces = serde_json::to_string_pretty(&native_value_namespaces)
        .expect("built-in native-value namespaces are serializable");

    format!(
        r#"// Generated by `cargo xtask codegen`. Do not edit directly.

export interface MasterCSSBuiltinNativeValueNamespace {{
  readonly properties: readonly string[]
  readonly variableAliasRefs: readonly string[]
}}

export type MasterCSSBuiltinKeyAliases = Readonly<Record<string, string>>
export type MasterCSSBuiltinNativeValueNamespaces = readonly MasterCSSBuiltinNativeValueNamespace[]

export const builtinKeyAliases = Object.freeze({key_aliases}) as MasterCSSBuiltinKeyAliases

export const builtinNativeValueNamespaces = Object.freeze(
  {native_value_namespaces}.map((namespace) => Object.freeze({{
    properties: Object.freeze(namespace.properties),
    variableAliasRefs: Object.freeze(namespace.variableAliasRefs)
  }}))
) as MasterCSSBuiltinNativeValueNamespaces
"#
    )
}

pub(crate) fn check_generated_file(path: &Path, generated: &str) -> Result<(), String> {
    let current = fs::read_to_string(path)
        .map_err(|error| format!("Cannot read {}: {error}", path.display()))?;
    if current != generated {
        return Err(format!(
            "{} is stale. Run `cargo xtask codegen`.",
            path.display()
        ));
    }
    Ok(())
}

pub(crate) fn codegen(check: bool) -> Result<(), String> {
    let root = workspace_root();
    let outputs = [
        (
            root.join("packages/binding/src/protocol.ts"),
            generated_contract(),
        ),
        (
            root.join("packages/binding/src/version.ts"),
            generated_package_version(),
        ),
        (
            root.join("packages/tooling/src/builtins.ts"),
            generated_builtin_registry(),
        ),
    ];
    if check {
        for (output, generated) in &outputs {
            check_generated_file(output, generated)?;
        }
        return Ok(());
    }
    for (output, generated) in outputs {
        fs::write(&output, generated)
            .map_err(|error| format!("Cannot write {}: {error}", output.display()))?;
    }
    Ok(())
}
