import { ModeDefinitions } from '../types/config'

const modes = {
    light: {
        base: '$white',
        canvas: '$slate-5',
        surface: '$white',
        invert: '$black',
        frame: {
            neutral: '$slate-60',
            light: '$slate-60/.2',
            lighter: '$slate-60/.16',
            lightest: '$slate-60/.12'
        },
        gray: '$gray-30',
        slate: '$slate-30',
        brown: '$brown-40',
        orange: '$orange-40',
        amber: '$amber-40',
        yellow: '$yellow-40',
        lime: '$lime-40',
        green: '$green-40',
        beryl: '$beryl-40',
        teal: '$teal-40',
        cyan: '$cyan-40',
        sky: '$sky-60',
        blue: '$blue-60',
        indigo: '$indigo-60',
        violet: '$violet-60',
        purple: '$purple-60',
        fuchsia: '$fuchsia-60',
        pink: '$pink-60',
        crimson: '$crimson-60',
        red: '$red-60',
        text: {
            invert: '$white',
            strong: '$slate-95',
            neutral: '$slate-70',
            lightest: '$slate-30',
            lighter: '$slate-40',
            light: '$slate-50',
            gray: '$gray-60',
            slate: '$slate-60',
            brown: '$brown-60',
            orange: '$orange-60',
            amber: '$amber-60',
            yellow: '$yellow-60',
            lime: '$lime-70',
            green: '$green-70',
            beryl: '$beryl-70',
            teal: '$teal-70',
            cyan: '$cyan-70',
            sky: '$sky-70',
            blue: '$blue-60',
            indigo: '$indigo-60',
            violet: '$violet-60',
            purple: '$purple-60',
            fuchsia: '$fuchsia-60',
            pink: '$pink-60',
            crimson: '$crimson-60',
            red: '$red-60'
        },
    },
    dark: {
        base: '$gray-95',
        canvas: '$gray-90',
        surface: '$gray-80',
        invert: '$white',
        frame: {
            neutral: '$gray-30',
            light: '$gray-30/.2',
            lighter: '$gray-30/.16',
            lightest: '$gray-30/.12'
        },
        gray: '$gray-40',
        slate: '$slate-40',
        brown: '$brown-50',
        orange: '$orange-50',
        amber: '$amber-50',
        yellow: '$yellow-50',
        lime: '$lime-50',
        green: '$green-50',
        beryl: '$beryl-50',
        teal: '$teal-50',
        cyan: '$cyan-50',
        sky: '$sky-50',
        blue: '$blue-50',
        indigo: '$indigo-50',
        violet: '$violet-50',
        purple: '$purple-50',
        fuchsia: '$fuchsia-50',
        pink: '$pink-50',
        crimson: '$crimson-50',
        red: '$red-50',
        text: {
            invert: '$black',
            strong: '$gray-10',
            neutral: '$gray-30',
            lightest: '$gray-60',
            lighter: '$gray-50',
            light: '$gray-40',
            gray: '$gray-30',
            slate: '$slate-30',
            brown: '$brown-30',
            orange: '$orange-30',
            amber: '$amber-40',
            yellow: '$yellow-40',
            lime: '$lime-40',
            green: '$green-40',
            beryl: '$beryl-40',
            teal: '$teal-40',
            cyan: '$cyan-40',
            sky: '$sky-30',
            blue: '$blue-30',
            indigo: '$indigo-30',
            violet: '$violet-30',
            purple: '$purple-30',
            fuchsia: '$fuchsia-30',
            pink: '$pink-30',
            crimson: '$crimson-30',
            red: '$red-30'
        },

    }
} satisfies ModeDefinitions

export default modes