// Generated by `cargo xtask codegen`. Do not edit directly.
import type { CSSDirectiveSourceReference } from './css-directives.js'

export interface MasterCSSKeyframeDefinition {
  name: string
  text: string
  dependencies?: string[]
  source?: CSSDirectiveSourceReference
}
