// Generated by `cargo xtask codegen`. Do not edit directly.

export const MASTER_CSS_BINDING_ABI_VERSION = 4 as const
export const MASTER_CSS_MANIFEST_VERSION = 1 as const
export const MASTER_CSS_HYDRATION_MANIFEST_VERSION = 1 as const
export const MASTER_CSS_ENGINE_TRANSITION_VERSION = 1 as const
export const MASTER_CSS_VALIDATOR_BATCH_VERSION = 1 as const
export const MASTER_CSS_DIAGNOSTICS_REPORT_VERSION = 1 as const
export const MASTER_CSS_LINT_BATCH_VERSION = 1 as const
export const MASTER_CSS_LANGUAGE_BATCH_VERSION = 1 as const
export const MASTER_CSS_LEXER_BATCH_VERSION = 1 as const
export const MASTER_CSS_SOURCE_BATCH_VERSION = 1 as const

export type MasterCSSBindingSurface = 'native' | 'runtime' | 'compiler' | 'tooling' | 'cli'

export type MasterCSSBindingFeature =
  | 'cli'
  | 'compiler'
  | 'diagnostics'
  | 'engine'
  | 'language'
  | 'lexer'
  | 'lint'
  | 'project'
  | 'render'
  | 'scanner'
  | 'source'
  | 'validator'

export interface MasterCSSBindingInfo {
  bindingAbiVersion: typeof MASTER_CSS_BINDING_ABI_VERSION
  packageVersion: string
  manifestVersion: typeof MASTER_CSS_MANIFEST_VERSION
  hydrationManifestVersion: typeof MASTER_CSS_HYDRATION_MANIFEST_VERSION
  engineTransitionVersion: typeof MASTER_CSS_ENGINE_TRANSITION_VERSION
  validatorBatchVersion: typeof MASTER_CSS_VALIDATOR_BATCH_VERSION
  diagnosticsReportVersion: typeof MASTER_CSS_DIAGNOSTICS_REPORT_VERSION
  lintBatchVersion: typeof MASTER_CSS_LINT_BATCH_VERSION
  languageBatchVersion: typeof MASTER_CSS_LANGUAGE_BATCH_VERSION
  lexerBatchVersion: typeof MASTER_CSS_LEXER_BATCH_VERSION
  sourceBatchVersion: typeof MASTER_CSS_SOURCE_BATCH_VERSION
  target: string
  surface: MasterCSSBindingSurface
  features: MasterCSSBindingFeature[]
}

export type MasterCSSBackend = 'auto' | 'native' | 'wasm'
export type MasterCSSResolvedBackend = Exclude<MasterCSSBackend, 'auto'>
export type MasterCSSRuleTarget =
  | 'theme'
  | 'base'
  | 'defaults'
  | 'components'
  | 'utilities'
  | 'keyframes'

export interface MasterCSSSourceRange {
  start: number
  end: number
}

export interface MasterCSSEngineInsertMutationIR {
  op: 'insert'
  target: MasterCSSRuleTarget
  index: number
  key: string
  text: string
  rule?: import('./hydration-manifest').MasterCSSGeneratedRuleIR
}

export interface MasterCSSEngineDeleteMutationIR {
  op: 'delete'
  target: MasterCSSRuleTarget
  index: number
  key: string
}

export type MasterCSSEngineMutationIR =
  | MasterCSSEngineInsertMutationIR
  | MasterCSSEngineDeleteMutationIR

export interface MasterCSSEngineTransitionIR {
  version: typeof MASTER_CSS_ENGINE_TRANSITION_VERSION
  mutations: MasterCSSEngineMutationIR[]
}

export interface MasterCSSEngineSnapshotIR {
  version: 1
  rules: import('./hydration-manifest').MasterCSSGeneratedRuleIR[]
  resources: MasterCSSEngineResourcesIR
  text: string
}

export interface MasterCSSEngineVariableResourceIR {
  name: string
  refCount: number
  dependencies: string[]
  static: boolean
}

export interface MasterCSSEngineAnimationResourceIR {
  name: string
  index: number
  refCount: number
  text: string
}

export interface MasterCSSEngineResourcesIR {
  themeText?: string
  variables: MasterCSSEngineVariableResourceIR[]
  animations: MasterCSSEngineAnimationResourceIR[]
}

export interface MasterCSSEngineInspectionIR {
  version: 1
  className: string
  valid: boolean
  rules: import('./hydration-manifest').MasterCSSGeneratedRuleIR[]
}

export interface MasterCSSNativeDeclarationCandidateIR {
  className: string
  property: string
  value: string
}

export interface MasterCSSLexerClassListInputIR {
  source: string
  unescape?: string[]
}

export interface MasterCSSLexerBatchRequestIR {
  classLists?: MasterCSSLexerClassListInputIR[]
  cssSources?: string[]
  escapeIdentifiers?: string[]
}

export interface MasterCSSLexerClassListItemIR {
  range: MasterCSSSourceRange
  raw: string
  token: string
}

export interface MasterCSSLexerCSSDirectiveIR {
  name: string
  range: MasterCSSSourceRange
  preludeRange: MasterCSSSourceRange
  hasBlock: boolean
  quotedStrings: number
}

export interface MasterCSSLexerCSSImportIR {
  range: MasterCSSSourceRange
  statement: string
  source?: string
}

export interface MasterCSSLexerCSSAnalysisIR {
  directives: MasterCSSLexerCSSDirectiveIR[]
  imports: MasterCSSLexerCSSImportIR[]
}

export interface MasterCSSLexerBatchIR {
  version: typeof MASTER_CSS_LEXER_BATCH_VERSION
  classLists: MasterCSSLexerClassListItemIR[][]
  cssSources: MasterCSSLexerCSSAnalysisIR[]
  escapedIdentifiers: string[]
}

export type MasterCSSSourceExtractorKind = 'auto' | 'raw' | 'oxc' | 'html' | 'astro'

export interface MasterCSSSourceExtractionInputIR {
  source: string
  content: string
  kind?: MasterCSSSourceExtractorKind
}

export interface MasterCSSSourceBatchRequestIR {
  files: MasterCSSSourceExtractionInputIR[]
}

export interface MasterCSSSourceExtractionIR {
  source: string
  candidates: string[]
}

export interface MasterCSSSourceBatchIR {
  version: typeof MASTER_CSS_SOURCE_BATCH_VERSION
  files: MasterCSSSourceExtractionIR[]
}

export type MasterCSSInspectionDiagnosticSeverity = 'error' | 'warning'
export type MasterCSSInspectionDiagnosticCode =
  | 'invalid-scanner-class'
  | 'missing-css'
  | 'stylesheet-error'
  | 'stylesheet-warning'
  | 'scanner-error'
export type MasterCSSInspectionDiagnosticSourceKind = 'scanner' | 'stylesheet' | 'missing-css'
export type MasterCSSMissingCSSStatus = 'present' | 'missing'
export type MasterCSSMissingCSSReason =
  | 'generated'
  | 'native-css'
  | 'safelist'
  | 'invalid'
  | 'blocklisted'
  | 'not-detected'

export interface MasterCSSMissingCSSResultIR {
  className: string
  status: MasterCSSMissingCSSStatus
  reason: MasterCSSMissingCSSReason
}

export type MasterCSSInspectionDiagnosticDataIR =
  | { cwd: string }
  | { className: string }
  | MasterCSSMissingCSSResultIR

export interface MasterCSSInspectionDiagnosticIR {
  code: MasterCSSInspectionDiagnosticCode
  severity: MasterCSSInspectionDiagnosticSeverity
  message: string
  source: 'Master CSS'
  sourceKind: MasterCSSInspectionDiagnosticSourceKind
  filePath?: string
  data?: MasterCSSInspectionDiagnosticDataIR
}

export interface MasterCSSDiscoveredClassesIR {
  latent: string[]
  valid: string[]
  invalid: string[]
  usedNative: string[]
}

export interface MasterCSSSourceInspectionIR {
  filePath: string
  source: string
  scanned: boolean
  changed: boolean
  discovered: MasterCSSDiscoveredClassesIR
}

export interface MasterCSSStylesheetInspectionIR {
  filePath: string
  masterCSS: boolean
  pruneNativeCSS: boolean
  dependencies: string[]
  sourceDependencies: string[]
  warnings: string[]
  errors: string[]
}

export interface MasterCSSStylesheetErrorIR {
  filePath: string
  message: string
}

export interface MasterCSSDiagnosticsReportInputIR {
  version: typeof MASTER_CSS_DIAGNOSTICS_REPORT_VERSION
  cwd: string
  patterns: string[]
  files: MasterCSSSourceInspectionIR[]
  classes: string[]
  scanner: {
    latent?: string[]
    valid?: string[]
    invalid?: string[]
    native?: string[]
    usedNative?: string[]
    safelist?: string[]
    blocklist?: (string | MasterCSSRegexIR)[]
    resetDependencies?: string[]
  }
  stylesheets: {
    entries?: MasterCSSStylesheetInspectionIR[]
    warnings?: string[]
    errors?: MasterCSSStylesheetErrorIR[]
  }
  css: {
    text?: string
    included?: boolean
    variables?: string[]
    animations?: string[]
  }
  firstSourceByClass?: Record<string, string>
  fatalError?: string
}

export interface MasterCSSInspectionReportIR {
  version: typeof MASTER_CSS_DIAGNOSTICS_REPORT_VERSION
  cwd: string
  inputs: {
    patterns: string[]
    files: string[]
    classes: string[]
  }
  scanner: {
    counts: {
      latent: number
      valid: number
      invalid: number
      native: number
      usedNative: number
      safelist: number
      blocklist: number
    }
    classes: {
      latent: string[]
      valid: string[]
      invalid: string[]
      native: string[]
      usedNative: string[]
      safelist: string[]
      blocklist: string[]
    }
    resetDependencies: string[]
  }
  stylesheets: {
    entries: MasterCSSStylesheetInspectionIR[]
    dependencies: string[]
    warnings: string[]
    errors: MasterCSSStylesheetErrorIR[]
  }
  css: {
    bytes: number
    included: boolean
    text?: string
    emittedGlobals: {
      variables: number
      animations: number
    }
  }
  missingCSS: {
    checked: string[]
    present: MasterCSSMissingCSSResultIR[]
    missing: MasterCSSMissingCSSResultIR[]
  }
  files: MasterCSSSourceInspectionIR[]
  diagnostics: MasterCSSInspectionDiagnosticIR[]
  summary: {
    files: number
    stylesheets: number
    diagnostics: number
    errors: number
    warnings: number
    missingCSS: number
    invalidClasses: number
  }
}

export interface MasterCSSValidatorClassIR {
  className: string
  matched: boolean
  rules: import('./hydration-manifest').MasterCSSGeneratedRuleIR[]
}

export interface MasterCSSValidatorBatchIR {
  version: typeof MASTER_CSS_VALIDATOR_BATCH_VERSION
  classes: MasterCSSValidatorClassIR[]
}

export interface MasterCSSLintClassConflictIR {
  className: string
  conflicts: string[]
}

export interface MasterCSSLintPartialClassConflictIR {
  className: string
  replacement: string
  conflict: string
}

export interface MasterCSSLintBatchIR {
  version: typeof MASTER_CSS_LINT_BATCH_VERSION
  sortedClassNames: string[]
  conflicts: MasterCSSLintClassConflictIR[]
  partialConflicts: MasterCSSLintPartialClassConflictIR[]
}

export interface MasterCSSLintRawValueCandidateIR {
  className: string
  key: string
  segments: string[]
  properties: string[]
}

export interface MasterCSSLintRawValueCandidatesIR {
  version: typeof MASTER_CSS_LINT_BATCH_VERSION
  candidates: MasterCSSLintRawValueCandidateIR[]
}

export interface MasterCSSLintCanonicalClassNameOptionsIR {
  preferStaticUtilities: boolean
  preferThemeTokens: boolean
  preferPropertyAliases: boolean
  preferVariableReferences: boolean
  preferMultiValueTokens: boolean
  preferCompositionUtilities: boolean
  preferConditionOrder: boolean
  preferNativeDeclarationsInCompose: boolean
  preferVariantBlocksInCompose: boolean
}

export interface MasterCSSLintCanonicalClassSuggestionIR {
  className: string
  recommended: string
}

export interface MasterCSSLintCanonicalClassSuggestionsIR {
  version: typeof MASTER_CSS_LINT_BATCH_VERSION
  suggestions: MasterCSSLintCanonicalClassSuggestionIR[]
}

export interface MasterCSSLintCanonicalClassGroupSuggestionIR {
  classNames: string[]
  recommended: string
}

export interface MasterCSSLintCanonicalClassGroupSuggestionsIR {
  version: typeof MASTER_CSS_LINT_BATCH_VERSION
  suggestions: MasterCSSLintCanonicalClassGroupSuggestionIR[]
}

export type MasterCSSLintCanonicalComposeSuggestionKind =
  | 'class'
  | 'native-declaration'
  | 'variant-block'

export interface MasterCSSLintCanonicalComposeSuggestionIR {
  actual: string
  recommended: string
  classNames: string[]
  kind: MasterCSSLintCanonicalComposeSuggestionKind
}

export interface MasterCSSLintCanonicalComposeDirectiveIR {
  version: typeof MASTER_CSS_LINT_BATCH_VERSION
  suggestions: MasterCSSLintCanonicalComposeSuggestionIR[]
  structuralChange?: boolean
  replacement?: string
}

export interface MasterCSSLintEditIR {
  range: MasterCSSSourceRange
  text: string
  scope: 'class-list' | 'directive'
}

export interface MasterCSSLintDiagnosticIR {
  ruleId: 'sort-classes' | 'no-invalid-classes' | 'no-conflicting-classes' | 'prefer-canonical-classes' | 'no-unapproved-raw-values'
  code:
    | 'invalid-class-order'
    | 'invalid-class'
    | 'unknown-class'
    | 'conflicting-class'
    | 'partially-conflicting-class'
    | 'prefer-canonical-class'
    | 'prefer-native-declaration'
    | 'prefer-variant-block'
    | 'unapproved-raw-value'
  message: string
  range: MasterCSSSourceRange
  data?: Record<string, string | number | boolean | string[] | null>
  fix?: MasterCSSLintEditIR
}

export interface MasterCSSLintClassListIR {
  version: typeof MASTER_CSS_LINT_BATCH_VERSION
  analysis: MasterCSSLintBatchIR
  diagnostics: MasterCSSLintDiagnosticIR[]
  sortEdit?: MasterCSSLintEditIR
  conflictEdit?: MasterCSSLintEditIR
  conflictRange?: MasterCSSSourceRange
}

export type MasterCSSLanguageClassKind =
  | 'unknown'
  | 'component'
  | 'semantic'
  | 'pattern'
  | 'declaration'

export interface MasterCSSLanguageClassIR {
  className: string
  kind: MasterCSSLanguageClassKind
  matcherTypes: ('static' | 'pattern' | 'key' | 'variable' | 'value')[]
  keyToken?: string
  valueToken?: string
  stateToken?: string
  important: boolean
}

export interface MasterCSSLanguageClassificationsIR {
  version: typeof MASTER_CSS_LANGUAGE_BATCH_VERSION
  variableNames: string[]
  classes: MasterCSSLanguageClassIR[]
}

export interface MasterCSSLanguageVariableIR {
  namespace?: string
  name: string
  key: string
  type: string
  value?: string | number
  numeric?: import('./manifest').MasterCSSManifestVariableNumericValue
  modes?: import('./manifest').MasterCSSManifestVariable['modes']
  dependencies?: string[]
  inline?: boolean
  static?: boolean
}

export interface MasterCSSLanguageClassVariableIR {
  key: string
  variable: MasterCSSLanguageVariableIR
}

export interface MasterCSSLanguageInspectionIR {
  version: typeof MASTER_CSS_LANGUAGE_BATCH_VERSION
  className: string
  valid: boolean
  kind: MasterCSSLanguageClassKind
  base: string
  suffix: string
  key?: string
  value?: string
  keyToken?: string
  valueToken?: string
  stateToken?: string
  important: boolean
  matcherTypes: ('static' | 'pattern' | 'key' | 'variable' | 'value')[]
  variables: MasterCSSLanguageClassVariableIR[]
  rules: import('./hydration-manifest').MasterCSSGeneratedRuleIR[]
  text: string
}

export type MasterCSSLanguageCompletionKind = 'property' | 'value'

export interface MasterCSSLanguageCompletionEntryIR {
  label: string
  kind: MasterCSSLanguageCompletionKind
  detail?: string
  documentationText?: string
  sortText?: string
  triggerSuggest: boolean
}

export interface MasterCSSLanguageCompletionIndexIR {
  version: typeof MASTER_CSS_LANGUAGE_BATCH_VERSION
  classEntries: MasterCSSLanguageCompletionEntryIR[]
}

export interface MasterCSSLanguageColorPresentationIR {
  version: typeof MASTER_CSS_LANGUAGE_BATCH_VERSION
  colorToken: string
  space?: string
}

export interface MasterCSSLanguageColorCandidateInputIR {
  className: string
  start: number
}

export interface MasterCSSLanguageColorTokenIR {
  range: MasterCSSSourceRange
  value: string
  alpha?: number
}

export interface MasterCSSLanguageColorTokensIR {
  version: typeof MASTER_CSS_LANGUAGE_BATCH_VERSION
  tokens: MasterCSSLanguageColorTokenIR[]
}

export type MasterCSSDirectiveManifestInputIR =
  import('./css-directives').CSSDirectiveManifestInput

export type MasterCSSDirectiveVariableDefinitionIR =
  import('./css-directives').CSSDirectiveVariableDefinition

export interface MasterCSSRegexIR {
  source: string
  flags: string
}

export interface MasterCSSDirectiveExtractionPolicyIR {
  include: string[]
  exclude: string[]
  safelist: string[]
  blocklist: (string | MasterCSSRegexIR)[]
  preserveNative: boolean
}

export interface MasterCSSDirectiveCompilationIR {
  manifestInput: MasterCSSDirectiveManifestInputIR
  extractionPolicy: MasterCSSDirectiveExtractionPolicyIR
  classNames: string[]
  nativeClassNames: string[]
  warnings: string[]
  nativeCSS: string
  css: string
  generatedCSS: string
  dependencies: string[]
  styleDefinitions?: import('./css-directives').CSSDirectiveStyleDefinition[]
  references?: (import('./css-directives').CSSDirectiveReference & {
    start: number
    end: number
    statement: string
  })[]
}

export interface MasterCSSCompileManifestOptionsIR {
  baseManifest?: import('./manifest').MasterCSSManifest
}

export interface MasterCSSCompileManifestResultIR {
  manifest: import('./manifest').MasterCSSManifest
}

export interface MasterCSSCompileDefaultPresetRequestIR {
  manifestInput: MasterCSSDirectiveManifestInputIR
  styleDefinitions?: import('./css-directives').CSSDirectiveStyleDefinition[]
}

export interface MasterCSSCompileDefaultPresetResultIR {
  manifest: import('./manifest').MasterCSSManifest
  json: string
}

export interface MasterCSSServerRenderIR {
  classes: string[]
  snapshot: MasterCSSEngineSnapshotIR
  hydrationManifest: import('./hydration-manifest').MasterCSSHydrationManifest
}

export interface MasterCSSImportGraphEdgeIR {
  from: string
  specifier: string
  resolved: string
}

export interface MasterCSSImportGraphRequestIR {
  entry: string
  files: Record<string, string>
  edges: MasterCSSImportGraphEdgeIR[]
}

export interface MasterCSSResolvedImportGraphIR {
  source: string
  dependencies: string[]
  references?: MasterCSSDirectiveCompilationIR['references']
}

export type MasterCSSErrorCode =
  | 'INVALID_MANIFEST'
  | 'UNSUPPORTED_MANIFEST_VERSION'
  | 'INVALID_HYDRATION_MANIFEST'
  | 'NATIVE_UNAVAILABLE'
  | 'NATIVE_LOAD_FAILED'
  | 'WASM_LOAD_FAILED'
  | 'RUNTIME_STARTUP_TIMEOUT'
  | 'CSS_PARSE_ERROR'
  | 'CSS_PRINT_ERROR'
  | 'CSS_DIRECTIVE_ERROR'
  | 'invalid-compose-class'
  | 'compose-quoted-syntax'
  | 'compose-group-syntax'
  | 'CSS_IMPORT_ERROR'
  | 'SESSION_DISPOSED'
  | 'INVALID_INPUT'
  | 'INTERNAL'

export interface MasterCSSDiagnostic {
  code: MasterCSSErrorCode
  message: string
  source?: string
  range?: MasterCSSSourceRange
  notes?: string[]
}
