// Generated by `cargo xtask codegen`. Do not edit directly.

export const MASTER_CSS_ENGINE_TRANSITION_VERSION = 1 as const
export const MASTER_CSS_VALIDATOR_BATCH_VERSION = 1 as const
export const MASTER_CSS_DIAGNOSTICS_REPORT_VERSION = 1 as const
export const MASTER_CSS_LINT_BATCH_VERSION = 1 as const

export type MasterCSSBackend = 'auto' | 'native' | 'wasm'
export type MasterCSSResolvedBackend = Exclude<MasterCSSBackend, 'auto'>
export type MasterCSSRuleTarget =
  | 'theme'
  | 'base'
  | 'defaults'
  | 'components'
  | 'utilities'
  | 'keyframes'

export interface MasterCSSSourceRange {
  start: number
  end: number
}

export interface MasterCSSEngineInsertMutationIR {
  op: 'insert'
  target: MasterCSSRuleTarget
  index: number
  key: string
  text: string
  rule?: import('./hydration-manifest').MasterCSSGeneratedRuleIR
}

export interface MasterCSSEngineDeleteMutationIR {
  op: 'delete'
  target: MasterCSSRuleTarget
  index: number
  key: string
}

export type MasterCSSEngineMutationIR =
  | MasterCSSEngineInsertMutationIR
  | MasterCSSEngineDeleteMutationIR

export interface MasterCSSEngineTransitionIR {
  version: typeof MASTER_CSS_ENGINE_TRANSITION_VERSION
  mutations: MasterCSSEngineMutationIR[]
}

export interface MasterCSSEngineSnapshotIR {
  version: 1
  rules: import('./hydration-manifest').MasterCSSGeneratedRuleIR[]
  text: string
}

export interface MasterCSSEngineInspectionIR {
  version: 1
  className: string
  valid: boolean
  rules: import('./hydration-manifest').MasterCSSGeneratedRuleIR[]
}

export interface MasterCSSNativeDeclarationCandidateIR {
  className: string
  property: string
  value: string
}

export interface MasterCSSValidatorClassIR {
  className: string
  matched: boolean
  rules: import('./hydration-manifest').MasterCSSGeneratedRuleIR[]
}

export interface MasterCSSValidatorBatchIR {
  version: typeof MASTER_CSS_VALIDATOR_BATCH_VERSION
  classes: MasterCSSValidatorClassIR[]
}

export type MasterCSSDirectiveManifestInputIR =
  import('./css-directives').CSSDirectiveManifestInput

export type MasterCSSDirectiveVariableDefinitionIR =
  import('./css-directives').CSSDirectiveVariableDefinition

export interface MasterCSSRegexIR {
  source: string
  flags: string
}

export interface MasterCSSDirectiveExtractionPolicyIR {
  include: string[]
  exclude: string[]
  safelist: string[]
  blocklist: (string | MasterCSSRegexIR)[]
  preserveNative: boolean
}

export interface MasterCSSDirectiveCompilationIR {
  manifestInput: MasterCSSDirectiveManifestInputIR
  extractionPolicy: MasterCSSDirectiveExtractionPolicyIR
  classNames: string[]
  nativeClassNames: string[]
  warnings: string[]
  nativeCSS: string
  css: string
  generatedCSS: string
  dependencies: string[]
  styleDefinitions?: import('./css-directives').CSSDirectiveStyleDefinition[]
  references?: (import('./css-directives').CSSDirectiveReference & {
    start: number
    end: number
    statement: string
  })[]
}

export interface MasterCSSCompileManifestOptionsIR {
  baseManifest?: import('./manifest').MasterCSSManifest
}

export interface MasterCSSCompileManifestResultIR {
  manifest: import('./manifest').MasterCSSManifest
}

export interface MasterCSSCompileDefaultPresetRequestIR {
  manifestInput: MasterCSSDirectiveManifestInputIR
  styleDefinitions?: import('./css-directives').CSSDirectiveStyleDefinition[]
}

export interface MasterCSSCompileDefaultPresetResultIR {
  manifest: import('./manifest').MasterCSSManifest
  json: string
}

export interface MasterCSSServerRenderIR {
  classes: string[]
  snapshot: MasterCSSEngineSnapshotIR
  hydrationManifest: import('./hydration-manifest').MasterCSSHydrationManifest
}

export interface MasterCSSImportGraphEdgeIR {
  from: string
  specifier: string
  resolved: string
}

export interface MasterCSSImportGraphRequestIR {
  entry: string
  files: Record<string, string>
  edges: MasterCSSImportGraphEdgeIR[]
}

export interface MasterCSSResolvedImportGraphIR {
  source: string
  dependencies: string[]
  references?: MasterCSSDirectiveCompilationIR['references']
}

export type MasterCSSErrorCode =
  | 'INVALID_MANIFEST'
  | 'UNSUPPORTED_MANIFEST_VERSION'
  | 'INVALID_HYDRATION_MANIFEST'
  | 'NATIVE_UNAVAILABLE'
  | 'NATIVE_LOAD_FAILED'
  | 'WASM_LOAD_FAILED'
  | 'RUNTIME_STARTUP_TIMEOUT'
  | 'CSS_PARSE_ERROR'
  | 'CSS_PRINT_ERROR'
  | 'CSS_DIRECTIVE_ERROR'
  | 'CSS_IMPORT_ERROR'
  | 'SESSION_DISPOSED'
  | 'INVALID_INPUT'
  | 'INTERNAL'

export interface MasterCSSDiagnostic {
  code: MasterCSSErrorCode
  message: string
  source?: string
  range?: MasterCSSSourceRange
  notes?: string[]
}
