export { getConfigFileColorRender, getDocumentColors, getColorValue, getColorPresentation } from './providers/color'
export { checkConfigColorsBlock, getLastInstance, getConfigColorsCompletionItem, getCompletionItem } from './providers/completion'
export { doHover } from './providers/hover'
export { positionCheck } from './position-check'
export * as default from './server'