// Generated by `cargo xtask codegen`. Do not edit directly.

export interface MasterCSSBuiltinNativeValueNamespace {
  readonly properties: readonly string[]
  readonly variableAliasRefs: readonly string[]
}

export type MasterCSSBuiltinKeyAliases = Readonly<Record<string, string>>
export type MasterCSSBuiltinNativeValueNamespaces = readonly MasterCSSBuiltinNativeValueNamespace[]

export const builtinKeyAliases = Object.freeze({
  "b": "border",
  "bb": "border-bottom",
  "bg": "background",
  "bl": "border-left",
  "br": "border-right",
  "bt": "border-top",
  "bx": "border-inline",
  "by": "border-block",
  "fg": "color",
  "gap-x": "column-gap",
  "gap-y": "row-gap",
  "grid-col": "grid-column",
  "grid-col-end": "grid-column-end",
  "grid-col-start": "grid-column-start",
  "h": "height",
  "ix": "inset-inline",
  "ixe": "inset-inline-end",
  "ixs": "inset-inline-start",
  "iy": "inset-block",
  "iye": "inset-block-end",
  "iys": "inset-block-start",
  "leading": "line-height",
  "line-clamp": "-webkit-line-clamp",
  "m": "margin",
  "max": "max-size",
  "max-h": "max-height",
  "max-size-x": "max-inline-size",
  "max-size-y": "max-block-size",
  "max-w": "max-width",
  "mb": "margin-bottom",
  "min": "min-size",
  "min-h": "min-height",
  "min-size-x": "min-inline-size",
  "min-size-y": "min-block-size",
  "min-w": "min-width",
  "ml": "margin-left",
  "mr": "margin-right",
  "mt": "margin-top",
  "mx": "margin-inline",
  "mxe": "margin-inline-end",
  "mxs": "margin-inline-start",
  "my": "margin-block",
  "mye": "margin-block-end",
  "mys": "margin-block-start",
  "p": "padding",
  "pb": "padding-bottom",
  "pl": "padding-left",
  "pr": "padding-right",
  "pt": "padding-top",
  "px": "padding-inline",
  "pxe": "padding-inline-end",
  "pxs": "padding-inline-start",
  "py": "padding-block",
  "pye": "padding-block-end",
  "pys": "padding-block-start",
  "r": "border-radius",
  "rbl": "border-bottom-left-radius",
  "rbr": "border-bottom-right-radius",
  "rtl": "border-top-left-radius",
  "rtr": "border-top-right-radius",
  "scroll-m": "scroll-margin",
  "scroll-mb": "scroll-margin-bottom",
  "scroll-ml": "scroll-margin-left",
  "scroll-mr": "scroll-margin-right",
  "scroll-mt": "scroll-margin-top",
  "scroll-mx": "scroll-margin-inline",
  "scroll-mxe": "scroll-margin-inline-end",
  "scroll-mxs": "scroll-margin-inline-start",
  "scroll-my": "scroll-margin-block",
  "scroll-mye": "scroll-margin-block-end",
  "scroll-mys": "scroll-margin-block-start",
  "scroll-p": "scroll-padding",
  "scroll-pb": "scroll-padding-bottom",
  "scroll-pl": "scroll-padding-left",
  "scroll-pr": "scroll-padding-right",
  "scroll-pt": "scroll-padding-top",
  "scroll-px": "scroll-padding-inline",
  "scroll-pxe": "scroll-padding-inline-end",
  "scroll-pxs": "scroll-padding-inline-start",
  "scroll-py": "scroll-padding-block",
  "scroll-pye": "scroll-padding-block-end",
  "scroll-pys": "scroll-padding-block-start",
  "shadow": "box-shadow",
  "size-x": "inline-size",
  "size-y": "block-size",
  "text-fill-color": "-webkit-text-fill-color",
  "text-stroke-color": "-webkit-text-stroke-color",
  "text-stroke-width": "-webkit-text-stroke-width",
  "tracking": "letter-spacing",
  "w": "width",
  "z": "z-index"
}) as MasterCSSBuiltinKeyAliases

export const builtinNativeValueNamespaces = Object.freeze(
  [
  {
    "properties": [
      "background-position",
      "bottom",
      "border-spacing",
      "column-gap",
      "gap",
      "inset",
      "inset-block",
      "inset-block-end",
      "inset-block-start",
      "inset-inline",
      "inset-inline-end",
      "inset-inline-start",
      "left",
      "margin",
      "margin-block",
      "margin-block-end",
      "margin-block-start",
      "margin-bottom",
      "margin-inline",
      "margin-inline-end",
      "margin-inline-start",
      "margin-left",
      "margin-right",
      "margin-top",
      "mask-position",
      "object-position",
      "outline-offset",
      "padding",
      "padding-block",
      "padding-block-end",
      "padding-block-start",
      "padding-bottom",
      "padding-inline",
      "padding-inline-end",
      "padding-inline-start",
      "padding-left",
      "padding-right",
      "padding-top",
      "perspective",
      "perspective-origin",
      "right",
      "row-gap",
      "scroll-margin",
      "scroll-margin-block",
      "scroll-margin-block-end",
      "scroll-margin-block-start",
      "scroll-margin-bottom",
      "scroll-margin-inline",
      "scroll-margin-inline-end",
      "scroll-margin-inline-start",
      "scroll-margin-left",
      "scroll-margin-right",
      "scroll-margin-top",
      "scroll-padding",
      "scroll-padding-block",
      "scroll-padding-block-end",
      "scroll-padding-block-start",
      "scroll-padding-bottom",
      "scroll-padding-inline",
      "scroll-padding-inline-end",
      "scroll-padding-inline-start",
      "scroll-padding-left",
      "scroll-padding-right",
      "scroll-padding-top",
      "shape-margin",
      "text-indent",
      "text-underline-offset",
      "top",
      "translate",
      "transform-origin",
      "word-spacing"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "cx",
      "cy",
      "stroke-dashoffset",
      "x",
      "y"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "background-size",
      "block-size",
      "contain-intrinsic-block-size",
      "contain-intrinsic-inline-size",
      "flex-basis",
      "height",
      "inline-size",
      "max-block-size",
      "max-height",
      "max-inline-size",
      "max-width",
      "min-block-size",
      "min-height",
      "min-inline-size",
      "min-width",
      "mask-size",
      "width"
    ],
    "variableAliasRefs": [
      "~container"
    ]
  },
  {
    "properties": [
      "border-bottom-left-radius",
      "border-bottom-right-radius",
      "border-end-end-radius",
      "border-end-start-radius",
      "border-radius",
      "border-start-end-radius",
      "border-start-start-radius",
      "border-top-left-radius",
      "border-top-right-radius"
    ],
    "variableAliasRefs": [
      "~radius"
    ]
  },
  {
    "properties": [
      "border",
      "border-block",
      "border-block-color",
      "border-block-end",
      "border-block-end-color",
      "border-block-start",
      "border-block-start-color",
      "border-bottom",
      "border-bottom-color",
      "border-color",
      "border-inline",
      "border-inline-color",
      "border-inline-end",
      "border-inline-end-color",
      "border-inline-start",
      "border-inline-start-color",
      "border-left",
      "border-left-color",
      "border-right",
      "border-right-color",
      "border-top",
      "border-top-color",
      "outline",
      "outline-color"
    ],
    "variableAliasRefs": [
      "~color-line",
      "~color"
    ]
  },
  {
    "properties": [
      "accent-color",
      "background-color",
      "fill",
      "filter"
    ],
    "variableAliasRefs": [
      "~color"
    ]
  },
  {
    "properties": [
      "caret-color"
    ],
    "variableAliasRefs": [
      "~color-text",
      "~color"
    ]
  },
  {
    "properties": [
      "stroke"
    ],
    "variableAliasRefs": [
      "~color-line",
      "~color"
    ]
  },
  {
    "properties": [
      "color"
    ],
    "variableAliasRefs": [
      "=color",
      "~color-text",
      "~color"
    ]
  },
  {
    "properties": [
      "-webkit-text-fill-color",
      "text-decoration-color"
    ],
    "variableAliasRefs": [
      "~color-text",
      "~color"
    ]
  },
  {
    "properties": [
      "-webkit-text-stroke-color"
    ],
    "variableAliasRefs": [
      "~color"
    ]
  },
  {
    "properties": [
      "text-shadow"
    ],
    "variableAliasRefs": [
      "~color"
    ]
  },
  {
    "properties": [
      "box-shadow"
    ],
    "variableAliasRefs": [
      "~shadow",
      "~color"
    ]
  },
  {
    "properties": [
      "animation-delay",
      "animation-duration",
      "transition-delay",
      "transition-duration"
    ],
    "variableAliasRefs": [
      "~duration"
    ]
  },
  {
    "properties": [
      "animation-timing-function",
      "transition-timing-function"
    ],
    "variableAliasRefs": [
      "~easing"
    ]
  },
  {
    "properties": [
      "animation",
      "transition"
    ],
    "variableAliasRefs": [
      "~duration",
      "~easing"
    ]
  },
  {
    "properties": [
      "content"
    ],
    "variableAliasRefs": [
      "=content"
    ]
  },
  {
    "properties": [
      "font-feature-settings"
    ],
    "variableAliasRefs": [
      "=font-feature"
    ]
  },
  {
    "properties": [
      "font-family"
    ],
    "variableAliasRefs": [
      "=font-family"
    ]
  },
  {
    "properties": [
      "font-size"
    ],
    "variableAliasRefs": [
      "=font-size"
    ]
  },
  {
    "properties": [
      "font-weight"
    ],
    "variableAliasRefs": [
      "=font-weight"
    ]
  },
  {
    "properties": [
      "letter-spacing"
    ],
    "variableAliasRefs": [
      "~tracking"
    ]
  },
  {
    "properties": [
      "line-height"
    ],
    "variableAliasRefs": [
      "~leading"
    ]
  },
  {
    "properties": [
      "order"
    ],
    "variableAliasRefs": [
      "=order"
    ]
  }
].map((namespace) => Object.freeze({
    properties: Object.freeze(namespace.properties),
    variableAliasRefs: Object.freeze(namespace.variableAliasRefs)
  }))
) as MasterCSSBuiltinNativeValueNamespaces
