// Generated by `cargo xtask codegen`. Do not edit directly.

export interface MasterCSSBuiltinTokenNamespace {
  readonly properties: readonly string[]
  readonly variableAliasRefs: readonly string[]
}

export interface MasterCSSBuiltinTokenFamily {
  readonly prefix: string
  readonly property: string
  readonly namespaces: readonly string[]
}

export const builtinTokenFamilies: readonly MasterCSSBuiltinTokenFamily[] = Object.freeze(
  [
  {
    "prefix": "background-position",
    "property": "background-position",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "bottom",
    "property": "bottom",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "border-spacing",
    "property": "border-spacing",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "gap-x",
    "property": "column-gap",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "gap",
    "property": "gap",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "inset",
    "property": "inset",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "iy",
    "property": "inset-block",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "iye",
    "property": "inset-block-end",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "iys",
    "property": "inset-block-start",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "ix",
    "property": "inset-inline",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "ixe",
    "property": "inset-inline-end",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "ixs",
    "property": "inset-inline-start",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "left",
    "property": "left",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "m",
    "property": "margin",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "my",
    "property": "margin-block",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "mye",
    "property": "margin-block-end",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "mys",
    "property": "margin-block-start",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "mb",
    "property": "margin-bottom",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "mx",
    "property": "margin-inline",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "mxe",
    "property": "margin-inline-end",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "mxs",
    "property": "margin-inline-start",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "ml",
    "property": "margin-left",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "mr",
    "property": "margin-right",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "mt",
    "property": "margin-top",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "mask-position",
    "property": "mask-position",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "object-position",
    "property": "object-position",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "outline-offset",
    "property": "outline-offset",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "p",
    "property": "padding",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "py",
    "property": "padding-block",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "pye",
    "property": "padding-block-end",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "pys",
    "property": "padding-block-start",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "pb",
    "property": "padding-bottom",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "px",
    "property": "padding-inline",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "pxe",
    "property": "padding-inline-end",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "pxs",
    "property": "padding-inline-start",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "pl",
    "property": "padding-left",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "pr",
    "property": "padding-right",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "pt",
    "property": "padding-top",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "perspective",
    "property": "perspective",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "perspective-origin",
    "property": "perspective-origin",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "right",
    "property": "right",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "gap-y",
    "property": "row-gap",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "scroll-m",
    "property": "scroll-margin",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "scroll-my",
    "property": "scroll-margin-block",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "scroll-mye",
    "property": "scroll-margin-block-end",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "scroll-mys",
    "property": "scroll-margin-block-start",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "scroll-mb",
    "property": "scroll-margin-bottom",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "scroll-mx",
    "property": "scroll-margin-inline",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "scroll-mxe",
    "property": "scroll-margin-inline-end",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "scroll-mxs",
    "property": "scroll-margin-inline-start",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "scroll-ml",
    "property": "scroll-margin-left",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "scroll-mr",
    "property": "scroll-margin-right",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "scroll-mt",
    "property": "scroll-margin-top",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "scroll-p",
    "property": "scroll-padding",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "scroll-py",
    "property": "scroll-padding-block",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "scroll-pye",
    "property": "scroll-padding-block-end",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "scroll-pys",
    "property": "scroll-padding-block-start",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "scroll-pb",
    "property": "scroll-padding-bottom",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "scroll-px",
    "property": "scroll-padding-inline",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "scroll-pxe",
    "property": "scroll-padding-inline-end",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "scroll-pxs",
    "property": "scroll-padding-inline-start",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "scroll-pl",
    "property": "scroll-padding-left",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "scroll-pr",
    "property": "scroll-padding-right",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "scroll-pt",
    "property": "scroll-padding-top",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "shape-margin",
    "property": "shape-margin",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "text-indent",
    "property": "text-indent",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "text-underline",
    "property": "text-underline-offset",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "top",
    "property": "top",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "translate",
    "property": "translate",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "transform-origin",
    "property": "transform-origin",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "word-spacing",
    "property": "word-spacing",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "cx",
    "property": "cx",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "cy",
    "property": "cy",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "stroke-dashoffset",
    "property": "stroke-dashoffset",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "x",
    "property": "x",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "y",
    "property": "y",
    "namespaces": [
      "spacing"
    ]
  },
  {
    "prefix": "background-size",
    "property": "background-size",
    "namespaces": [
      "container"
    ]
  },
  {
    "prefix": "size-y",
    "property": "block-size",
    "namespaces": [
      "container"
    ]
  },
  {
    "prefix": "contain-intrinsic-block-size",
    "property": "contain-intrinsic-block-size",
    "namespaces": [
      "container"
    ]
  },
  {
    "prefix": "contain-intrinsic-inline-size",
    "property": "contain-intrinsic-inline-size",
    "namespaces": [
      "container"
    ]
  },
  {
    "prefix": "flex-basis",
    "property": "flex-basis",
    "namespaces": [
      "container"
    ]
  },
  {
    "prefix": "h",
    "property": "height",
    "namespaces": [
      "container"
    ]
  },
  {
    "prefix": "size-x",
    "property": "inline-size",
    "namespaces": [
      "container"
    ]
  },
  {
    "prefix": "max-size-y",
    "property": "max-block-size",
    "namespaces": [
      "container"
    ]
  },
  {
    "prefix": "max-h",
    "property": "max-height",
    "namespaces": [
      "container"
    ]
  },
  {
    "prefix": "max-size-x",
    "property": "max-inline-size",
    "namespaces": [
      "container"
    ]
  },
  {
    "prefix": "max-w",
    "property": "max-width",
    "namespaces": [
      "container"
    ]
  },
  {
    "prefix": "min-size-y",
    "property": "min-block-size",
    "namespaces": [
      "container"
    ]
  },
  {
    "prefix": "min-h",
    "property": "min-height",
    "namespaces": [
      "container"
    ]
  },
  {
    "prefix": "min-size-x",
    "property": "min-inline-size",
    "namespaces": [
      "container"
    ]
  },
  {
    "prefix": "min-w",
    "property": "min-width",
    "namespaces": [
      "container"
    ]
  },
  {
    "prefix": "mask-size",
    "property": "mask-size",
    "namespaces": [
      "container"
    ]
  },
  {
    "prefix": "w",
    "property": "width",
    "namespaces": [
      "container"
    ]
  },
  {
    "prefix": "rbl",
    "property": "border-bottom-left-radius",
    "namespaces": [
      "radius"
    ]
  },
  {
    "prefix": "rbr",
    "property": "border-bottom-right-radius",
    "namespaces": [
      "radius"
    ]
  },
  {
    "prefix": "border-end-end-radius",
    "property": "border-end-end-radius",
    "namespaces": [
      "radius"
    ]
  },
  {
    "prefix": "border-end-start-radius",
    "property": "border-end-start-radius",
    "namespaces": [
      "radius"
    ]
  },
  {
    "prefix": "r",
    "property": "border-radius",
    "namespaces": [
      "radius"
    ]
  },
  {
    "prefix": "border-start-end-radius",
    "property": "border-start-end-radius",
    "namespaces": [
      "radius"
    ]
  },
  {
    "prefix": "border-start-start-radius",
    "property": "border-start-start-radius",
    "namespaces": [
      "radius"
    ]
  },
  {
    "prefix": "rtl",
    "property": "border-top-left-radius",
    "namespaces": [
      "radius"
    ]
  },
  {
    "prefix": "rtr",
    "property": "border-top-right-radius",
    "namespaces": [
      "radius"
    ]
  },
  {
    "prefix": "by",
    "property": "border-block-color",
    "namespaces": [
      "color"
    ]
  },
  {
    "prefix": "border-block-end-color",
    "property": "border-block-end-color",
    "namespaces": [
      "color"
    ]
  },
  {
    "prefix": "border-block-start-color",
    "property": "border-block-start-color",
    "namespaces": [
      "color"
    ]
  },
  {
    "prefix": "bb",
    "property": "border-bottom-color",
    "namespaces": [
      "color"
    ]
  },
  {
    "prefix": "b",
    "property": "border-color",
    "namespaces": [
      "color"
    ]
  },
  {
    "prefix": "bx",
    "property": "border-inline-color",
    "namespaces": [
      "color"
    ]
  },
  {
    "prefix": "border-inline-end-color",
    "property": "border-inline-end-color",
    "namespaces": [
      "color"
    ]
  },
  {
    "prefix": "border-inline-start-color",
    "property": "border-inline-start-color",
    "namespaces": [
      "color"
    ]
  },
  {
    "prefix": "bl",
    "property": "border-left-color",
    "namespaces": [
      "color"
    ]
  },
  {
    "prefix": "br",
    "property": "border-right-color",
    "namespaces": [
      "color"
    ]
  },
  {
    "prefix": "bt",
    "property": "border-top-color",
    "namespaces": [
      "color"
    ]
  },
  {
    "prefix": "outline",
    "property": "outline-color",
    "namespaces": [
      "color"
    ]
  },
  {
    "prefix": "accent-color",
    "property": "accent-color",
    "namespaces": [
      "color"
    ]
  },
  {
    "prefix": "bg",
    "property": "background-color",
    "namespaces": [
      "color"
    ]
  },
  {
    "prefix": "fill",
    "property": "fill",
    "namespaces": [
      "color"
    ]
  },
  {
    "prefix": "caret-color",
    "property": "caret-color",
    "namespaces": [
      "color"
    ]
  },
  {
    "prefix": "stroke",
    "property": "stroke",
    "namespaces": [
      "color"
    ]
  },
  {
    "prefix": "fg",
    "property": "color",
    "namespaces": [
      "color"
    ]
  },
  {
    "prefix": "text-fill-color",
    "property": "-webkit-text-fill-color",
    "namespaces": [
      "color"
    ]
  },
  {
    "prefix": "text-decoration",
    "property": "text-decoration-color",
    "namespaces": [
      "color"
    ]
  },
  {
    "prefix": "text-stroke",
    "property": "-webkit-text-stroke-color",
    "namespaces": [
      "color"
    ]
  },
  {
    "prefix": "shadow",
    "property": "box-shadow",
    "namespaces": [
      "shadow"
    ]
  },
  {
    "prefix": "animate",
    "property": "animation",
    "namespaces": [
      "animate"
    ]
  },
  {
    "prefix": "animation-delay",
    "property": "animation-delay",
    "namespaces": [
      "duration"
    ]
  },
  {
    "prefix": "animation-duration",
    "property": "animation-duration",
    "namespaces": [
      "duration"
    ]
  },
  {
    "prefix": "transition-delay",
    "property": "transition-delay",
    "namespaces": [
      "duration"
    ]
  },
  {
    "prefix": "transition-duration",
    "property": "transition-duration",
    "namespaces": [
      "duration"
    ]
  },
  {
    "prefix": "animation-timing-function",
    "property": "animation-timing-function",
    "namespaces": [
      "easing"
    ]
  },
  {
    "prefix": "transition-timing-function",
    "property": "transition-timing-function",
    "namespaces": [
      "easing"
    ]
  },
  {
    "prefix": "content",
    "property": "content",
    "namespaces": [
      "content"
    ]
  },
  {
    "prefix": "font-feature-settings",
    "property": "font-feature-settings",
    "namespaces": [
      "font-feature"
    ]
  },
  {
    "prefix": "font-family",
    "property": "font-family",
    "namespaces": [
      "font-family"
    ]
  },
  {
    "prefix": "font-size",
    "property": "font-size",
    "namespaces": [
      "font-size"
    ]
  },
  {
    "prefix": "font-weight",
    "property": "font-weight",
    "namespaces": [
      "font-weight"
    ]
  },
  {
    "prefix": "tracking",
    "property": "letter-spacing",
    "namespaces": [
      "tracking"
    ]
  },
  {
    "prefix": "leading",
    "property": "line-height",
    "namespaces": [
      "leading"
    ]
  },
  {
    "prefix": "order",
    "property": "order",
    "namespaces": [
      "order"
    ]
  }
].map((family) => Object.freeze({ ...family, namespaces: Object.freeze(family.namespaces) }))
)

export type MasterCSSBuiltinTokenNamespaces = readonly MasterCSSBuiltinTokenNamespace[]


export const builtinTokenNamespaces = Object.freeze(
  [
  {
    "properties": [
      "background-position"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "bottom"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "border-spacing"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "column-gap"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "gap"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "inset"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "inset-block"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "inset-block-end"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "inset-block-start"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "inset-inline"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "inset-inline-end"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "inset-inline-start"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "left"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "margin"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "margin-block"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "margin-block-end"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "margin-block-start"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "margin-bottom"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "margin-inline"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "margin-inline-end"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "margin-inline-start"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "margin-left"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "margin-right"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "margin-top"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "mask-position"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "object-position"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "outline-offset"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "padding"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "padding-block"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "padding-block-end"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "padding-block-start"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "padding-bottom"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "padding-inline"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "padding-inline-end"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "padding-inline-start"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "padding-left"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "padding-right"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "padding-top"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "perspective"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "perspective-origin"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "right"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "row-gap"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "scroll-margin"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "scroll-margin-block"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "scroll-margin-block-end"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "scroll-margin-block-start"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "scroll-margin-bottom"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "scroll-margin-inline"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "scroll-margin-inline-end"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "scroll-margin-inline-start"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "scroll-margin-left"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "scroll-margin-right"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "scroll-margin-top"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "scroll-padding"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "scroll-padding-block"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "scroll-padding-block-end"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "scroll-padding-block-start"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "scroll-padding-bottom"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "scroll-padding-inline"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "scroll-padding-inline-end"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "scroll-padding-inline-start"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "scroll-padding-left"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "scroll-padding-right"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "scroll-padding-top"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "shape-margin"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "text-indent"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "text-underline-offset"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "top"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "translate"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "transform-origin"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "word-spacing"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "cx"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "cy"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "stroke-dashoffset"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "x"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "y"
    ],
    "variableAliasRefs": [
      "~spacing"
    ]
  },
  {
    "properties": [
      "background-size"
    ],
    "variableAliasRefs": [
      "~container"
    ]
  },
  {
    "properties": [
      "block-size"
    ],
    "variableAliasRefs": [
      "~container"
    ]
  },
  {
    "properties": [
      "contain-intrinsic-block-size"
    ],
    "variableAliasRefs": [
      "~container"
    ]
  },
  {
    "properties": [
      "contain-intrinsic-inline-size"
    ],
    "variableAliasRefs": [
      "~container"
    ]
  },
  {
    "properties": [
      "flex-basis"
    ],
    "variableAliasRefs": [
      "~container"
    ]
  },
  {
    "properties": [
      "height"
    ],
    "variableAliasRefs": [
      "~container"
    ]
  },
  {
    "properties": [
      "inline-size"
    ],
    "variableAliasRefs": [
      "~container"
    ]
  },
  {
    "properties": [
      "max-block-size"
    ],
    "variableAliasRefs": [
      "~container"
    ]
  },
  {
    "properties": [
      "max-height"
    ],
    "variableAliasRefs": [
      "~container"
    ]
  },
  {
    "properties": [
      "max-inline-size"
    ],
    "variableAliasRefs": [
      "~container"
    ]
  },
  {
    "properties": [
      "max-width"
    ],
    "variableAliasRefs": [
      "~container"
    ]
  },
  {
    "properties": [
      "min-block-size"
    ],
    "variableAliasRefs": [
      "~container"
    ]
  },
  {
    "properties": [
      "min-height"
    ],
    "variableAliasRefs": [
      "~container"
    ]
  },
  {
    "properties": [
      "min-inline-size"
    ],
    "variableAliasRefs": [
      "~container"
    ]
  },
  {
    "properties": [
      "min-width"
    ],
    "variableAliasRefs": [
      "~container"
    ]
  },
  {
    "properties": [
      "mask-size"
    ],
    "variableAliasRefs": [
      "~container"
    ]
  },
  {
    "properties": [
      "width"
    ],
    "variableAliasRefs": [
      "~container"
    ]
  },
  {
    "properties": [
      "border-bottom-left-radius"
    ],
    "variableAliasRefs": [
      "~radius"
    ]
  },
  {
    "properties": [
      "border-bottom-right-radius"
    ],
    "variableAliasRefs": [
      "~radius"
    ]
  },
  {
    "properties": [
      "border-end-end-radius"
    ],
    "variableAliasRefs": [
      "~radius"
    ]
  },
  {
    "properties": [
      "border-end-start-radius"
    ],
    "variableAliasRefs": [
      "~radius"
    ]
  },
  {
    "properties": [
      "border-radius"
    ],
    "variableAliasRefs": [
      "~radius"
    ]
  },
  {
    "properties": [
      "border-start-end-radius"
    ],
    "variableAliasRefs": [
      "~radius"
    ]
  },
  {
    "properties": [
      "border-start-start-radius"
    ],
    "variableAliasRefs": [
      "~radius"
    ]
  },
  {
    "properties": [
      "border-top-left-radius"
    ],
    "variableAliasRefs": [
      "~radius"
    ]
  },
  {
    "properties": [
      "border-top-right-radius"
    ],
    "variableAliasRefs": [
      "~radius"
    ]
  },
  {
    "properties": [
      "border-block-color"
    ],
    "variableAliasRefs": [
      "~color"
    ]
  },
  {
    "properties": [
      "border-block-end-color"
    ],
    "variableAliasRefs": [
      "~color"
    ]
  },
  {
    "properties": [
      "border-block-start-color"
    ],
    "variableAliasRefs": [
      "~color"
    ]
  },
  {
    "properties": [
      "border-bottom-color"
    ],
    "variableAliasRefs": [
      "~color"
    ]
  },
  {
    "properties": [
      "border-color"
    ],
    "variableAliasRefs": [
      "~color"
    ]
  },
  {
    "properties": [
      "border-inline-color"
    ],
    "variableAliasRefs": [
      "~color"
    ]
  },
  {
    "properties": [
      "border-inline-end-color"
    ],
    "variableAliasRefs": [
      "~color"
    ]
  },
  {
    "properties": [
      "border-inline-start-color"
    ],
    "variableAliasRefs": [
      "~color"
    ]
  },
  {
    "properties": [
      "border-left-color"
    ],
    "variableAliasRefs": [
      "~color"
    ]
  },
  {
    "properties": [
      "border-right-color"
    ],
    "variableAliasRefs": [
      "~color"
    ]
  },
  {
    "properties": [
      "border-top-color"
    ],
    "variableAliasRefs": [
      "~color"
    ]
  },
  {
    "properties": [
      "outline-color"
    ],
    "variableAliasRefs": [
      "~color"
    ]
  },
  {
    "properties": [
      "accent-color"
    ],
    "variableAliasRefs": [
      "~color"
    ]
  },
  {
    "properties": [
      "background-color"
    ],
    "variableAliasRefs": [
      "~color"
    ]
  },
  {
    "properties": [
      "fill"
    ],
    "variableAliasRefs": [
      "~color"
    ]
  },
  {
    "properties": [
      "caret-color"
    ],
    "variableAliasRefs": [
      "~color"
    ]
  },
  {
    "properties": [
      "stroke"
    ],
    "variableAliasRefs": [
      "~color"
    ]
  },
  {
    "properties": [
      "color"
    ],
    "variableAliasRefs": [
      "~color"
    ]
  },
  {
    "properties": [
      "-webkit-text-fill-color"
    ],
    "variableAliasRefs": [
      "~color"
    ]
  },
  {
    "properties": [
      "text-decoration-color"
    ],
    "variableAliasRefs": [
      "~color"
    ]
  },
  {
    "properties": [
      "-webkit-text-stroke-color"
    ],
    "variableAliasRefs": [
      "~color"
    ]
  },
  {
    "properties": [
      "box-shadow"
    ],
    "variableAliasRefs": [
      "~shadow"
    ]
  },
  {
    "properties": [
      "animation"
    ],
    "variableAliasRefs": [
      "~animate"
    ]
  },
  {
    "properties": [
      "animation-delay"
    ],
    "variableAliasRefs": [
      "~duration"
    ]
  },
  {
    "properties": [
      "animation-duration"
    ],
    "variableAliasRefs": [
      "~duration"
    ]
  },
  {
    "properties": [
      "transition-delay"
    ],
    "variableAliasRefs": [
      "~duration"
    ]
  },
  {
    "properties": [
      "transition-duration"
    ],
    "variableAliasRefs": [
      "~duration"
    ]
  },
  {
    "properties": [
      "animation-timing-function"
    ],
    "variableAliasRefs": [
      "~easing"
    ]
  },
  {
    "properties": [
      "transition-timing-function"
    ],
    "variableAliasRefs": [
      "~easing"
    ]
  },
  {
    "properties": [
      "content"
    ],
    "variableAliasRefs": [
      "~content"
    ]
  },
  {
    "properties": [
      "font-feature-settings"
    ],
    "variableAliasRefs": [
      "~font-feature"
    ]
  },
  {
    "properties": [
      "font-family"
    ],
    "variableAliasRefs": [
      "~font-family"
    ]
  },
  {
    "properties": [
      "font-size"
    ],
    "variableAliasRefs": [
      "~font-size"
    ]
  },
  {
    "properties": [
      "font-weight"
    ],
    "variableAliasRefs": [
      "~font-weight"
    ]
  },
  {
    "properties": [
      "letter-spacing"
    ],
    "variableAliasRefs": [
      "~tracking"
    ]
  },
  {
    "properties": [
      "line-height"
    ],
    "variableAliasRefs": [
      "~leading"
    ]
  },
  {
    "properties": [
      "order"
    ],
    "variableAliasRefs": [
      "~order"
    ]
  }
].map((namespace) => Object.freeze({
    properties: Object.freeze(namespace.properties),
    variableAliasRefs: Object.freeze(namespace.variableAliasRefs)
  }))
) as MasterCSSBuiltinTokenNamespaces
