const variableNamespaces = [
    'animation',
    'aspect-ratio',
    'breakpoint',
    'blur',
    'border-radius',
    'color',
    'color-line',
    'color-text',
    'container',
    'drop-shadow',
    'duration',
    'easing',
    'font-family',
    'font-size',
    'font-style',
    'font-variant',
    'font-weight',
    'letter-spacing',
    'line-height',
    'outline-color',
    'outline-offset',
    'outline-style',
    'outline-width',
    'perspective',
    'shadow',
    'shadow-inset',
    'spacing',
    'tab-size',
    'zoom',
] as const

export type VariableNamespace = typeof variableNamespaces[number]

export default variableNamespaces
