//! Retirement diagnostics only. These spellings never register token families.

/// Diagnostics only: these names never participate in declaration matching.
pub(crate) fn removed_raw_alias(property: &str) -> Option<&'static str> {
    if mastercss_schema::is_native_css_property(property) {
        return None;
    }
    match property {
        "gap-x" => Some("column-gap"),
        "iy" => Some("inset-block"),
        "iye" => Some("inset-block-end"),
        "iys" => Some("inset-block-start"),
        "ix" => Some("inset-inline"),
        "ixe" => Some("inset-inline-end"),
        "ixs" => Some("inset-inline-start"),
        "m" => Some("margin"),
        "my" => Some("margin-block"),
        "mye" => Some("margin-block-end"),
        "mys" => Some("margin-block-start"),
        "mb" => Some("margin-bottom"),
        "mx" => Some("margin-inline"),
        "mxe" => Some("margin-inline-end"),
        "mxs" => Some("margin-inline-start"),
        "ml" => Some("margin-left"),
        "mr" => Some("margin-right"),
        "mt" => Some("margin-top"),
        "p" => Some("padding"),
        "py" => Some("padding-block"),
        "pye" => Some("padding-block-end"),
        "pys" => Some("padding-block-start"),
        "pb" => Some("padding-bottom"),
        "px" => Some("padding-inline"),
        "pxe" => Some("padding-inline-end"),
        "pxs" => Some("padding-inline-start"),
        "pl" => Some("padding-left"),
        "pr" => Some("padding-right"),
        "pt" => Some("padding-top"),
        "gap-y" => Some("row-gap"),
        "scroll-m" => Some("scroll-margin"),
        "scroll-my" => Some("scroll-margin-block"),
        "scroll-mye" => Some("scroll-margin-block-end"),
        "scroll-mys" => Some("scroll-margin-block-start"),
        "scroll-mb" => Some("scroll-margin-bottom"),
        "scroll-mx" => Some("scroll-margin-inline"),
        "scroll-mxe" => Some("scroll-margin-inline-end"),
        "scroll-mxs" => Some("scroll-margin-inline-start"),
        "scroll-ml" => Some("scroll-margin-left"),
        "scroll-mr" => Some("scroll-margin-right"),
        "scroll-mt" => Some("scroll-margin-top"),
        "scroll-p" => Some("scroll-padding"),
        "scroll-py" => Some("scroll-padding-block"),
        "scroll-pye" => Some("scroll-padding-block-end"),
        "scroll-pys" => Some("scroll-padding-block-start"),
        "scroll-pb" => Some("scroll-padding-bottom"),
        "scroll-px" => Some("scroll-padding-inline"),
        "scroll-pxe" => Some("scroll-padding-inline-end"),
        "scroll-pxs" => Some("scroll-padding-inline-start"),
        "scroll-pl" => Some("scroll-padding-left"),
        "scroll-pr" => Some("scroll-padding-right"),
        "scroll-pt" => Some("scroll-padding-top"),
        "text-underline" => Some("text-underline-offset"),
        "size-y" => Some("block-size"),
        "h" => Some("height"),
        "size-x" => Some("inline-size"),
        "max-size-y" => Some("max-block-size"),
        "max-h" => Some("max-height"),
        "max-size-x" => Some("max-inline-size"),
        "max-w" => Some("max-width"),
        "min-size-y" => Some("min-block-size"),
        "min-h" => Some("min-height"),
        "min-size-x" => Some("min-inline-size"),
        "min-w" => Some("min-width"),
        "w" => Some("width"),
        "rbl" => Some("border-bottom-left-radius"),
        "rbr" => Some("border-bottom-right-radius"),
        "r" => Some("border-radius"),
        "rtl" => Some("border-top-left-radius"),
        "rtr" => Some("border-top-right-radius"),
        "by" => Some("border-block-color"),
        "bb" => Some("border-bottom-color"),
        "b" => Some("border-color"),
        "bx" => Some("border-inline-color"),
        "bl" => Some("border-left-color"),
        "br" => Some("border-right-color"),
        "bt" => Some("border-top-color"),
        "outline" => Some("outline-color"),
        "bg" => Some("background-color"),
        "fg" => Some("color"),
        "text-fill-color" => Some("-webkit-text-fill-color"),
        "text-decoration" => Some("text-decoration-color"),
        "text-stroke" => Some("-webkit-text-stroke-color"),
        "shadow" => Some("box-shadow"),
        "animate" => Some("animation"),
        "tracking" => Some("letter-spacing"),
        "leading" => Some("line-height"),
        "grid-col" => Some("grid-column"),
        "grid-col-start" => Some("grid-column-start"),
        "grid-col-end" => Some("grid-column-end"),
        "text-stroke-color" => Some("-webkit-text-stroke-color"),
        "text-stroke-width" => Some("-webkit-text-stroke-width"),
        "z" => Some("z-index"),
        _ => None,
    }
}

/// Retired preset parameter heads must not silently become unknown CSS properties.
pub(crate) fn removed_recipe(property: &str) -> Option<String> {
    match property {
        "grid-cols" | "grid-rows" | "grid-col-span" | "grid-row-span" | "clamp-lines" => Some(
            format!("{property}:value was removed; use {property}(value) with a positive integer"),
        ),
        "text" => {
            Some("text:value was removed; use font-size:value or a named text-token recipe".into())
        }
        _ => None,
    }
}
