import { validate } from '@master/css-validator'
import type { MasterCSS } from '@master/css-engine'
import { formatClassName, formatReason } from './diagnostic-format'

export interface ClassValidationOptions {
  disallowUnknownClass?: boolean
  displayClassName?: string
}

export type ClassValidationIssueKind = 'invalid' | 'unknown'

export interface ClassValidationIssue {
  kind: ClassValidationIssueKind
  className: string
  message: string
}

export default function getClassValidationIssues(
  className: string,
  css: MasterCSS,
  options: ClassValidationOptions = {}
): ClassValidationIssue[] {
  const { matched, errors } = validate(className, css)
  const issues: ClassValidationIssue[] = []
  const displayClassName = options.displayClassName || className
  for (const error of errors) {
    if (matched) {
      const reason = formatReason(error.message || error.rawMessage || 'CSS validation failed')
      issues.push({
        kind: 'invalid',
        className,
        message: `Class ${formatClassName(displayClassName)} emits invalid CSS: ${reason}`
      })
    } else if (options.disallowUnknownClass) {
      issues.push({
        kind: 'unknown',
        className,
        message: `Unknown Master CSS class ${formatClassName(displayClassName)}. It is not generated by the active manifest.`
      })
    }
  }
  return issues
}
