export const MASTER_CSS_RUNTIME_BOOTSTRAP_ID = 'virtual:master-css-runtime'
export const RESOLVED_MASTER_CSS_RUNTIME_BOOTSTRAP_ID = `\0${MASTER_CSS_RUNTIME_BOOTSTRAP_ID}`

export function createMasterCSSRuntimeBootstrapSource() {
  return [
    `import { MasterCSSRuntime } from '@master/css-runtime'`,
    `import masterCSSManifest from 'virtual:master-css-manifest'`,
    `import masterCSSEmittedGlobals from 'virtual:master-css-emitted-globals'`,
    ``,
    `let masterCSSRuntime`,
    `let startGeneration = 0`,
    ``,
    `function disposeRuntime() {`,
    `  startGeneration++`,
    `  masterCSSRuntime?.dispose()`,
    `  masterCSSRuntime = undefined`,
    `}`,
    ``,
    `async function startRuntime(manifest = masterCSSManifest, emittedGlobals = masterCSSEmittedGlobals) {`,
    `  if (typeof document === 'undefined') return`,
    `  disposeRuntime()`,
    `  const generation = startGeneration`,
    `  const nextRuntime = await MasterCSSRuntime.start({`,
    `    manifest,`,
    `    emittedGlobals,`,
    `    onDiagnostic: diagnostic => console.error(diagnostic)`,
    `  })`,
    `  if (generation !== startGeneration) {`,
    `    nextRuntime.dispose()`,
    `    return`,
    `  }`,
    `  masterCSSRuntime = nextRuntime.observe()`,
    `}`,
    ``,
    `if (typeof document !== 'undefined') {`,
    `  void startRuntime().catch(error => console.error(error, error?.cause))`,
    `}`,
    ``,
    `if (import.meta.hot) {`,
    `  import.meta.hot.accept(() => {})`,
    `  import.meta.hot.accept([`,
    `    'virtual:master-css-manifest',`,
    `    'virtual:master-css-emitted-globals'`,
    `  ], ([manifestModule, emittedGlobalsModule]) => {`,
    `    void startRuntime(`,
    `      manifestModule?.default ?? masterCSSManifest,`,
    `      emittedGlobalsModule?.default ?? masterCSSEmittedGlobals`,
    `    ).catch(error => console.error(error, error?.cause))`,
    `  })`,
    `  import.meta.hot.dispose(disposeRuntime)`,
    `}`,
    ``
  ].join('\n')
}
