export default function Head() {
    return (
        <>
            <title>Next.js v13 + Master CSS v2</title>
            <meta content="width=device-width, initial-scale=1" name="viewport" />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </>
    )
}
