import './globals.css'
import Client from './client'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" style={{ display: 'none' }}>
            <body>
                <Client>
                    {children}
                </Client>
            </body>
        </html>
    )
}
