export { getConfigFileColorRender, getDocumentColors, getColorValue, getColorPresentation } from './providers/color'
export { checkConfigColorsBlock, getLastInstance, getConfigColorsCompletionItem, getCompletionItem, getReturnItem } from './providers/completion'
export { doHover } from './providers/hover'
export { positionCheck } from './position-check'
export { settings } from './settings'