# https://moonrepo.dev/docs/config/global-project
$schema: 'https://moonrepo.dev/schemas/global-project.json'

# Extend and inherit an external configuration file. Must be a valid HTTPS URL or file system path.
# extends: './shared/project.yml'

# File groups are a mechanism for grouping similar types of files within a project
# using file glob patterns. These groups are then used by tasks to calculate functionality like
# cache computation, affected files since last change, command line arguments, deterministic
# builds, and more.
#
# This setting requires a map, where the key is the file group name, and the value is a list of
# globs. Globs are relative to a project, even though they are defined globally. This enables
# enforcement of organizational patterns across all projects in the workspace.
fileGroups:
    # List of configuration files located within the project root.
    configs:
        - '*.{js,json}'

    # List of non-test source files.
    sources:
        - 'src/**/*'
        - 'types/**/*'

    # List of non-source test files.
    tests:
        - 'tests/**/*.test.*'
        - '**/__tests__/**/*'

    # All static assets within the project.
    # This may include styles, images, videos, etc.
    assets:
        - 'assets/**/*'
        - 'images/**/*'
        - 'static/**/*'
        - '**/*.{scss,css}'
        - '**/*.mdx'
