import assert from 'node:assert/strict'
import { DEFAULT_BASELINE_REF, RC87_COMMIT, RC87_MIGRATION_TARGET_COMMIT } from './config.mjs'

export function buildReport(ledger, rustRefactorContractLedger, postRc87Delta) {
  const gaps = ledger.entries.filter((entry) => entry.migration.status === 'gap')
  const p0Gaps = gaps.filter((entry) => entry.priority === 'P0')
  const active = ledger.entries.filter((entry) => entry.source.state === 'active' || entry.source.state === 'only')
  const complete = active.filter((entry) => ['verified-exact', 'approved-divergence'].includes(entry.migration.status))
  const unresolvedMatrices = ledger.entries.filter((entry) => entry.source.matrix?.resolved === false)
  const divergenceApprovals = [...new Map(
    ledger.entries
      .filter((entry) => entry.migration.status === 'approved-divergence')
      .map((entry) => [entry.divergence.id, entry.divergence])
  ).values()].sort((left, right) => left.id.localeCompare(right.id))
  const packageRows = Object.entries(ledger.summary.byPackage)
    .map(([packageName, counts]) => `| \`${packageName}\` | ${counts.total} | ${counts.P0 ?? 0} | ${counts.P1 ?? 0} | ${counts.P2 ?? 0} | ${counts.mapped ?? 0} | ${counts.gap ?? 0} |`)
    .join('\n')
  const p0GapRows = p0Gaps.slice(0, 80)
    .map((entry) => `| \`${entry.source.file}:${entry.source.line}\` | ${entry.source.title.replace(/\|/gu, '\\|')} | ${entry.domains.join(', ')} |`)
    .join('\n') || '| — | None | — |'
  const overlayRows = postRc87Delta.files
    .map((entry) => `| ${entry.priority} | \`${entry.file}\` | ${entry.decision} | ${entry.behavior} |`)
    .join('\n') || '| — | None | — | — |'
  const divergenceApprovalRows = divergenceApprovals
    .map((exception) => {
      const caseBindings = exception.approval.cases.map(({ sourceId, sourceDigest, targets }) => {
        const targetBindings = targets
          .map(({ caseId, runner, digest }) => `\`${caseId}\` (${runner}) @ \`${digest}\``)
          .join('<br>')
        return `\`${sourceId}\` @ \`${sourceDigest}\`<br>→ ${targetBindings}`
      }).join('<br>')
      return `| \`${exception.id}\` | ${caseBindings} | \`${exception.approval.approvedBy}\` | \`${exception.approval.approvedAt}\` | \`${exception.approval.reviewRef}\` | \`${exception.approval.scopeDigest}\` |`
    })
    .join('\n')
  const contractSurfaceRows = rustRefactorContractLedger.surfaces
    .map((surface) => `| \`${surface.id}\` | \`${surface.digest}\`<br>→ \`${surface.targetDigest}\` | ${surface.status} | ${surface.proof} | ${surface.approval ? `\`${surface.approval.approvedBy}\`<br>\`${surface.approval.approvedAt}\`<br>\`${surface.approval.reviewRef}\`<br>\`${surface.approval.scopeDigest}\`` : '—'} |`)
    .join('\n')
  const overlayDecisionRows = postRc87Delta.decisions
    .map((decision) => `| \`${decision.id}\` | ${decision.status} | \`${decision.owner}\` | \`${decision.target.implementedAtCommit}\` | \`${decision.upstream.digest}\`<br>→ \`${decision.target.digest}\` | ${decision.target.tests.length} | \`${decision.approval.approvedBy}\`<br>\`${decision.approval.approvedAt}\`<br>\`${decision.approval.reviewRef}\`<br>\`${decision.approval.scopeDigest}\` |`)
    .join('\n')

  return `# Rust test migration from v2.0.0-rc.87

This report is generated by \`node scripts/build-ts-test-migration-ledger.mjs\`.
The rc.87 source of truth is \`parity/ts-test-migration-ledger.json\`; newer behavior
is isolated in \`parity/post-rc87-delta-ledger.json\`.

## Frozen baseline

- Public and semantic source baseline: \`${ledger.baseline.ref}@${ledger.baseline.commit}\`.
- Rust target candidate: \`${ledger.target.ref}@${ledger.target.commit}\`.
- Scope: executable tests and E2E cases under \`packages/*\`; examples, site, and benchmarks are not migration denominators.
- Newer rc changes are an overlay only and never replace rc.87 expectations.

## Inventory

| Measure | Count |
|---|---:|
| rc.87 workspace packages | ${ledger.baseline.packageCount} |
| rc.87 executable test files | ${ledger.baseline.testFiles} |
| rc.87 executable E2E files | ${ledger.baseline.e2eFiles} |
| rc.87 expanded cases | ${ledger.baseline.cases} |
| Expanded parameter and RuleTester cases | ${ledger.baseline.expandedMatrixCases} |
| Unresolved runtime matrices | ${ledger.baseline.dynamicMatrixCases} |
| Rust target cases collected | ${ledger.target.cases} |
| Target-only cases | ${ledger.summary.targetOnlyCases} |

The old 114-test takeover ledger is an engine-only historical subset. Its semantic
capture commit \`${ledger.existingParity.semanticBaseline}\` is not substituted for rc.87.

## Migration status

| Status | Count |
|---|---:|
${Object.entries(ledger.summary.byStatus).map(([status, count]) => `| ${status} | ${count} |`).join('\n')}

| Candidate coverage | Count |
|---|---:|
${Object.entries(ledger.summary.byCoverage).map(([coverage, count]) => `| ${coverage} | ${count} |`).join('\n')}

| Verification proof | Count |
|---|---:|
${Object.entries(ledger.summary.byProof).map(([proof, count]) => `| ${proof} | ${count} |`).join('\n') || '| — | 0 |'}

| Priority | Cases | Gaps |
|---|---:|---:|
${['P0', 'P1', 'P2', 'P3'].map((priority) => `| ${priority} | ${ledger.summary.byPriority[priority] ?? 0} | ${ledger.entries.filter((entry) => entry.priority === priority && entry.migration.status === 'gap').length} |`).join('\n')}
Verified active cases: ${complete.length}/${active.length}.

\`mapped-unverified\` means that an executable target candidate or takeover reference
exists. It does not claim parity. \`exact-source\` requires one identical executable
target; \`rc87-golden\` requires an explicit evidence record with pinned target digests.
Ambiguous candidates remain incomplete until evidence selects a target explicitly.

## Package ledger

| Legacy package | Cases | P0 | P1 | P2 | Mapped/inactive | Gaps |
|---|---:|---:|---:|---:|---:|---:|
${packageRows}

## P0 behavior gates

- Exact CSS bytes: selector escaping, declaration and cascade ordering, fixed layer order, variables, resources, and keyframes outside layers.
- Syntax: parser boundaries, values, functions, groups, priority, modes, selectors, conditions, invalid and retired syntax.
- Authoring: \`@theme\`, \`@custom-variant\`, \`@variant\`, \`@compose\`, \`@reference\`, project and stylesheet lowering.
- Runtime/server: hydration, DOM and CSSOM lifecycle, class deletion, retained resources, HTML injection and escaping.
- Rendering Modes: runtime, static, progressive, and pre-render across Vite, Webpack, Next, Astro, Nuxt, and Svelte.
- Binding parity: native and Wasm engine/compiler/tooling must execute identical Rust semantics.

## P0 gaps

The full list is in the JSON ledger; the first ${Math.min(80, p0Gaps.length)} are shown here.

| Source | rc.87 case | Domains |
|---|---|---|
${p0GapRows}

## Dynamic matrices requiring runtime collection

${unresolvedMatrices.length
    ? unresolvedMatrices.map((entry) => `- \`${entry.source.file}:${entry.source.line}\` — ${entry.source.title}`).join('\n')
    : 'All statically discoverable parameter matrices were expanded.'}

## Human approval traceability

Every approved divergence is bound to its exact exception text, rc.87 source ids and
digests, target case ids, runners, and target digests. Any scope change invalidates the
recorded scope digest and fails ledger generation.

| Exception | rc.87 cases | Approved by | Approved at | Review reference | Scope digest |
|---|---|---|---|---|---|
${divergenceApprovalRows}

## Rust refactor contract audit

The completed Rust refactor at
\`${rustRefactorContractLedger.baseline.ref}@${rustRefactorContractLedger.baseline.commit}\`
is an independent non-regression authority. An rc.87 expectation cannot restore an
older API, export, binding ABI, language wire shape, or rendering-mode option contract.

| Measure | Count |
|---|---:|
| Baseline contract cases | ${rustRefactorContractLedger.baseline.cases} |
| Preserved exact cases | ${rustRefactorContractLedger.summary.byStatus['preserved-exact'] ?? 0} |
| Verified supersets | ${rustRefactorContractLedger.summary.byStatus['verified-superset'] ?? 0} |
| Approved contract changes | ${rustRefactorContractLedger.summary.byStatus['approved-contract-change'] ?? 0} |
| Regressed or removed cases | ${(rustRefactorContractLedger.summary.byStatus.regressed ?? 0) + (rustRefactorContractLedger.summary.byStatus['removed-unapproved'] ?? 0)} |
| Target-added supplemental cases | ${rustRefactorContractLedger.summary.addedCases} |

| Contract surface | Baseline → target digest | Status | Proof | Human approval |
|---|---|---|---|---|
${contractSurfaceRows}

The rendering-mode surface preserves the current distinction between disabling an
integration with \`enabled: false\` and retaining host loaders without runtime injection
using \`mode: 'runtime', runtime: false\`. Retired null-mode behavior is not restored.

## Post-rc.87 overlay

These entries do not affect rc.87 parity completion or belong in \`parity-exceptions.json\`.
The browser manifest adaptation has its own approved decision source, implementation
commit, upstream and target scope digests, target test bindings, and human approval.
The target audit follows the latest package commit at
\`${postRc87Delta.targetAudit.ref}@${postRc87Delta.targetAudit.commit}\`.

| Decision | Status | Owner | Implementation commit | Upstream → target digest | Tests | Human approval |
|---|---|---|---|---|---:|---|
${overlayDecisionRows}

| Priority | File | Decision | Behavior |
|---|---|---|---|
${overlayRows}

## Completion rule

The migration is complete only when every active rc.87 entry is \`verified-exact\` or
references an explicitly approved parity exception. P0 may not use representative-only
coverage. Source-inactive tests remain visible but do not count as executable proof.
`
}

export function buildPackageSummary(entries) {
  const packages = {}
  for (const entry of entries) {
    const summary = packages[entry.source.package] ??= {
      total: 0,
      P0: 0,
      P1: 0,
      P2: 0,
      mapped: 0,
      gap: 0
    }
    summary.total++
    summary[entry.priority]++
    if (entry.migration.status === 'gap') summary.gap++
    else summary.mapped++
  }
  return Object.fromEntries(Object.entries(packages).sort(([left], [right]) => left.localeCompare(right)))
}

export function validateLedger(ledger) {
  assert.equal(ledger.baseline.ref, DEFAULT_BASELINE_REF, 'The ledger must remain rooted at v2.0.0-rc.87.')
  assert.equal(ledger.baseline.commit, RC87_COMMIT, 'The rc.87 tag moved unexpectedly.')
  assert.equal(ledger.target.commit, RC87_MIGRATION_TARGET_COMMIT, 'The completed rc.87 migration target moved unexpectedly.')
  assert.equal(new Set(ledger.entries.map((entry) => entry.id)).size, ledger.entries.length, 'Legacy entry ids must be unique.')
  assert.equal(ledger.entries.length, ledger.baseline.cases, 'Legacy case count does not match the ledger entries.')
  assert.ok(ledger.baseline.testFiles >= 180, 'The collector lost rc.87 test files.')
  assert.ok(ledger.baseline.e2eFiles >= 20, 'The collector lost rc.87 E2E files.')
  for (const entry of ledger.entries) {
    assert.ok(['P0', 'P1', 'P2', 'P3'].includes(entry.priority), `Invalid priority for ${entry.id}.`)
    assert.ok(entry.domains.length, `Missing behavior domain for ${entry.id}.`)
    assert.ok(entry.source.file.startsWith('packages/'), `Out-of-scope source file for ${entry.id}.`)
    assert.ok(['mapped-unverified', 'gap', 'source-inactive', 'verified-exact', 'approved-divergence'].includes(entry.migration.status), `Invalid status for ${entry.id}.`)
    if (entry.migration.status === 'verified-exact') {
      assert.ok(entry.migration.proof, `Verified entry ${entry.id} is missing proof.`)
      assert.ok(['exact-source', 'rc87-golden'].includes(entry.migration.proof.kind), `Invalid exact proof for ${entry.id}.`)
      assert.equal(entry.divergence, null, `Verified entry ${entry.id} cannot carry a divergence.`)
    } else if (entry.migration.status === 'approved-divergence') {
      assert.equal(entry.migration.proof?.kind, 'approved-divergence', `Divergence entry ${entry.id} is missing proof.`)
      assert.ok(entry.divergence, `Divergence entry ${entry.id} is missing exception data.`)
      assert.ok(entry.divergence.approval, `Divergence entry ${entry.id} is missing human approval.`)
      assert.ok(
        entry.divergence.approval.cases.some(({ sourceId }) => sourceId === entry.id),
        `Divergence entry ${entry.id} is outside its approved case scope.`
      )
    } else {
      assert.equal(entry.migration.proof, null, `Incomplete entry ${entry.id} cannot carry proof.`)
      assert.equal(entry.divergence, null, `Incomplete entry ${entry.id} cannot carry a divergence.`)
    }
  }
  const active = ledger.entries.filter((entry) => entry.source.state === 'active')
  const inactive = ledger.entries.filter((entry) => entry.source.state !== 'active')
  assert.equal(active.length, 1536, 'The rc.87 active-case denominator drifted.')
  assert.equal(inactive.length, 10, 'The rc.87 inactive-case denominator drifted.')
  assert.ok(
    active.every((entry) => ['verified-exact', 'approved-divergence'].includes(entry.migration.status)),
    'Every active rc.87 case must have exact or approved-divergence proof.'
  )
  assert.ok(
    inactive.every((entry) => entry.migration.status === 'source-inactive'),
    'Inactive rc.87 cases must remain source-inactive.'
  )
  assert.equal(ledger.summary.targetOnlyCases, 158, 'The completed rc.87 target-only inventory drifted.')
}
