import assert from 'node:assert/strict'
import test from 'node:test'
import { evaluateSourceBudgets } from './check-ai-context.mjs'

const policy = {
  limits: {
    source: { maxLines: 3, maxBytes: 40 },
    support: { maxLines: 5, maxBytes: 60 },
    context: { maxLines: 4, maxBytes: 50 }
  },
  exceptions: []
}

test('applies source, support, and context budgets', () => {
  const result = evaluateSourceBudgets([
    { path: 'src/core.ts', content: 'a\nb\nc\nd\n' },
    { path: 'tests/core.test.ts', content: 'a\nb\nc\nd\n' },
    { path: '.ai/context/index.md', content: 'a\nb\nc\nd\ne\n' }
  ], policy)
  assert.deepEqual(result.violations, [
    'src/core.ts: source budget exceeded (4/3 lines, 8/40 bytes).',
    '.ai/context/index.md: context budget exceeded (5/4 lines, 10/50 bytes).'
  ])
})

test('excludes generated sources with an explicit marker', () => {
  const result = evaluateSourceBudgets([{
    path: 'src/generated.ts',
    content: '// Generated by `cargo xtask codegen`. Do not edit directly.\na\nb\nc\nd\n'
  }], policy)
  assert.equal(result.generated, 1)
  assert.deepEqual(result.violations, [])
})

test('enforces bounded exceptions and rejects stale exceptions', () => {
  const exceptionPolicy = {
    ...policy,
    exceptions: [{
      path: 'src/data.ts',
      category: 'static-data',
      maxLines: 6,
      maxBytes: 80,
      reason: 'Static fixture data remains in one file.'
    }]
  }
  assert.deepEqual(evaluateSourceBudgets([
    { path: 'src/data.ts', content: 'a\nb\nc\nd\n' }
  ], exceptionPolicy).violations, [])
  assert.deepEqual(evaluateSourceBudgets([
    { path: 'src/data.ts', content: 'a\n' }
  ], exceptionPolicy).violations, [
    'src/data.ts: budget exception is stale; the file now fits the source budget.'
  ])
  assert.deepEqual(evaluateSourceBudgets([
    { path: 'src/data.ts', content: 'a\nb\nc\nd\ne\nf\ng\n' }
  ], exceptionPolicy).violations, [
    'src/data.ts: exception ceiling exceeded (7/6 lines, 14/80 bytes).'
  ])
})
