/** Reviewed page / stable section inventory, including examples expanded from MDX includes. */
export const referenceDemoCoverage: Record<string, readonly string[]> = {
  "accent-color": ["set-the-accent-color", "apply-conditionally"],
  "align-content": ["align-multiple-rows-or-tracks", "center-wrapped-lines", "apply-conditionally"],
  "align-items": ["align-items-on-the-cross-axis", "align-to-the-start-or-end", "stretch-children", "align-text-baselines", "apply-conditionally"],
  "align-self": ["override-cross-axis-alignment-for-one-item", "stretch-a-single-item", "apply-conditionally"],
  "animation": ["ping-indicator", "rotate-indicator", "loading-spinner", "apply-conditionally", "add-your-animations"],
  "animation-delay": ["delay-animation-start", "offset-looping-animations", "stagger-a-list", "use-duration-tokens", "apply-conditionally"],
  "animation-direction": ["play-forward", "play-backward", "play-alternately", "play-alternately-and-reverse-first", "fade-out", "apply-conditionally"],
  "animation-duration": ["set-animation-speed", "slow-down-looping-motion", "remove-animation-in-static-output", "apply-conditionally"],
  "animation-fill-mode": ["keep-the-final-keyframe", "apply-both-before-and-after-states", "reset-fill-behavior", "apply-conditionally"],
  "animation-iteration-count": ["loop-animation", "specify-n-iterations", "pair-with-fill-mode", "apply-conditionally"],
  "animation-name": ["choose-the-keyframes-to-run", "disable-an-animation", "combine-with-timing-longhands", "apply-conditionally"],
  "animation-play-state": ["run-an-animation", "pause-animation", "pause-nonessential-motion", "apply-conditionally"],
  "animation-timing-function": ["set-keyframe-easing", "use-linear-timing-for-rotation", "match-easing-to-intent", "apply-conditionally"],
  "appearance": ["remove-default-styling", "restore-native-appearance", "keep-semantics-intact", "apply-conditionally"],
  "aspect-ratio": ["set-a-custom-ratio", "use-square-and-video-shortcuts", "pair-with-one-explicit-axis", "use-the-video-shortcut", "choose-size-for-fixed-squares", "apply-conditionally"],
  "backdrop-filter": ["blur-content-behind-an-element", "combine-with-translucent-backgrounds", "reset-backdrop-filters", "apply-conditionally"],
  "background": ["use-the-background-shorthand", "prefer-focused-utilities-for-simple-changes", "apply-conditionally"],
  "background-attachment": ["scroll-with-the-element", "fix-a-background-to-the-viewport", "attach-to-scrollable-content", "apply-conditionally"],
  "background-blend-mode": ["blend-background-layers", "restore-normal-blending", "apply-conditionally"],
  "background-clip": ["clip-a-background-to-a-box", "clip-a-background-to-text", "apply-conditionally"],
  "background-color": ["with-opacity", "apply-conditionally"],
  "background-image": ["add-a-background-image", "use-gradients", "apply-conditionally"],
  "background-origin": ["choose-the-background-positioning-area", "align-art-with-borders-or-content", "apply-conditionally"],
  "background-position": ["position-a-background-image", "use-explicit-positions", "apply-conditionally"],
  "background-repeat": ["disable-tiling", "repeat-on-one-axis", "apply-conditionally"],
  "background-size": ["cover-a-frame", "contain-an-image", "use-measured-sizes", "apply-conditionally"],
  "border": ["set-width-style-and-color-together", "set-one-side-or-one-axis", "use-focused-border-utilities", "apply-conditionally"],
  "border-collapse": ["collapse-table-borders", "separate-table-borders", "match-border-spacing-to-the-mode", "apply-conditionally"],
  "border-color": ["set-border-color", "use-side-specific-color-utilities", "follow-the-current-text-color", "apply-conditionally", "customize-line-colors"],
  "border-image": ["draw-a-gradient-border-image", "include-width-and-repeat", "apply-conditionally"],
  "border-image-outset": ["extend-the-border-image-outside-the-box", "use-separate-vertical-and-horizontal-values", "apply-conditionally"],
  "border-image-repeat": ["round-repeated-edge-slices", "set-vertical-and-horizontal-behavior", "apply-conditionally"],
  "border-image-slice": ["slice-the-source-image", "preserve-the-center-with-fill", "apply-conditionally"],
  "border-image-source": ["set-a-gradient-source", "use-no-source", "apply-conditionally"],
  "border-image-width": ["set-the-border-image-width", "use-automatic-width", "apply-conditionally"],
  "border-radius": ["basic-usage", "create-a-pill-button", "create-an-icon-button", "use-a-radius-token", "round-individual-corners", "apply-conditionally", "use-custom-border-radius"],
  "border-style": ["set-border-style", "use-dashed-or-dotted-borders", "remove-border-style", "apply-conditionally"],
  "border-width": ["set-border-width", "set-one-side-or-axis", "apply-conditionally"],
  "box-decoration-break": ["slice", "clone", "use-on-inline-content", "apply-conditionally"],
  "box-shadow": ["use-shadow-tokens", "use-raw-values", "use-inset-shadows", "apply-conditionally", "customize-mode-specific-tokens"],
  "box-sizing": ["include-border-and-padding-in-size", "size-the-content-box-only", "prefer-consistency-inside-components", "apply-conditionally"],
  "break-after": ["set-the-break-after-behavior", "apply-conditionally"],
  "break-before": ["set-the-break-before-behavior", "apply-conditionally"],
  "break-inside": ["set-the-break-inside-behavior", "apply-conditionally"],
  "caret-color": ["set-the-text-caret-color", "use-the-current-text-color", "hide-the-caret-intentionally", "apply-conditionally"],
  "clear": ["clearing-both-left-and-right-floats", "clearing-left-floats", "clearing-right-floats", "apply-conditionally"],
  "clip-path": ["clip-to-a-circle", "clip-with-an-inset", "remove-clipping", "apply-conditionally"],
  "color": ["with-opacity", "apply-conditionally", "use-custom-text-colors"],
  "column-span": ["span-across-all-columns", "does-not-span-multiple-columns", "use-inside-multi-column-layouts", "apply-conditionally"],
  "columns": ["set-column-count", "flexible-multi-column-layout", "apply-conditionally"],
  "contain": ["contain-layout-and-paint", "contain-painting", "reset-containment", "apply-conditionally"],
  "content": ["add-indicators-for-external-links", "resolve-whitespaces-in-the-value", "apply-conditionally"],
  "counter-increment": ["number-sections", "count-backward", "apply-conditionally"],
  "counter-reset": ["create-a-section-counter", "start-from-another-number", "create-a-reversed-counter", "apply-conditionally"],
  "counter-set": ["set-a-counter-on-one-item", "set-multiple-counters", "apply-conditionally"],
  "cursor": ["show-clickable-affordance", "mark-disabled-actions", "support-drag-handles", "apply-conditionally"],
  "direction": ["set-left-to-right-direction", "set-right-to-left-direction", "prefer-semantic-document-direction", "apply-conditionally"],
  "display": ["block--inline", "flex", "inline-flex", "grid", "inline-grid", "table", "contents", "flow-root", "list-item", "hidden", "apply-conditionally"],
  "fill": ["set-svg-fill-color", "use-theme-colors", "apply-conditionally"],
  "filter": ["apply-filter-functions", "use-drop-shadow-for-transparent-images", "reset-filters", "apply-conditionally"],
  "flex": ["let-an-item-fill-remaining-space", "prevent-an-item-from-flexing", "set-grow-shrink-and-basis-together", "remember-the-parent-display", "apply-conditionally"],
  "flex-basis": ["set-the-starting-size-of-a-flex-item", "use-content-or-parent-sized-basis-values", "use-container-basis-values", "prefer-shorthand-for-complete-flex-behavior", "apply-conditionally"],
  "flex-direction": ["lay-out-items-in-a-row", "stack-items-in-a-column", "reverse-visual-order", "apply-conditionally"],
  "flex-grow": ["let-an-item-grow", "keep-an-item-at-its-basis", "apply-conditionally"],
  "flex-shrink": ["allow-an-item-to-shrink", "prevent-fixed-media-from-shrinking", "apply-conditionally"],
  "flex-wrap": ["allow-items-to-wrap", "keep-items-on-one-line", "reverse-wrap-direction", "apply-conditionally"],
  "float": ["float-elements-to-the-left", "float-elements-to-the-right", "reset-floats", "apply-conditionally"],
  "font-family": ["basic-usage", "set-the-font-family", "apply-fonts-globally", "apply-conditionally", "apply-fonts-to-specified-elements", "resolve-whitespaces-in-the-value", "use-custom-fonts", "google-fonts", "self-hosted-fonts"],
  "font-feature-settings": ["enable-a-font-feature", "reset-features", "prefer-semantic-numeric-utilities", "use-feature-tokens", "apply-conditionally"],
  "font-size": ["basic-usage", "with-line-height", "use-an-explicit-font-size", "apply-conditionally"],
  "font-smooth": ["use-antialiased-text", "restore-subpixel-antialiasing", "use-sparingly", "apply-conditionally"],
  "font-style": ["italicize-emphasis", "use-oblique-text", "reset-font-style", "apply-conditionally"],
  "font-variant-numeric": ["align-tabular-numbers", "show-slashed-zeroes", "reset-numeric-variants", "apply-conditionally"],
  "font-weight": ["basic-usage", "use-explicit-weights", "apply-conditionally"],
  "gap": ["add-the-same-gap-on-both-axes", "set-row-and-column-gaps-separately", "use-gap-for-component-internals", "apply-conditionally"],
  "grid": ["set-the-native-grid-shorthand", "define-rows-columns-and-auto-flow-together", "apply-conditionally"],
  "grid-area": ["place-an-item-by-grid-lines", "span-tracks", "use-a-named-area", "apply-conditionally"],
  "grid-auto-columns": ["size-implicit-columns", "apply-conditionally"],
  "grid-auto-flow": ["fill-by-column", "fill-gaps-densely", "apply-conditionally"],
  "grid-auto-rows": ["size-implicit-rows", "apply-conditionally"],
  "grid-column": ["place-an-item-by-columns", "span-columns", "apply-conditionally"],
  "grid-columns": ["create-equal-columns", "apply-conditionally"],
  "grid-row": ["place-an-item-by-rows", "span-rows", "apply-conditionally"],
  "grid-rows": ["create-equal-rows", "apply-conditionally"],
  "grid-template": ["define-rows-and-columns-together", "apply-conditionally"],
  "grid-template-areas": ["name-areas-in-a-grid", "apply-conditionally"],
  "grid-template-columns": ["define-explicit-columns", "use-minmax", "apply-conditionally"],
  "grid-template-rows": ["define-explicit-rows", "use-minmax", "apply-conditionally"],
  "height": ["set-a-fixed-height", "fill-a-parent-height", "use-viewport-and-intrinsic-values", "size-both-axes-together", "apply-conditionally"],
  "hyphens": ["allow-automatic-hyphenation", "respect-manual-hyphenation-points", "disable-hyphenation", "apply-conditionally"],
  "inset": ["pin-all-sides", "pin-one-side", "center-overlays-with-inset", "apply-conditionally"],
  "isolation": ["create-a-stacking-context", "return-to-automatic-isolation", "protect-layered-components", "apply-conditionally"],
  "justify-content": ["align-items-on-the-main-axis", "start-center-or-end-a-group", "distribute-extra-space", "use-explicit-css-values", "apply-conditionally"],
  "justify-items": ["align-grid-items-inline", "stretch-items-by-default", "apply-conditionally"],
  "justify-self": ["align-one-grid-item-inline", "center-an-item-inside-its-area", "apply-conditionally"],
  "letter-spacing": ["basic-usage", "use-a-custom-value", "apply-conditionally"],
  "line-clamp": ["clamp-long-summaries", "remove-a-clamp", "keep-important-content-accessible", "apply-conditionally"],
  "line-height": ["basic-usage", "set-line-height-with-font-size", "tighten-display-text", "use-explicit-values", "apply-conditionally"],
  "list-style": ["set-type-and-position-together", "use-an-image-marker", "split-longhands-when-variants-differ", "apply-conditionally"],
  "list-style-image": ["use-an-image-marker", "use-a-gradient-marker", "fall-back-to-type-markers", "apply-conditionally"],
  "list-style-position": ["place-markers-inside-the-content-box", "keep-markers-outside", "combine-with-marker-type", "apply-conditionally"],
  "list-style-type": ["use-decimal-markers", "use-disc-markers", "use-a-native-list-style-type", "apply-conditionally"],
  "margin": ["add-margin-on-every-side", "set-one-side", "set-horizontal-or-vertical-margins", "avoid-margin-for-internal-spacing", "apply-conditionally"],
  "mask-image": ["apply-a-mask-image", "fade-overflowing-media", "apply-conditionally"],
  "max-height": ["cap-a-vertical-region", "keep-media-inside-a-frame", "use-viewport-caps", "apply-conditionally"],
  "max-size": ["cap-width-and-height-together", "keep-square-media-bounded", "cap-one-logical-axis", "use-one-axis-caps-for-layout", "apply-conditionally"],
  "max-width": ["cap-a-fluid-element", "set-a-readable-measure", "keep-media-responsive", "use-viewport-and-container-caps", "apply-conditionally"],
  "min-height": ["set-a-baseline-height", "build-viewport-sections", "let-content-define-the-final-size", "apply-conditionally"],
  "min-size": ["set-minimum-width-and-height-together", "preserve-touch-targets", "set-one-logical-axis", "use-percentages-with-care", "apply-conditionally"],
  "min-width": ["preserve-a-minimum-inline-size", "allow-flexible-children-to-shrink", "combine-with-width-and-max-width", "use-intrinsic-keywords", "apply-conditionally"],
  "mix-blend-mode": ["blend-an-element-with-its-backdrop", "restore-normal-blending", "apply-conditionally"],
  "object-fit": ["cover-a-fixed-frame", "contain-the-full-media", "disable-object-fitting", "apply-conditionally"],
  "object-position": ["center-cropped-media", "pin-the-top-of-an-image", "use-precise-positions", "apply-conditionally"],
  "opacity": ["fade-an-entire-element", "prefer-color-alpha-for-surfaces", "apply-conditionally"],
  "order": ["change-visual-order", "keep-source-order-meaningful", "apply-conditionally"],
  "outline": ["set-the-full-outline-shorthand", "keep-outlines-for-focus", "apply-conditionally"],
  "outline-color": ["set-outline-color", "inherit-the-text-color", "apply-conditionally"],
  "outline-offset": ["move-an-outline-away-from-the-element", "pull-an-outline-inward", "apply-conditionally"],
  "outline-style": ["set-outline-style", "use-dashed-focus-indicators", "apply-conditionally"],
  "outline-width": ["set-outline-width", "use-keyword-widths", "apply-conditionally"],
  "overflow": ["hide-overflowing-content", "create-a-scroll-container", "clip-without-scrolling", "truncate-a-single-line", "apply-conditionally"],
  "overflow-wrap": ["break-long-unbroken-content", "allow-breaks-anywhere", "restore-normal-wrapping", "apply-conditionally"],
  "overscroll-behavior": ["contain-nested-scrolling", "block-page-bounce-on-one-axis", "keep-horizontal-gestures-local", "apply-conditionally"],
  "padding": ["quick-answer", "multiple-values", "add-padding-on-every-side", "set-one-side", "set-inline-or-block-padding", "apply-conditionally"],
  "place-content": ["align-grid-or-wrapped-flex-content-on-both-axes", "use-separate-axis-values", "apply-conditionally"],
  "place-items": ["align-grid-items-on-both-axes", "stretch-items", "apply-conditionally"],
  "place-self": ["align-one-item-on-both-axes", "center-one-item", "apply-conditionally"],
  "pointer-events": ["let-clicks-pass-through-an-overlay", "use-the-untouchable-alias", "restore-pointer-events-on-a-child", "apply-conditionally"],
  "position": ["positioning-elements-as-static", "positioning-elements-as-relative", "positioning-elements-as-absolute", "positioning-elements-as-fixed", "positioning-elements-as-sticky", "apply-conditionally"],
  "resize": ["allow-both-axis-resizing", "restrict-resizing-to-one-axis", "disable-native-resizing", "apply-conditionally"],
  "screen-readers": ["hide-text-visually", "label-icon-only-controls", "avoid-hiding-interactive-content", "apply-conditionally"],
  "scroll-behavior": ["enable-smooth-anchor-scrolling", "keep-static-output-immediate", "combine-with-scroll-offsets", "apply-conditionally"],
  "scroll-margin": ["offset-anchor-targets", "add-horizontal-snap-margin", "use-all-side-margin-for-compact-cases", "apply-conditionally"],
  "scroll-padding": ["pad-the-scroll-container", "reserve-space-for-fixed-headers", "pad-horizontal-snapping", "apply-conditionally"],
  "scroll-snap-align": ["align-a-snap-item-to-the-start", "center-snap-items", "disable-item-snapping", "apply-conditionally"],
  "scroll-snap-stop": ["force-a-snap-stop", "keep-normal-scroll-momentum", "use-sparingly", "apply-conditionally"],
  "scroll-snap-type": ["snap-on-the-horizontal-axis", "require-a-snap-point", "allow-nearby-snap-points", "apply-conditionally"],
  "shape-image-threshold": ["set-the-alpha-threshold", "use-lower-thresholds-for-soft-masks", "use-with-image-shapes", "apply-conditionally"],
  "shape-margin": ["add-space-around-a-shape", "increase-margin-for-large-media", "pair-with-shape-outside", "apply-conditionally"],
  "shape-outside": ["wrap-text-around-a-circle", "use-an-inset-shape", "remove-shape-wrapping", "apply-conditionally"],
  "size": ["set-width-and-height-together", "build-square-media-and-controls", "set-one-logical-axis", "use-the-full-static-utility", "use-intrinsic-static-utilities", "apply-conditionally"],
  "stroke": ["set-svg-stroke-color", "use-theme-colors", "apply-conditionally"],
  "stroke-width": ["set-svg-stroke-width", "pair-width-with-stroke-color", "apply-conditionally"],
  "text-align": ["align-contents-to-the-left", "align-contents-to-the-right", "center-contents", "align-contents-to-the-left-and-right", "use-logical-alignment", "apply-conditionally"],
  "text-decoration": ["set-a-complete-decoration", "use-line-aliases", "remove-decoration", "apply-conditionally"],
  "text-decoration-color": ["set-decoration-color", "follow-the-current-text-color", "hide-decoration-color", "apply-conditionally"],
  "text-decoration-line": ["underline-text", "combine-line-values", "use-shorthand-aliases-for-common-cases", "apply-conditionally"],
  "text-decoration-style": ["use-a-wavy-decoration", "use-dashed-or-dotted-lines", "return-to-solid-lines", "apply-conditionally"],
  "text-decoration-thickness": ["set-decoration-thickness", "use-font-provided-thickness", "pair-with-underline-offset", "apply-conditionally"],
  "text-fill-color": ["fill-text-with-a-color", "make-text-fill-transparent", "use-the-current-color", "apply-conditionally"],
  "text-indent": ["indent-the-first-line", "use-spacing-values", "reset-at-a-breakpoint", "apply-conditionally"],
  "text-orientation": ["keep-characters-upright", "use-mixed-orientation", "use-sideways-orientation", "apply-conditionally"],
  "text-overflow": ["clip-overflowing-inline-text", "show-an-ellipsis", "use-in-flex-rows", "apply-conditionally"],
  "text-rendering": ["optimize-legibility", "prefer-speed-for-dense-updates", "return-to-browser-behavior", "apply-conditionally"],
  "text-shadow": ["add-a-text-shadow", "use-text-shadows-sparingly", "apply-conditionally"],
  "text-size": ["body-text", "headings", "page-titles-hero-sections", "use-a-precise-size", "apply-conditionally"],
  "text-stroke": ["set-stroke-width-and-color-together", "combine-stroke-with-transparent-fill", "split-width-and-color-when-states-differ", "apply-conditionally"],
  "text-stroke-color": ["set-text-stroke-color", "use-the-current-color", "make-the-stroke-transparent", "apply-conditionally"],
  "text-stroke-width": ["set-text-stroke-width", "use-the-explicit-property-name", "remove-the-stroke-width", "apply-conditionally"],
  "text-transform": ["capitalized-text", "lowercase-text", "uppercase-text", "sentence", "apply-conditionally"],
  "text-underline-offset": ["move-underline-away-from-text", "pair-with-decoration-thickness", "reset-in-compact-contexts", "apply-conditionally"],
  "text-wrap": ["balance-short-headings", "prefer-pretty-wrapping-for-prose", "prevent-wrapping", "apply-conditionally"],
  "touch-action": ["disable-browser-gestures-on-a-custom-surface", "allow-vertical-scrolling", "optimize-tap-controls", "apply-conditionally"],
  "transform": ["move-an-element", "scale-pressed-controls", "rotate-or-skew-decorative-elements", "set-the-pivot-separately", "apply-conditionally"],
  "transform-box": ["choose-the-transform-reference-box", "use-the-border-box-for-html-elements", "pair-with-transform-origin", "apply-conditionally"],
  "transform-origin": ["set-the-pivot-point", "use-two-axis-origins", "match-the-origin-to-the-interaction", "apply-conditionally"],
  "transform-style": ["preserve-3d-children", "flatten-nested-transforms", "combine-with-perspective", "apply-conditionally"],
  "transition": ["declare-a-complete-transition", "animate-transforms-explicitly", "split-longhands-when-states-differ", "apply-conditionally"],
  "transition-delay": ["delay-a-transition", "stagger-sibling-elements", "use-duration-tokens", "reset-delay-at-breakpoints", "apply-conditionally"],
  "transition-duration": ["set-transition-speed", "match-duration-to-distance", "remove-motion-for-static-contexts", "apply-conditionally"],
  "transition-property": ["limit-what-can-animate", "pair-with-duration-and-easing", "disable-accidental-transitions", "apply-conditionally"],
  "transition-timing-function": ["choose-an-easing-curve", "use-linear-timing-for-continuous-motion", "keep-entrance-and-exit-curves-intentional", "apply-conditionally"],
  "user-drag": ["prevent-dragging-media", "keep-draggable-elements-explicit", "reset-to-browser-behavior", "apply-conditionally"],
  "user-select": ["disable-selection-on-controls", "select-all-text-in-one-click", "preserve-normal-reading-selection", "apply-conditionally"],
  "vertical-align": ["align-inline-content", "align-icons-with-text", "align-table-cells", "apply-conditionally"],
  "visibility": ["hide-but-preserve-layout", "make-an-element-visible-again", "collapse-table-rows", "apply-conditionally"],
  "white-space": ["keep-text-on-one-line", "preserve-authored-line-breaks", "preserve-spaces-and-wrapping", "apply-conditionally"],
  "width": ["set-a-fixed-or-fluid-width", "use-percentages-for-proportional-layout", "use-intrinsic-width-keywords", "use-container-widths-for-wrappers", "apply-conditionally"],
  "will-change": ["hint-an-upcoming-transform", "hint-opacity-changes", "reset-when-the-hint-is-no-longer-useful", "apply-conditionally"],
  "word-break": ["keep-normal-word-boundaries", "break-anywhere-inside-words", "keep-cjk-words-together", "use-the-break-word-shortcut", "apply-conditionally"],
  "word-spacing": ["add-space-between-words", "use-fixed-spacing-when-needed", "avoid-overusing-wide-spacing", "apply-conditionally"],
  "writing-mode": ["use-vertical-right-to-left-flow", "restore-horizontal-text", "pair-with-text-orientation", "apply-conditionally"],
  "z-index": ["order-positioned-elements", "use-negative-stacking-when-intentional", "prefer-local-stacking-contexts", "apply-conditionally"],
}
