import { transitions } from './transitions'
import { transforms } from './transforms'
import { shapes } from './shapes'
import { media } from './media'
import { borderPaint } from './border-paint'
import { edges } from './edges'
import { overscroll, scrolling } from './scrolling'
import { flexbox } from './flexbox'
import { alignment } from './alignment'
import { grid } from './grid'
import { position, inset, stacking, isolation } from './positioning'
import { overflow } from './clipping'
import type { SceneFactory } from './types'
import { flow } from './layout'
import { sizing } from './sizing'
import { textEffects } from './text-effects'
import { textFlow } from './text-flow'
import { typeSpecimens } from './type-specimens'
import { typography } from './typography'
import { effects } from './effects'
import { backgrounds } from './backgrounds'
import { interaction } from './interaction'
import { animations } from './animations'

/** Explicit utility ownership: no catch-all scene can silently satisfy coverage. */
export const referenceScenes: Record<string, SceneFactory> = {
  'accent-color': interaction,
  'align-content': alignment,
  'align-items': alignment,
  'align-self': alignment,
  'animation': animations,
  'animation-delay': animations,
  'animation-direction': animations,
  'animation-duration': animations,
  'animation-fill-mode': animations,
  'animation-iteration-count': animations,
  'animation-name': animations,
  'animation-play-state': animations,
  'animation-timing-function': animations,
  'appearance': interaction,
  'aspect-ratio': sizing,
  'backdrop-filter': effects,
  'background': backgrounds,
  'background-attachment': backgrounds,
  'background-blend-mode': backgrounds,
  'background-clip': backgrounds,
  'background-color': backgrounds,
  'background-image': backgrounds,
  'background-origin': backgrounds,
  'background-position': backgrounds,
  'background-repeat': backgrounds,
  'background-size': backgrounds,
  'border': edges,
  'border-collapse': borderPaint,
  'border-color': edges,
  'border-image': borderPaint,
  'border-image-outset': borderPaint,
  'border-image-repeat': borderPaint,
  'border-image-slice': borderPaint,
  'border-image-source': borderPaint,
  'border-image-width': borderPaint,
  'border-radius': edges,
  'border-style': edges,
  'border-width': edges,
  'box-decoration-break': borderPaint,
  'box-shadow': edges,
  'box-sizing': flow,
  'break-after': flow,
  'break-before': flow,
  'break-inside': flow,
  'caret-color': interaction,
  'clear': flow,
  'clip-path': effects,
  'color': backgrounds,
  'column-span': flow,
  'columns': flow,
  'contain': flow,
  'content': typography,
  'counter-increment': typography,
  'counter-reset': typography,
  'counter-set': typography,
  'cursor': interaction,
  'direction': textFlow,
  'display': flow,
  'fill': media,
  'filter': effects,
  'flex': flexbox,
  'flex-basis': flexbox,
  'flex-direction': flexbox,
  'flex-grow': flexbox,
  'flex-shrink': flexbox,
  'flex-wrap': flexbox,
  'float': flow,
  'font-family': typeSpecimens,
  'font-feature-settings': typeSpecimens,
  'font-size': typeSpecimens,
  'font-smooth': typeSpecimens,
  'font-style': typeSpecimens,
  'font-variant-numeric': typeSpecimens,
  'font-weight': typeSpecimens,
  'gap': sizing,
  'grid': grid,
  'grid-area': grid,
  'grid-auto-columns': grid,
  'grid-auto-flow': grid,
  'grid-auto-rows': grid,
  'grid-column': grid,
  'grid-columns': grid,
  'grid-row': grid,
  'grid-rows': grid,
  'grid-template': grid,
  'grid-template-areas': grid,
  'grid-template-columns': grid,
  'grid-template-rows': grid,
  'height': sizing,
  'hyphens': textFlow,
  'inset': inset,
  'isolation': isolation,
  'justify-content': alignment,
  'justify-items': alignment,
  'justify-self': alignment,
  'letter-spacing': typeSpecimens,
  'line-clamp': textFlow,
  'line-height': typeSpecimens,
  'list-style': typography,
  'list-style-image': typography,
  'list-style-position': typography,
  'list-style-type': typography,
  'margin': sizing,
  'mask-image': effects,
  'max-height': sizing,
  'max-size': sizing,
  'max-width': sizing,
  'min-height': sizing,
  'min-size': sizing,
  'min-width': sizing,
  'mix-blend-mode': effects,
  'object-fit': media,
  'object-position': media,
  'opacity': effects,
  'order': flexbox,
  'outline': edges,
  'outline-color': edges,
  'outline-offset': edges,
  'outline-style': edges,
  'outline-width': edges,
  'overflow': overflow,
  'overflow-wrap': textFlow,
  'overscroll-behavior': overscroll,
  'padding': sizing,
  'place-content': alignment,
  'place-items': alignment,
  'place-self': alignment,
  'pointer-events': interaction,
  'position': position,
  'resize': interaction,
  'screen-readers': interaction,
  'scroll-behavior': scrolling,
  'scroll-margin': scrolling,
  'scroll-padding': scrolling,
  'scroll-snap-align': scrolling,
  'scroll-snap-stop': scrolling,
  'scroll-snap-type': scrolling,
  'shape-image-threshold': shapes,
  'shape-margin': shapes,
  'shape-outside': shapes,
  'size': sizing,
  'stroke': media,
  'stroke-width': media,
  'text-align': textFlow,
  'text-decoration': textEffects,
  'text-decoration-color': textEffects,
  'text-decoration-line': textEffects,
  'text-decoration-style': textEffects,
  'text-decoration-thickness': textEffects,
  'text-fill-color': textEffects,
  'text-indent': textFlow,
  'text-orientation': textFlow,
  'text-overflow': textFlow,
  'text-rendering': textFlow,
  'text-shadow': textEffects,
  'text-size': typeSpecimens,
  'text-stroke': textEffects,
  'text-stroke-color': textEffects,
  'text-stroke-width': textEffects,
  'text-transform': textFlow,
  'text-underline-offset': textEffects,
  'text-wrap': textFlow,
  'touch-action': interaction,
  'transform': transforms,
  'transform-box': transforms,
  'transform-origin': transforms,
  'transform-style': transforms,
  'transition': transitions,
  'transition-delay': transitions,
  'transition-duration': transitions,
  'transition-property': transitions,
  'transition-timing-function': transitions,
  'user-drag': interaction,
  'user-select': interaction,
  'vertical-align': typeSpecimens,
  'visibility': flow,
  'white-space': textFlow,
  'width': sizing,
  'will-change': transforms,
  'word-break': textFlow,
  'word-spacing': typeSpecimens,
  'writing-mode': textFlow,
  'z-index': stacking,
}
