export const MASTER_CSS_RUNTIME_BOOTSTRAP_ID = 'virtual:master-css-runtime'
export const RESOLVED_MASTER_CSS_RUNTIME_BOOTSTRAP_ID = `\0${MASTER_CSS_RUNTIME_BOOTSTRAP_ID}`

export function createMasterCSSRuntimeBootstrapSource() {
  return [
    `import { MasterCSSRuntime } from '@master/css-runtime'`,
    `import masterCSSManifest from 'virtual:master-css-manifest'`,
    `import masterCSSEmittedGlobals from 'virtual:master-css-emitted-globals'`,
    ``,
    `let masterCSSRuntime`,
    `let currentManifest = masterCSSManifest`,
    `let currentEmittedGlobals = masterCSSEmittedGlobals`,
    `let startGeneration = 0`,
    `let pendingStart = import.meta.hot?.data.pendingRuntimeStart ?? Promise.resolve()`,
    ``,
    `function disposeRuntime() {`,
    `  startGeneration++`,
    `  masterCSSRuntime?.dispose()`,
    `  masterCSSRuntime = undefined`,
    `}`,
    ``,
    `async function startRuntime(manifest = currentManifest, emittedGlobals = currentEmittedGlobals) {`,
    `  if (typeof document === 'undefined') return`,
    `  disposeRuntime()`,
    `  const generation = startGeneration`,
    `  const startup = pendingStart.catch(() => {}).then(async () => {`,
    `    if (generation !== startGeneration) return`,
    `    const nextRuntime = await MasterCSSRuntime.start({`,
    `      manifest,`,
    `      emittedGlobals,`,
    `      onDiagnostic: diagnostic => console.error(diagnostic)`,
    `    })`,
    `    if (generation !== startGeneration) {`,
    `      nextRuntime.dispose()`,
    `      return`,
    `    }`,
    `    masterCSSRuntime = nextRuntime.observe()`,
    `  })`,
    `  pendingStart = startup`,
    `  await startup`,
    `}`,
    ``,
    `if (typeof document !== 'undefined') {`,
    `  void startRuntime().catch(error => console.error(error, error?.cause))`,
    `}`,
    ``,
    `if (import.meta.hot) {`,
    `  import.meta.hot.accept(() => {})`,
    `  import.meta.hot.accept([`,
    `    'virtual:master-css-manifest',`,
    `    'virtual:master-css-emitted-globals'`,
    `  ], ([manifestModule, emittedGlobalsModule]) => {`,
    `    currentManifest = manifestModule?.default ?? currentManifest`,
    `    currentEmittedGlobals = emittedGlobalsModule?.default ?? currentEmittedGlobals`,
    `    void startRuntime().catch(error => console.error(error, error?.cause))`,
    `  })`,
    `  import.meta.hot.dispose(data => {`,
    `    disposeRuntime()`,
    `    data.pendingRuntimeStart = pendingStart`,
    `  })`,
    `}`,
    ``
  ].join('\n')
}
