// Generated by `cargo xtask codegen`. Do not edit directly.

export const MASTER_CSS_BINDING_ABI_VERSION = 6 as const
export const MASTER_CSS_MANIFEST_VERSION = 1 as const
export const MASTER_CSS_HYDRATION_MANIFEST_VERSION = 1 as const
export const MASTER_CSS_ENGINE_TRANSITION_VERSION = 1 as const
export const MASTER_CSS_VALIDATOR_BATCH_VERSION = 1 as const
export const MASTER_CSS_DIAGNOSTICS_REPORT_VERSION = 1 as const
export const MASTER_CSS_LINT_BATCH_VERSION = 1 as const
export const MASTER_CSS_LANGUAGE_BATCH_VERSION = 1 as const
export const MASTER_CSS_LEXER_BATCH_VERSION = 1 as const
export const MASTER_CSS_SOURCE_BATCH_VERSION = 1 as const

export type MasterCSSBindingSurface = 'native' | 'runtime' | 'compiler' | 'tooling' | 'cli'

export type MasterCSSBindingFeature =
  | 'cli'
  | 'compiler'
  | 'diagnostics'
  | 'engine'
  | 'language'
  | 'lexer'
  | 'lint'
  | 'project'
  | 'render'
  | 'scanner'
  | 'source'
  | 'validator'

export interface MasterCSSBindingInfo {
  bindingAbiVersion: typeof MASTER_CSS_BINDING_ABI_VERSION
  packageVersion: string
  manifestVersion: typeof MASTER_CSS_MANIFEST_VERSION
  hydrationManifestVersion: typeof MASTER_CSS_HYDRATION_MANIFEST_VERSION
  engineTransitionVersion: typeof MASTER_CSS_ENGINE_TRANSITION_VERSION
  validatorBatchVersion: typeof MASTER_CSS_VALIDATOR_BATCH_VERSION
  diagnosticsReportVersion: typeof MASTER_CSS_DIAGNOSTICS_REPORT_VERSION
  lintBatchVersion: typeof MASTER_CSS_LINT_BATCH_VERSION
  languageBatchVersion: typeof MASTER_CSS_LANGUAGE_BATCH_VERSION
  lexerBatchVersion: typeof MASTER_CSS_LEXER_BATCH_VERSION
  sourceBatchVersion: typeof MASTER_CSS_SOURCE_BATCH_VERSION
  target: string
  surface: MasterCSSBindingSurface
  features: MasterCSSBindingFeature[]
}

export type MasterCSSBinding = 'auto' | 'native' | 'wasm'
export type MasterCSSResolvedBinding = Exclude<MasterCSSBinding, 'auto'>
export type MasterCSSRuleTarget =
  | 'theme'
  | 'base'
  | 'defaults'
  | 'components'
  | 'utilities'
  | 'keyframes'

export interface MasterCSSSourceRange {
  start: number
  end: number
}

export interface MasterCSSEngineInsertMutation {
  op: 'insert'
  target: MasterCSSRuleTarget
  index: number
  key: string
  text: string
  rule?: import('@master/css-schema/hydration-manifest').MasterCSSHydrationRule
}

export interface MasterCSSEngineDeleteMutation {
  op: 'delete'
  target: MasterCSSRuleTarget
  index: number
  key: string
}

export type MasterCSSEngineMutation =
  | MasterCSSEngineInsertMutation
  | MasterCSSEngineDeleteMutation

export interface MasterCSSEngineTransition {
  version: typeof MASTER_CSS_ENGINE_TRANSITION_VERSION
  mutations: MasterCSSEngineMutation[]
}

export interface MasterCSSEngineSnapshot {
  version: 1
  rules: import('@master/css-schema/hydration-manifest').MasterCSSHydrationRule[]
  resources: MasterCSSEngineResources
  text: string
}

export interface MasterCSSEngineVariableResource {
  name: string
  refCount: number
  dependencies: string[]
  static: boolean
}

export interface MasterCSSEngineAnimationResource {
  name: string
  index: number
  refCount: number
  text: string
}

export interface MasterCSSEngineResources {
  themeText?: string
  variables: MasterCSSEngineVariableResource[]
  animations: MasterCSSEngineAnimationResource[]
}

export interface MasterCSSEngineInspection {
  version: 1
  className: string
  valid: boolean
  rules: import('@master/css-schema/hydration-manifest').MasterCSSHydrationRule[]
}

export interface MasterCSSNativeDeclarationCandidate {
  className: string
  property: string
  value: string
}

export interface MasterCSSLexerClassListInput {
  source: string
  unescape?: string[]
}

export interface MasterCSSLexerBatchRequest {
  classLists?: MasterCSSLexerClassListInput[]
  cssSources?: string[]
  escapeIdentifiers?: string[]
}

export interface MasterCSSLexerClassListItem {
  range: MasterCSSSourceRange
  raw: string
  token: string
}

export interface MasterCSSLexerCSSDirective {
  name: string
  range: MasterCSSSourceRange
  preludeRange: MasterCSSSourceRange
  hasBlock: boolean
  quotedStrings: number
}

export interface MasterCSSLexerCSSImport {
  range: MasterCSSSourceRange
  statement: string
  source?: string
}

export interface MasterCSSLexerCSSAnalysis {
  directives: MasterCSSLexerCSSDirective[]
  imports: MasterCSSLexerCSSImport[]
}

export interface MasterCSSLexerBatch {
  version: typeof MASTER_CSS_LEXER_BATCH_VERSION
  classLists: MasterCSSLexerClassListItem[][]
  cssSources: MasterCSSLexerCSSAnalysis[]
  escapedIdentifiers: string[]
}

export type MasterCSSSourceExtractorKind = 'auto' | 'raw' | 'oxc' | 'html' | 'astro'

export interface MasterCSSSourceExtractionInput {
  source: string
  content: string
  kind?: MasterCSSSourceExtractorKind
}

export interface MasterCSSSourceBatchRequest {
  files: MasterCSSSourceExtractionInput[]
}

export interface MasterCSSSourceExtraction {
  source: string
  candidates: string[]
}

export interface MasterCSSSourceBatch {
  version: typeof MASTER_CSS_SOURCE_BATCH_VERSION
  files: MasterCSSSourceExtraction[]
}

export interface MasterCSSScannerUpdate {
  changed: boolean
  cacheHit: boolean
  candidates: string[]
  validClasses: string[]
  invalidClasses: string[]
  usedNativeClasses?: string[]
  transition: MasterCSSEngineTransition
}

export interface MasterCSSScannerState {
  latentClasses: string[]
  validClasses: string[]
  invalidClasses: string[]
  nativeClasses?: string[]
  usedNativeClasses?: string[]
  cachedSources: number
  engine: MasterCSSEngineSnapshot
}

export type MasterCSSInspectionDiagnosticSeverity = 'error' | 'warning'
export type MasterCSSInspectionDiagnosticCode =
  | 'invalid-scanner-class'
  | 'missing-css'
  | 'stylesheet-error'
  | 'stylesheet-warning'
  | 'scanner-error'
export type MasterCSSInspectionDiagnosticSourceKind = 'scanner' | 'stylesheet' | 'missing-css'
export type MasterCSSMissingCSSStatus = 'present' | 'missing'
export type MasterCSSMissingCSSReason =
  | 'generated'
  | 'native-css'
  | 'safelist'
  | 'invalid'
  | 'blocklisted'
  | 'not-detected'

export interface MasterCSSMissingCSSResult {
  className: string
  status: MasterCSSMissingCSSStatus
  reason: MasterCSSMissingCSSReason
}

export type MasterCSSInspectionDiagnosticData =
  | { cwd: string }
  | { className: string }
  | MasterCSSMissingCSSResult

export interface MasterCSSInspectionDiagnostic {
  code: MasterCSSInspectionDiagnosticCode
  severity: MasterCSSInspectionDiagnosticSeverity
  message: string
  source: 'Master CSS'
  sourceKind: MasterCSSInspectionDiagnosticSourceKind
  filePath?: string
  data?: MasterCSSInspectionDiagnosticData
}

export interface MasterCSSDiscoveredClasses {
  latent: readonly string[]
  valid: readonly string[]
  invalid: readonly string[]
  usedNative: readonly string[]
}

export interface MasterCSSSourceInspection {
  filePath: string
  source: string
  scanned: boolean
  changed: boolean
  discovered: MasterCSSDiscoveredClasses
}

export interface MasterCSSStylesheetInspection {
  filePath: string
  masterCSS: boolean
  pruneNativeCSS: boolean
  dependencies: readonly string[]
  sourceDependencies: readonly string[]
  warnings: readonly string[]
  errors: readonly string[]
}

export interface MasterCSSStylesheetError {
  filePath: string
  message: string
}

export interface MasterCSSDiagnosticsReportInput {
  version: typeof MASTER_CSS_DIAGNOSTICS_REPORT_VERSION
  cwd: string
  patterns: readonly string[]
  files: readonly MasterCSSSourceInspection[]
  classes: readonly string[]
  scanner: {
    latent?: readonly string[]
    valid?: readonly string[]
    invalid?: readonly string[]
    native?: readonly string[]
    usedNative?: readonly string[]
    safelist?: readonly string[]
    blocklist?: readonly (string | MasterCSSRegex)[]
    resetDependencies?: readonly string[]
  }
  stylesheets: {
    entries?: readonly MasterCSSStylesheetInspection[]
    warnings?: readonly string[]
    errors?: readonly MasterCSSStylesheetError[]
  }
  css: {
    text?: string
    included?: boolean
    variables?: readonly string[]
    animations?: readonly string[]
  }
  firstSourceByClass?: Record<string, string>
  fatalError?: string
}

export interface MasterCSSInspectionReport {
  version: typeof MASTER_CSS_DIAGNOSTICS_REPORT_VERSION
  cwd: string
  inputs: {
    patterns: string[]
    files: string[]
    classes: string[]
  }
  scanner: {
    counts: {
      latent: number
      valid: number
      invalid: number
      native: number
      usedNative: number
      safelist: number
      blocklist: number
    }
    classes: {
      latent: string[]
      valid: string[]
      invalid: string[]
      native: string[]
      usedNative: string[]
      safelist: string[]
      blocklist: string[]
    }
    resetDependencies: string[]
  }
  stylesheets: {
    entries: MasterCSSStylesheetInspection[]
    dependencies: string[]
    warnings: string[]
    errors: MasterCSSStylesheetError[]
  }
  css: {
    bytes: number
    included: boolean
    text?: string
    emittedGlobals: {
      variables: number
      animations: number
    }
  }
  missingCSS: {
    checked: string[]
    present: MasterCSSMissingCSSResult[]
    missing: MasterCSSMissingCSSResult[]
  }
  files: MasterCSSSourceInspection[]
  diagnostics: MasterCSSInspectionDiagnostic[]
  summary: {
    files: number
    stylesheets: number
    diagnostics: number
    errors: number
    warnings: number
    missingCSS: number
    invalidClasses: number
  }
}

export interface MasterCSSValidatorClass {
  className: string
  matched: boolean
  rules: import('@master/css-schema/hydration-manifest').MasterCSSHydrationRule[]
}

export interface MasterCSSValidatorBatch {
  version: typeof MASTER_CSS_VALIDATOR_BATCH_VERSION
  classes: MasterCSSValidatorClass[]
}

export interface MasterCSSLintClassConflict {
  className: string
  conflicts: string[]
}

export interface MasterCSSLintPartialClassConflict {
  className: string
  replacement: string
  conflict: string
}

export interface MasterCSSLintBatch {
  version: typeof MASTER_CSS_LINT_BATCH_VERSION
  sortedClassNames: string[]
  conflicts: MasterCSSLintClassConflict[]
  partialConflicts: MasterCSSLintPartialClassConflict[]
}

export interface MasterCSSLintRawValueCandidate {
  className: string
  key: string
  segments: string[]
  properties: string[]
}

export interface MasterCSSLintRawValueCandidates {
  version: typeof MASTER_CSS_LINT_BATCH_VERSION
  candidates: MasterCSSLintRawValueCandidate[]
}

export interface MasterCSSLintCanonicalClassNameOptions {
  preferStaticUtilities: boolean
  preferThemeTokens: boolean
  preferPropertyAliases: boolean
  preferVariableReferences: boolean
  preferMultiValueTokens: boolean
  preferCompositionUtilities: boolean
  preferConditionOrder: boolean
  preferNativeDeclarationsInCompose: boolean
  preferVariantBlocksInCompose: boolean
}

export interface MasterCSSLintCanonicalClassSuggestion {
  className: string
  recommended: string
}

export interface MasterCSSLintCanonicalClassSuggestions {
  version: typeof MASTER_CSS_LINT_BATCH_VERSION
  suggestions: MasterCSSLintCanonicalClassSuggestion[]
}

export interface MasterCSSLintCanonicalClassGroupSuggestion {
  classNames: string[]
  recommended: string
}

export interface MasterCSSLintCanonicalClassGroupSuggestions {
  version: typeof MASTER_CSS_LINT_BATCH_VERSION
  suggestions: MasterCSSLintCanonicalClassGroupSuggestion[]
}

export type MasterCSSLintCanonicalComposeSuggestionKind =
  | 'class'
  | 'native-declaration'
  | 'variant-block'

export interface MasterCSSLintCanonicalComposeSuggestion {
  actual: string
  recommended: string
  classNames: string[]
  kind: MasterCSSLintCanonicalComposeSuggestionKind
}

export interface MasterCSSLintCanonicalComposeDirective {
  version: typeof MASTER_CSS_LINT_BATCH_VERSION
  suggestions: MasterCSSLintCanonicalComposeSuggestion[]
  structuralChange?: boolean
  replacement?: string
}

export interface MasterCSSLintEdit {
  range: MasterCSSSourceRange
  text: string
  scope: 'class-list' | 'directive'
}

export interface MasterCSSLintDiagnostic {
  ruleId: 'sort-classes' | 'no-invalid-classes' | 'no-conflicting-classes' | 'prefer-canonical-classes' | 'no-unapproved-raw-values'
  code:
    | 'invalid-class-order'
    | 'invalid-class'
    | 'unknown-class'
    | 'conflicting-class'
    | 'partially-conflicting-class'
    | 'prefer-canonical-class'
    | 'prefer-native-declaration'
    | 'prefer-variant-block'
    | 'unapproved-raw-value'
  message: string
  range: MasterCSSSourceRange
  data?: Record<string, string | number | boolean | string[] | null>
  fix?: MasterCSSLintEdit
}

export interface MasterCSSLintClassList {
  version: typeof MASTER_CSS_LINT_BATCH_VERSION
  analysis: MasterCSSLintBatch
  diagnostics: MasterCSSLintDiagnostic[]
  sortEdit?: MasterCSSLintEdit
  conflictEdit?: MasterCSSLintEdit
  conflictRange?: MasterCSSSourceRange
}

export interface MasterCSSLintHostValidation {
  invalidGeneratedClasses: string[]
  validationErrors: string[][]
}

export interface MasterCSSLintRawValuePolicy {
  allowRawValues?: boolean
  allowProperties?: readonly string[]
  allowedPatterns?: readonly string[]
}

export interface MasterCSSLintClassListPolicyRequest {
  version: typeof MASTER_CSS_LINT_BATCH_VERSION
  classList: string
  classNames: readonly string[]
  nativeSupport?: readonly boolean[]
  invalidGeneratedClasses?: readonly string[]
  validationErrors?: readonly (readonly string[])[]
  disallowUnknownClass?: boolean
  canonicalOptions?: Partial<MasterCSSLintCanonicalClassNameOptions>
  composeDirective?: boolean
  rawValuePolicy?: MasterCSSLintRawValuePolicy
}

export interface MasterCSSLanguageClassListContext {
  start: number
  end: number
  unescape?: readonly string[]
}

export interface MasterCSSLanguageDocumentSettings {
  classAttributes?: readonly string[]
  classFunctions?: readonly string[]
  classDeclarations?: readonly string[]
}

export interface MasterCSSLanguageDocumentRequest {
  source: string
  languageId: string
  hostRanges?: readonly MasterCSSLanguageClassListContext[]
  settings?: MasterCSSLanguageDocumentSettings
}

export interface MasterCSSLanguageClassPosition {
  range: MasterCSSSourceRange
  contextRange: MasterCSSSourceRange
  raw: string
  token: string
}

export interface MasterCSSLanguageSemanticToken {
  start: number
  end: number
  type: string
  modifiers: string[]
}

export interface MasterCSSLanguageDocument {
  version: typeof MASTER_CSS_LANGUAGE_BATCH_VERSION
  classPositions: MasterCSSLanguageClassPosition[]
  semanticTokens: MasterCSSLanguageSemanticToken[]
  semanticTokenData: number[]
}

export interface MasterCSSLanguageFormatRequest {
  source: string
  range?: MasterCSSSourceRange
  styleRanges?: readonly MasterCSSSourceRange[]
}

export interface MasterCSSLanguageFormatEdit {
  range: MasterCSSSourceRange
  text: string
}

export interface MasterCSSLanguageFormatEdits {
  version: typeof MASTER_CSS_LANGUAGE_BATCH_VERSION
  edits: MasterCSSLanguageFormatEdit[]
}

export type MasterCSSLanguageClassKind =
  | 'unknown'
  | 'component'
  | 'semantic'
  | 'pattern'
  | 'declaration'

export interface MasterCSSLanguageClass {
  className: string
  kind: MasterCSSLanguageClassKind
  matcherTypes: ('static' | 'pattern' | 'key' | 'variable' | 'value')[]
  keyToken?: string
  valueToken?: string
  stateToken?: string
  important: boolean
}

export interface MasterCSSLanguageClassifications {
  version: typeof MASTER_CSS_LANGUAGE_BATCH_VERSION
  variableNames: string[]
  classes: MasterCSSLanguageClass[]
}

export interface MasterCSSLanguageVariable {
  namespace?: string
  name: string
  key: string
  type: string
  value?: string | number
  numeric?: import('@master/css-schema/manifest').MasterCSSManifestVariableNumericValue
  modes?: import('@master/css-schema/manifest').MasterCSSManifestVariable['modes']
  dependencies?: string[]
  inline?: boolean
  static?: boolean
}

export interface MasterCSSLanguageClassVariable {
  key: string
  variable: MasterCSSLanguageVariable
}

export interface MasterCSSLanguageInspection {
  version: typeof MASTER_CSS_LANGUAGE_BATCH_VERSION
  className: string
  valid: boolean
  kind: MasterCSSLanguageClassKind
  base: string
  suffix: string
  key?: string
  value?: string
  keyToken?: string
  valueToken?: string
  stateToken?: string
  important: boolean
  matcherTypes: ('static' | 'pattern' | 'key' | 'variable' | 'value')[]
  variables: MasterCSSLanguageClassVariable[]
  rules: import('@master/css-schema/hydration-manifest').MasterCSSHydrationRule[]
  text: string
}

export type MasterCSSLanguageCompletionKind = 'property' | 'value'

export interface MasterCSSLanguageCompletionEntry {
  label: string
  kind: MasterCSSLanguageCompletionKind
  detail?: string
  documentationText?: string
  sortText?: string
  triggerSuggest: boolean
}

export interface MasterCSSLanguageCompletionIndex {
  version: typeof MASTER_CSS_LANGUAGE_BATCH_VERSION
  classEntries: MasterCSSLanguageCompletionEntry[]
}

export interface MasterCSSLanguageColorPresentation {
  version: typeof MASTER_CSS_LANGUAGE_BATCH_VERSION
  colorToken: string
  space?: string
}

export interface MasterCSSLanguageColorCandidateInput {
  className: string
  start: number
}

export interface MasterCSSLanguageColorToken {
  range: MasterCSSSourceRange
  value: string
  alpha?: number
}

export interface MasterCSSLanguageColorTokens {
  version: typeof MASTER_CSS_LANGUAGE_BATCH_VERSION
  tokens: MasterCSSLanguageColorToken[]
}

export type MasterCSSDirectiveManifestInput =
  import('@master/css-schema/css-directives').CSSDirectiveManifestInput

export type MasterCSSDirectiveVariableDefinition =
  import('@master/css-schema/css-directives').CSSDirectiveVariableDefinition

export interface MasterCSSRegex {
  source: string
  flags: string
}

export interface MasterCSSDirectiveExtractionPolicy {
  include: string[]
  exclude: string[]
  safelist: string[]
  blocklist: (string | MasterCSSRegex)[]
  preserveNative: boolean
}

export interface MasterCSSDirectiveCompilation {
  manifestInput: MasterCSSDirectiveManifestInput
  extractionPolicy: MasterCSSDirectiveExtractionPolicy
  classNames: string[]
  nativeClassNames: string[]
  warnings: string[]
  nativeCSS: string
  css: string
  generatedCSS: string
  dependencies: string[]
  styleDefinitions?: import('@master/css-schema/css-directives').CSSDirectiveStyleDefinition[]
  references?: (import('@master/css-schema/css-directives').CSSDirectiveReference & {
    start: number
    end: number
    statement: string
  })[]
}

export interface MasterCSSCompilerInspection {
  hasMasterEntryDirective: boolean
  hasMasterCSSImport: boolean
  hasMasterEntry: boolean
  directives: MasterCSSLexerCSSDirective[]
}

export interface MasterCSSDirectiveCompileOptions {
  from?: string
  preserveNativeCSS?: boolean
  classes?: readonly string[]
}

export interface MasterCSSDependencyImport {
  start: number
  end: number
  statement: string
  source: string
}

export interface MasterCSSDependencyAnalysis {
  sourceWithoutReferences: string
  imports: MasterCSSDependencyImport[]
}

export interface MasterCSSStandaloneDirectiveStatement {
  start: number
  end: number
  atRuleName: 'master' | 'source' | 'safelist' | 'blocklist' | 'preserve'
  name: string
  statement: string
  args: string[]
  modifiers: string[]
}

export interface MasterCSSStandaloneDirectiveAnalysis {
  code: string
  statements: MasterCSSStandaloneDirectiveStatement[]
  extractionPolicy: MasterCSSDirectiveExtractionPolicy
}

export interface MasterCSSCompileManifestOptions {
  baseManifest?: import('@master/css-schema/manifest').MasterCSSManifest
}

export interface MasterCSSCompileManifestResult {
  manifest: import('@master/css-schema/manifest').MasterCSSManifest
}

export interface MasterCSSCompileDefaultPresetRequest {
  manifestInput: MasterCSSDirectiveManifestInput
  styleDefinitions?: readonly import('@master/css-schema/css-directives').CSSDirectiveStyleDefinition[]
}

export interface MasterCSSCompileDefaultPresetResult {
  manifest: import('@master/css-schema/manifest').MasterCSSManifest
  json: string
}

export interface MasterCSSLowerDirectivesRequest {
  manifestInput: MasterCSSDirectiveManifestInput
  styleDefinitions?: readonly import('@master/css-schema/css-directives').CSSDirectiveStyleDefinition[]
  warnings?: readonly string[]
}

export interface MasterCSSLowerDirectivesOptions {
  baseManifest?: import('@master/css-schema/manifest').MasterCSSManifest
  resolutionManifest?: import('@master/css-schema/manifest').MasterCSSManifest
}

export interface MasterCSSLowerDirectivesResult {
  input: MasterCSSDirectiveManifestInput
  manifest: import('@master/css-schema/manifest').MasterCSSManifest
  resolutionManifest: import('@master/css-schema/manifest').MasterCSSManifest
  warnings: string[]
  generatedCSS: string
  diagnosticCounts: Record<string, number>
}

export interface MasterCSSServerRender {
  classes: string[]
  snapshot: MasterCSSEngineSnapshot
  hydrationManifest: import('@master/css-schema/hydration-manifest').MasterCSSHydrationManifest
}

export interface MasterCSSImportGraphEdge {
  from: string
  specifier: string
  resolved: string
}

export interface MasterCSSImportGraphRequest {
  entry: string
  files: Record<string, string>
  edges: MasterCSSImportGraphEdge[]
}

export interface MasterCSSResolvedImportGraph {
  source: string
  dependencies: string[]
  references?: MasterCSSDirectiveCompilation['references']
}

export interface MasterCSSProjectEntryGraph {
  entry: string
  source: string
  dependencies: readonly string[]
}

export interface MasterCSSProjectSourceEntryPlan {
  entry: string
  include: string[]
  exclude: string[]
  files: string[]
}

export interface MasterCSSProjectSourcePlan {
  version: 1
  entries: MasterCSSProjectSourceEntryPlan[]
  files: string[]
}

export interface MasterCSSProjectManifest {
  entries: string[]
  manifest: import('@master/css-schema/manifest').MasterCSSManifest
  dependencies: string[]
  extractionPolicy: MasterCSSDirectiveExtractionPolicy
  classNames: string[]
  nativeClassNames: string[]
  nativeCSS: string
  css: string
  generatedCSS: string
  warnings: string[]
  sourcePlan: MasterCSSProjectSourcePlan
}

export type MasterCSSErrorCode =
  | 'INVALID_MANIFEST'
  | 'UNSUPPORTED_MANIFEST_VERSION'
  | 'INVALID_HYDRATION_MANIFEST'
  | 'NATIVE_UNAVAILABLE'
  | 'NATIVE_LOAD_FAILED'
  | 'WASM_LOAD_FAILED'
  | 'RUNTIME_STARTUP_TIMEOUT'
  | 'CSS_PARSE_ERROR'
  | 'CSS_PRINT_ERROR'
  | 'CSS_DIRECTIVE_ERROR'
  | 'invalid-compose-class'
  | 'compose-quoted-syntax'
  | 'compose-group-syntax'
  | 'CSS_IMPORT_ERROR'
  | 'SESSION_DISPOSED'
  | 'INVALID_INPUT'
  | 'INTERNAL'

export interface MasterCSSDiagnostic {
  code: MasterCSSErrorCode
  message: string
  source?: string
  range?: MasterCSSSourceRange
  notes?: string[]
}
