import { ESLint } from 'eslint'
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { expect, test } from 'vitest'
import plugin from '../src'
import { createPresetManifest } from './helpers/create-preset-manifest'
import { UtilityType } from '@master/css-schema/utility-type'
import isSameOrChildPath from '../src/utils/is-same-or-child-path'

test('uses explicit Master CSS manifest objects from ESLint settings', async () => {
  const cwd = mkdtempSync(join(tmpdir(), 'master-css-eslint-'))

  try {
    writeFileSync(join(cwd, 'index.jsx'), `<div className="fixture-button fixture-card zzz"></div>`)

    const eslint = new ESLint({
      cwd,
      overrideConfigFile: true,
      overrideConfig: [
        {
          files: ['**/*.jsx'],
          plugins: {
            '@master/css': plugin
          },
          languageOptions: {
            parserOptions: {
              ecmaVersion: 2022,
              sourceType: 'module',
              ecmaFeatures: {
                jsx: true
              }
            }
          },
          settings: {
            '@master/css': {
              manifest: createPresetManifest({
                utilities: [
                  {
                    name: 'fixture-card',
                    type: UtilityType.Semantic,
                    layer: 'components',
                    rules: [
                      { selector: '&', declarations: { display: 'block' } }
                    ]
                  },
                  {
                    name: 'fixture-button',
                    type: UtilityType.Semantic,
                    layer: 'components',
                    rules: [
                      { selector: '&', declarations: { display: 'inline-flex' } }
                    ]
                  }
                ]
              })
            }
          },
          rules: {
            '@master/css/no-invalid-classes': [
              'error',
              {
                disallowUnknownClass: true
              }
            ]
          }
        }
      ]
    })

    const [result] = await eslint.lintFiles('index.jsx')

    expect(result.messages.map((message) => message.message)).toStrictEqual([
      'Unknown Master CSS class "zzz". It is not generated by the active manifest.'
    ])
  } finally {
    rmSync(cwd, { force: true, recursive: true })
  }
})

test('uses project-level CSS manifest entries from the ESLint workspace', async () => {
  const cwd = mkdtempSync(join(tmpdir(), 'master-css-eslint-'))

  try {
    writeFileSync(join(cwd, 'index.css'), `
      @master entry;

      @components {
        fixture-button {
          display: inline-flex;
        }
      }
    `)
    writeFileSync(join(cwd, 'index.jsx'), `<div className="fixture-button zzz"></div>`)

    const eslint = new ESLint({
      cwd,
      overrideConfigFile: true,
      overrideConfig: [
        {
          files: ['**/*.jsx'],
          plugins: {
            '@master/css': plugin
          },
          languageOptions: {
            parserOptions: {
              ecmaVersion: 2022,
              sourceType: 'module',
              ecmaFeatures: {
                jsx: true
              }
            }
          },
          rules: {
            '@master/css/no-invalid-classes': [
              'error',
              {
                disallowUnknownClass: true
              }
            ]
          }
        }
      ]
    })

    const [result] = await eslint.lintFiles('index.jsx')

    expect(result.messages.map((message) => message.message)).toStrictEqual([
      'Unknown Master CSS class "zzz". It is not generated by the active manifest.'
    ])
  } finally {
    rmSync(cwd, { force: true, recursive: true })
  }
})

test('uses the project manifest for files that have not been written yet', async () => {
  const cwd = mkdtempSync(join(tmpdir(), 'master-css-eslint-'))

  try {
    writeFileSync(join(cwd, 'index.css'), `
      @master entry;

      @components {
        fixture-button {
          display: inline-flex;
        }
      }
    `)

    const eslint = createProjectESLint(cwd)
    const [result] = await eslint.lintText(
      `<div className="fixture-button zzz"></div>`,
      { filePath: join(cwd, 'new.jsx') }
    )

    expect(result.messages.map((message) => message.message)).toStrictEqual([
      'Unknown Master CSS class "zzz". It is not generated by the active manifest.'
    ])
  } finally {
    rmSync(cwd, { force: true, recursive: true })
  }
})

test('reloads project manifests between lint runs in the same process', async () => {
  const cwd = mkdtempSync(join(tmpdir(), 'master-css-eslint-'))
  const entry = join(cwd, 'index.css')

  try {
    writeProjectUtility(entry, 'fixture-one')
    writeFileSync(join(cwd, 'index.jsx'), `<div className="fixture-one fixture-two"></div>`)
    const eslint = createProjectESLint(cwd)

    const [firstResult] = await eslint.lintFiles('index.jsx')
    expect(firstResult.messages.map((message) => message.message)).toStrictEqual([
      'Unknown Master CSS class "fixture-two". It is not generated by the active manifest.'
    ])

    writeProjectUtility(entry, 'fixture-two')
    const [secondResult] = await eslint.lintFiles('index.jsx')
    expect(secondResult.messages.map((message) => message.message)).toStrictEqual([
      'Unknown Master CSS class "fixture-one". It is not generated by the active manifest.'
    ])
  } finally {
    rmSync(cwd, { force: true, recursive: true })
  }
})

test('does not match sibling workspace path prefixes', () => {
  const cwd = mkdtempSync(join(tmpdir(), 'master-css-eslint-'))

  try {
    const workspaceDir = join(cwd, 'packages', 'app')

    expect(isSameOrChildPath(workspaceDir, join(workspaceDir, 'index.jsx'))).toBe(true)
    expect(isSameOrChildPath(workspaceDir, join(cwd, 'packages', 'app-kit', 'index.jsx'))).toBe(false)
  } finally {
    rmSync(cwd, { force: true, recursive: true })
  }
})

function createProjectESLint(cwd: string) {
  return new ESLint({
    cwd,
    overrideConfigFile: true,
    overrideConfig: [
      {
        files: ['**/*.jsx'],
        plugins: {
          '@master/css': plugin
        },
        languageOptions: {
          parserOptions: {
            ecmaVersion: 2022,
            sourceType: 'module',
            ecmaFeatures: {
              jsx: true
            }
          }
        },
        rules: {
          '@master/css/no-invalid-classes': [
            'error',
            {
              disallowUnknownClass: true
            }
          ]
        }
      }
    ]
  })
}

function writeProjectUtility(filename: string, utility: string) {
  writeFileSync(filename, `
    @master entry;

    @components {
      ${utility} {
        display: inline-flex;
      }
    }
  `)
}
