import rule from '../src/rules/no-invalid-classes'
import { RuleTester } from '@typescript-eslint/rule-tester'
import { createTester, jsxTester } from './testers'
import { createPresetManifest } from './helpers/create-preset-manifest'
import { UtilityType } from '@master/css-schema/utility-type'

jsxTester.run('invalid', rule, {
  valid: [
    {
      code: `<div class="m:0.5rem p:0.5rem bg-black fg-white font-size:1.5rem">Simple, basic</div>`,
    },
    {
      code: `<div class={\`f:\${ fontSize }px\`}>TemplateLiteral</div>`,
    },
    {
      code: `<div class="{content:'';block}::after@light"></div>`,
    },
  ],
  invalid: [
    {
      code: `<div class="bg-black text-decoration:bad() rrr">Simple, basic</div>`,
      errors: [
        {
          messageId: 'invalidClass',
          data: {
            message: 'Class "text-decoration:bad()" emits invalid CSS: Invalid value for `-webkit-text-decoration` property.'
          }
        },
{
          messageId: 'invalidClass',
          data: {
            message: 'Class "text-decoration:bad()" emits invalid CSS: Invalid value for `text-decoration` property.'
          }
        },
        {
          messageId: 'disallowUnknownClass',
          data: {
            message: 'Unknown Master CSS class "rrr". It is not generated by the active manifest.'
          }
        }
      ],
      options: [
        {
          disallowUnknownClass: true
        }
      ] as any
    },
    {
      code: `<div class="bg-black text-decoration:bad() rrr">Simple, basic</div>`,
      errors: [
        { messageId: 'invalidClass' },
{ messageId: 'invalidClass' },
      ]
    },
    {
      code: `<div class="a c d hello:world text-decoration:bad() mt:0 mt:0@sm">Error class</div>`,
      errors: [
        { messageId: 'disallowUnknownClass' },
        { messageId: 'disallowUnknownClass' },
        { messageId: 'disallowUnknownClass' },
        { messageId: 'disallowUnknownClass' },
        { messageId: 'invalidClass' },
{ messageId: 'invalidClass' }
      ],
      options: [
        {
          disallowUnknownClass: true
        }
      ] as any
    },
    {
      code: `<div class="a c d hello:world text-decoration:bad() mt:0 mt:0@sm">Error class</div>`,
      errors: [
        { messageId: 'invalidClass' },
{ messageId: 'invalidClass' }
      ]
    },
  ]
})

createTester({
  settings: {
    '@master/css': {
      manifest: createPresetManifest({
        utilities: [
          {
            name: 'btn',
            type: UtilityType.Semantic,
            layer: 'components',
            rules: [
              { selector: '&', declarations: { display: 'block' } }
            ]
          }
        ]
      })
    }
  }
}).run('invalid', rule, {
  valid: [],
  invalid: [
    {
      code: `<div class="btn rrr bg-black text-decoration:bad()">Simple, basic</div>`,
      errors: [
        { messageId: 'disallowUnknownClass' },
        { messageId: 'invalidClass' },
{ messageId: 'invalidClass' }
      ],
      options: [
        {
          disallowUnknownClass: true
        }
      ] as any
    },
    {
      code: `<div class="btn a c d hello:world text-decoration:bad() mt:0 mt:0@sm">Error class</div>`,
      errors: [
        { messageId: 'disallowUnknownClass' },
        { messageId: 'disallowUnknownClass' },
        { messageId: 'disallowUnknownClass' },
        { messageId: 'disallowUnknownClass' },
        { messageId: 'invalidClass' },
{ messageId: 'invalidClass' }
      ],
      options: [
        {
          disallowUnknownClass: true
        }
      ] as any
    },
  ],
})
