import type { DemoScene } from '../../components/demo/reference/types'

const cell = (label: string, classes = '') => `<div class="p-md r-sm bg-blue-5 fg-blue-80 border-width:1px border-style:solid b-blue-20 ${classes}">${label}</div>`
const grid = (classes: string, cells: string) => `<div class="${classes} gap-sm">${cells}</div>`
const article = 'Good interfaces make space for the details. A short preview helps readers decide what to explore next, while a clear link keeps the complete story available. Design the summary as an invitation, and keep essential information outside the clipped region.'
const base: Record<string, DemoScene> = {
  'font-smooth': { html: `<div class="display:grid gap-xl"><section><p>font-antialiased</p><p class="margin:0 text-2xl font-antialiased">Quiet details, clearer ideas.<br>Aa 0123456789</p></section><section><p>font-subpixel-antialiased</p><p class="margin:0 text-2xl font-subpixel-antialiased">Quiet details, clearer ideas.<br>Aa 0123456789</p></section></div>`, caption: 'Same font, weight and size. Rendering differences depend on the operating system, display and browser; some environments render these identically.' },
  'screen-readers': { html: '<p>A visible icon and an accessible name:</p><button type="button"><span aria-hidden="true">＋</span><span class="sr-only">Add collection</span></button><p class="mt-md fg-text-muted">Focus the button. Its accessible name is “Add collection”; the decorative plus is hidden from assistive technology.</p>', caption: 'The sr-only text remains in the accessibility tree. The native button keeps its visible focus outline. This demonstration button does not create a collection.' },
  'grid-columns': { html: grid('grid-cols(3)', ['01 · Plan', '02 · Design', '03 · Build', '04 · Test', '05 · Refine', '06 · Ship'].map(text => cell(text)).join('')), caption: 'Three equal column tracks. Each cell can shrink because the minimum track size is zero.' },
  'grid-rows': { html: grid('grid-rows(3)', ['01 · Plan', '02 · Design', '03 · Build', '04 · Test', '05 · Refine', '06 · Ship'].map(text => cell(text)).join('')), caption: 'Three equal row tracks. Auto-placement fills the first column before starting the next.' },
  'grid-column': { html: grid('grid-cols(3)', cell('Feature · spans two columns', 'grid-col-span(2)') + cell('Notes') + cell('Archive') + cell('Reading') + cell('Saved')), caption: 'The featured region spans two tracks inside a three-column parent grid.' },
  'grid-row': { html: grid('grid-cols(3)', cell('Feature · spans two rows', 'grid-row-span(2)') + cell('Notes') + cell('Archive') + cell('Reading') + cell('Saved')), caption: 'The featured region spans two row tracks. The parent remains responsible for the grid.' },
  'clamp-lines': { html: `<div class="display:grid gap-lg"><section><h3 class="margin:0 text-sm fg-text-muted">Complete paragraph</h3><p class="mt-sm margin-bottom:0 max-width:32ch">${article}</p></section><section><h3 class="margin:0 text-sm fg-text-muted">clamp-lines(3)</h3><p class="mt-sm margin-bottom:0 max-width:32ch clamp-lines(3)">${article}</p></section></div>`, caption: 'Compare the full paragraph and its three-line preview at the same width. Essential content must remain available beyond a preview.' },
  'text-size': { html: '<article class="p-lg r-lg bg-surface-raised"><p class="margin:0 text-xs font-weight-medium fg-text-blue">FIELD NOTES / 024</p><h2 class="mt-sm mb-md text-3xl font-weight-semibold fg-text-strong">Make room for the details.</h2><p class="margin:0 text-md fg-text-body">A thoughtful type hierarchy brings the main idea forward and gives the supporting details a comfortable rhythm.</p><p class="mt-md margin-bottom:0 text-sm fg-text-muted">4 min read · Updated today</p></article>', caption: 'A complete composition uses four text treatments. Each treatment includes size, leading and tracking; weight and color are separate.' },
  'text-gradient': { html: '<h2 class="margin:0 text-4xl font-weight-bold text-gradient background-image:linear-gradient(100deg,var(--color-blue-60),var(--color-violet-60),var(--color-pink-60))">Ideas deserve<br>room to grow.</h2><p class="mt-lg margin-bottom:0 fg-text-body">The background supplies the colors; text-gradient clips them to the glyphs.</p>', caption: 'The recipe does not define the gradient. Keep supporting text in a readable solid foreground.' },
}
export const recipeSpecimens = Object.fromEntries(Object.entries(base).map(([id, scene]) => [id, { ...scene, sizing: 'content', bodyClass: 'bg-surface-base fg-text-body' } satisfies DemoScene]))
export function recipeScene(id: string): DemoScene {
  const scene = recipeSpecimens[id]
  if (!scene) throw new Error(`Missing recipe specimen: ${id}`)
  return scene
}
