name: Cache Pages
on:
  workflow_dispatch:
    inputs:
      locale:
        required: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v6
        - uses: ./.github/actions/setup-pnpm
          with:
            frozen-lockfile: "false"
            submodules-token: ${{ secrets.GITHUB_TOKEN }}
            turbo-cache: "false"
        - run: pnpm exec tsx internal/scripts/cache-pages
          env:
            FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
            FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
            LOCALE: ${{ github.event.inputs.locale }}
