name: Example Check
on:
    push:
        branches:
            - "**"
    pull_request_target:
        types:
            - opened
            - reopened
            - edited
            - synchronize

jobs:
    check:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node-version: [20]
                os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: 8
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
            - run: pnpm install
            - run: pnpm build
            - run: pnpm install
            - run: pnpm build:examples
