import { expect, test, type FrameLocator, type Locator, type Page } from '@playwright/test'

const routes = ['animation', 'animation-delay', 'animation-direction', 'animation-duration', 'animation-fill-mode', 'animation-iteration-count', 'animation-name', 'animation-play-state', 'animation-timing-function']
const example = (page: Page, route: string, section: string) => page.locator(`[data-demo-case="${route}#${section}"]`)
const target = (frame: FrameLocator, index?: number) => frame.locator(`#${index === undefined ? '' : `example-${index}-`}target`)
async function ready(demo: Locator) {
  await demo.scrollIntoViewIfNeeded()
  await expect(demo.locator('iframe')).toHaveAttribute('data-ready', 'true')
  await demo.locator('iframe').evaluate(async (element: HTMLIFrameElement) => { await element.contentDocument!.fonts.ready })
  return demo.frameLocator('iframe')
}
async function scene(page: Page, route: string, section: string) { return ready(example(page, route, section)) }
async function viewport(demo: Locator, width: number) {
  await demo.getByLabel('Viewport', { exact: true }).fill(String(width))
  await expect.poll(() => demo.locator('iframe').evaluate(e => e.clientWidth)).toBe(width)
}
async function seek(item: Locator, time: number) {
  return item.evaluate(async (e, time) => {
    const animation = e.getAnimations()[0]
    if (!animation) throw new Error('The authored CSS animation is missing')
    animation.pause(); animation.currentTime = time
    await new Promise<void>(resolve => requestAnimationFrame(() => resolve()))
    const style = getComputedStyle(e), matrix = new DOMMatrixReadOnly(style.transform)
    return { x: matrix.e, y: matrix.f, a: matrix.a, b: matrix.b, opacity: Number(style.opacity), progress: animation.effect!.getComputedTiming().progress }
  }, time)
}
async function time(item: Locator) { return item.evaluate(e => Number(e.getAnimations()[0]?.currentTime ?? 0)) }
async function print(page: Page, browserName: string, item: Locator) {
  if (browserName === 'chromium') {
    await page.emulateMedia({ media: 'print' }); await expect(item).toHaveCSS('animation-name', 'none')
    await page.emulateMedia({ media: 'screen' })
  }
}

test('animation shorthand preserves complete SVGs, negative segment phases and custom keyframes', async ({ page, browserName }) => {
  await page.goto('/en/reference/animation')
  const ping = await scene(page, 'animation', 'ping-indicator')
  await expect(ping.getByText('Open for orders')).toBeVisible()
  await expect(ping.locator('circle')).toHaveCount(2)
  await expect(target(ping)).toHaveCSS('animation-name', 'ping')
  const rotated = await scene(page, 'animation', 'rotate-indicator')
  expect((await seek(target(rotated), 250)).b).toBeCloseTo(-1, 2)
  const spinner = await scene(page, 'animation', 'loading-spinner')
  await expect(spinner.locator('path')).toHaveCount(8)
  expect(await spinner.locator('path').evaluateAll(paths => paths.map(e => getComputedStyle(e).animationDelay))).toEqual(['-0.875s', '-0.75s', '-0.625s', '-0.5s', '-0.375s', '-0.25s', '-0.125s', '0s'])
  const custom = await scene(page, 'animation', 'add-your-animations')
  await expect(target(custom)).toHaveCSS('animation-duration', '0.5s')
  expect((await seek(target(custom), 0)).y).toBeCloseTo(40, 1)
  expect((await seek(target(custom), 500)).y).toBeCloseTo(0, 1)
  const demo = example(page, 'animation', 'apply-conditionally'), frame = await ready(demo)
  await viewport(demo, 390); await expect(target(frame)).toHaveCSS('animation-name', 'none')
  await viewport(demo, 900); await expect(target(frame)).toHaveCSS('animation-name', 'rotate')
  await print(page, browserName, target(frame))
})

test('delay preserves waiting, negative phase, actual sibling offsets and duration tokens', async ({ page, browserName }) => {
  await page.goto('/en/reference/animation-delay')
  const base = await scene(page, 'animation-delay', 'delay-animation-start')
  expect((await seek(target(base, 0), 300)).x).toBeCloseTo(45.6, 1)
  expect((await seek(target(base, 1), 300)).x).toBeCloseTo(0, 1)
  expect((await seek(target(base, 1), 900)).x).toBeCloseTo(45.6, 1)
  const offset = await scene(page, 'animation-delay', 'offset-looping-animations')
  expect((await seek(target(offset, 1), 0)).b).toBeCloseTo(1, 2)
  expect((await seek(target(offset, 0), 500)).b).toBeCloseTo(1, 2)
  const list = await scene(page, 'animation-delay', 'stagger-a-list')
  await expect(list.locator('ul > li')).toHaveCount(3)
  expect(await list.locator('li > span[aria-hidden]').evaluateAll(elements => elements.map(e => [getComputedStyle(e).animationDelay, getComputedStyle(e).animationDuration]))).toEqual([['0s', '0.8s'], ['0.2s', '0.8s'], ['0.4s', '0.8s']])
  expect((await seek(target(list), 600)).opacity).toBeCloseTo(.25, 2)
  const token = await scene(page, 'animation-delay', 'use-duration-tokens')
  await expect(target(token)).toHaveCSS('animation-delay', '0.12s')
  const demo = example(page, 'animation-delay', 'apply-conditionally'), frame = await ready(demo)
  await viewport(demo, 390); await expect(target(frame)).toHaveCSS('animation-delay', '0.6s')
  await viewport(demo, 900); await expect(target(frame)).toHaveCSS('animation-delay', '0s')
  await print(page, browserName, target(frame))
})

test('direction uses native first and second iterations and supports explicit reduced-motion preview', async ({ page }) => {
  await page.goto('/en/reference/animation-direction')
  for (const [section, first, second] of [ ['play-forward', 42, 42], ['play-backward', 78, 78], ['play-alternately', 42, 78], ['play-alternately-and-reverse-first', 78, 42] ] as const) {
    const frame = await scene(page, 'animation-direction', section)
    expect((await seek(target(frame), 250)).x).toBeCloseTo(first, 1)
    expect((await seek(target(frame), 1250)).x).toBeCloseTo(second, 1)
  }
  const fade = await scene(page, 'animation-direction', 'fade-out')
  expect((await seek(target(fade), 250)).opacity).toBeCloseTo(.75, 2)
  expect((await seek(target(fade), 1000)).opacity).toBeCloseTo(0, 2)
  const demo = example(page, 'animation-direction', 'apply-conditionally'), frame = await ready(demo)
  await viewport(demo, 390); await expect(target(frame)).toHaveCSS('animation-direction', 'reverse')
  await viewport(demo, 900); await expect(target(frame)).toHaveCSS('animation-direction', 'normal')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect.poll(() => target(frame).evaluate(e => e.getAnimations()[0]?.playState)).toBe('paused')
  const play = demo.getByRole('button', { name: 'Play', exact: true })
  await play.focus(); await page.keyboard.press('Enter')
  await expect.poll(() => time(target(frame))).toBeGreaterThan(200)
  await demo.getByRole('button', { name: 'Pause', exact: true }).click()
  await expect.poll(() => target(frame).evaluate(e => e.getAnimations()[0]?.playState)).toBe('paused')
  await demo.getByRole('button', { name: 'Replay', exact: true }).click()
  expect(await time(target(frame))).toBeLessThan(250)
})

test('duration compares actual cycle lengths, looping rates and zero-duration fill', async ({ page, browserName }) => {
  await page.goto('/en/reference/animation-duration')
  const base = await scene(page, 'animation-duration', 'set-animation-speed')
  expect((await seek(target(base, 0), 250)).x).toBeCloseTo(60, 1)
  expect((await seek(target(base, 1), 250)).x).toBeCloseTo(42, 1)
  const loop = await scene(page, 'animation-duration', 'slow-down-looping-motion')
  expect((await seek(target(loop, 0), 250)).b).toBeCloseTo(1, 2)
  expect((await seek(target(loop, 1), 250)).b).toBeCloseTo(.5, 2)
  const zero = await scene(page, 'animation-duration', 'remove-animation-in-static-output')
  await expect(target(zero, 1)).toHaveCSS('animation-duration', '0s')
  expect((await target(zero, 1).evaluate(e => new DOMMatrixReadOnly(getComputedStyle(e).transform).e))).toBeCloseTo(96, 1)
  const demo = example(page, 'animation-duration', 'apply-conditionally'), frame = await ready(demo)
  await viewport(demo, 390); await expect(target(frame)).toHaveCSS('animation-duration', '0.5s')
  await viewport(demo, 900); await expect(target(frame)).toHaveCSS('animation-duration', '1s')
  await print(page, browserName, target(frame))
})

test('fill distinguishes all phases and naturally finished no-fill timelines replay', async ({ page, browserName }) => {
  await page.goto('/en/reference/animation-fill-mode')
  const demo = example(page, 'animation-fill-mode', 'keep-the-final-keyframe'), base = await ready(demo)
  await demo.getByRole('button', { name: 'Play', exact: true }).click()
  await expect.poll(() => target(base, 0).evaluate(e => e.getAnimations().length)).toBe(0)
  expect(await target(base, 0).evaluate(e => new DOMMatrixReadOnly(getComputedStyle(e).transform).e)).toBe(0)
  expect(await target(base, 1).evaluate(e => new DOMMatrixReadOnly(getComputedStyle(e).transform).e)).toBe(96)
  await expect(base.locator('[data-animation-readout="example-0-target"]')).toContainText('finished')
  await expect(demo.getByRole('button', { name: 'Play', exact: true })).toBeVisible()
  await demo.getByRole('button', { name: 'Replay', exact: true }).click()
  await expect.poll(() => target(base, 0).evaluate(e => e.getAnimations().length)).toBe(1)
  expect(await time(target(base, 0))).toBeLessThan(300)
  const both = await scene(page, 'animation-fill-mode', 'apply-both-before-and-after-states')
  for (const i of [0, 1]) expect((await seek(target(both, i), 300)).x).toBeCloseTo(24, 1)
  expect((await seek(target(both, 0), 1700)).x).toBeCloseTo(0, 1)
  expect((await seek(target(both, 1), 1700)).x).toBeCloseTo(96, 1)
  const none = await scene(page, 'animation-fill-mode', 'reset-fill-behavior')
  expect((await seek(target(none), 300)).x).toBeCloseTo(0, 1)
  expect((await seek(target(none), 900)).x).toBeCloseTo(45.6, 1)
  const conditional = example(page, 'animation-fill-mode', 'apply-conditionally'), frame = await ready(conditional)
  await viewport(conditional, 390); await expect(target(frame)).toHaveCSS('animation-fill-mode', 'both')
  await viewport(conditional, 900); await expect(target(frame)).toHaveCSS('animation-fill-mode', 'none')
  await print(page, browserName, target(frame))
})

test('iteration count preserves fractional endpoints and alternate final fill', async ({ page, browserName }) => {
  await page.goto('/en/reference/animation-iteration-count')
  const loop = await scene(page, 'animation-iteration-count', 'loop-animation')
  await expect(target(loop)).toHaveCSS('animation-iteration-count', 'infinite')
  const count = await scene(page, 'animation-iteration-count', 'specify-n-iterations')
  expect((await seek(target(count, 0), 3000)).x).toBeCloseTo(96, 1)
  expect((await seek(target(count, 1), 2500)).x).toBeCloseTo(60, 1)
  const final = await scene(page, 'animation-iteration-count', 'pair-with-fill-mode')
  expect((await seek(target(final), 2000)).x).toBeCloseTo(24, 1)
  const demo = example(page, 'animation-iteration-count', 'apply-conditionally'), frame = await ready(demo)
  await viewport(demo, 390); await expect(target(frame)).toHaveCSS('animation-iteration-count', '1')
  await viewport(demo, 900); await expect(target(frame)).toHaveCSS('animation-iteration-count', '3')
  await print(page, browserName, target(frame))
})

test('animation names select actual keyframes, cancel on none and create a fresh responsive timeline', async ({ page, browserName }) => {
  await page.goto('/en/reference/animation-name')
  const base = await scene(page, 'animation-name', 'choose-the-keyframes-to-run')
  expect((await seek(target(base, 0), 250)).opacity).toBeCloseTo(.25, 2)
  expect((await seek(target(base, 1), 250)).b).toBeCloseTo(1, 2)
  const off = await scene(page, 'animation-name', 'disable-an-animation')
  await expect(target(off, 1)).toHaveCSS('animation-name', 'none')
  expect(await target(off, 1).evaluate(e => e.getAnimations().length)).toBe(0)
  const timing = await scene(page, 'animation-name', 'combine-with-timing-longhands')
  expect((await seek(target(timing), 0)).x).toBe(24)
  expect((await seek(target(timing), 800)).x).toBeCloseTo(60, 1)
  const demo = example(page, 'animation-name', 'apply-conditionally'), frame = await ready(demo)
  await viewport(demo, 390); await expect(target(frame)).toHaveCSS('animation-name', 'none')
  await viewport(demo, 900); await expect(target(frame)).toHaveCSS('animation-name', 'rotate')
  await demo.getByRole('button', { name: 'Play', exact: true }).click()
  await expect.poll(() => time(target(frame))).toBeGreaterThan(150)
  await viewport(demo, 390); expect(await target(frame).evaluate(e => e.getAnimations().length)).toBe(0)
  await viewport(demo, 900); expect(await time(target(frame))).toBeLessThan(300)
  await print(page, browserName, target(frame))
})

test('native play-state controls retain keyboard operation, resume time and actual hover/focus selectors', async ({ page, browserName }) => {
  await page.goto('/en/reference/animation-play-state')
  const base = await scene(page, 'animation-play-state', 'run-an-animation'), input = base.getByRole('checkbox', { name: 'Run indicator' })
  await expect(target(base)).toHaveCSS('animation-play-state', 'paused')
  await input.focus(); await page.keyboard.press('Space')
  await expect(target(base)).toHaveCSS('animation-play-state', 'running')
  await expect.poll(() => time(target(base))).toBeGreaterThan(150)
  await page.keyboard.press('Space'); await expect(target(base)).toHaveCSS('animation-play-state', 'paused')
  const held = await time(target(base))
  await input.check(); await expect.poll(() => time(target(base))).toBeGreaterThan(held + 80)
  const hover = await scene(page, 'animation-play-state', 'pause-animation')
  await hover.getByRole('checkbox').check(); await page.mouse.move(0, 0)
  await expect(target(hover)).toHaveCSS('animation-play-state', 'running')
  if (await page.evaluate(() => matchMedia('(hover:hover)').matches)) {
    await hover.getByText('Hover this panel to pause').hover()
    await expect(target(hover)).toHaveCSS('animation-play-state', 'paused')
    await page.mouse.move(0, 0); await expect(target(hover)).toHaveCSS('animation-play-state', 'running')
  }
  const editor = await scene(page, 'animation-play-state', 'pause-nonessential-motion')
  await editor.getByRole('checkbox').check(); await expect(target(editor)).toHaveCSS('animation-play-state', 'running')
  const field = editor.getByRole('textbox', { name: 'Project name' })
  await field.focus(); await field.fill('New canvas'); await expect(field).toHaveValue('New canvas')
  await expect(target(editor)).toHaveCSS('animation-play-state', 'paused')
  await editor.getByRole('checkbox').focus(); await expect(target(editor)).toHaveCSS('animation-play-state', 'running')
  const demo = example(page, 'animation-play-state', 'apply-conditionally'), frame = await ready(demo)
  await frame.getByRole('checkbox').check()
  await viewport(demo, 390); await expect(target(frame)).toHaveCSS('animation-play-state', 'paused')
  await viewport(demo, 900); await expect(target(frame)).toHaveCSS('animation-play-state', 'running')
  await page.emulateMedia({ reducedMotion: 'reduce' }); await expect(target(frame)).toHaveCSS('animation-play-state', 'paused')
  await print(page, browserName, target(frame))
  await expect(demo.getByRole('button', { name: 'Replay', exact: true })).toHaveCount(0)
})

test('easing retains actual interpolation and keyframe-level stepped precedence', async ({ page, browserName }) => {
  await page.goto('/en/reference/animation-timing-function')
  const base = await scene(page, 'animation-timing-function', 'set-keyframe-easing')
  expect((await seek(target(base, 0), 500)).x).toBeCloseTo(60, 1)
  expect((await seek(target(base, 1), 500)).x).toBeLessThan(50)
  expect((await seek(target(base, 2), 500)).x).toBeGreaterThan(70)
  const rotation = await scene(page, 'animation-timing-function', 'use-linear-timing-for-rotation')
  expect((await seek(target(rotation, 0), 250)).b).toBeCloseTo(Math.SQRT1_2, 2)
  expect((await seek(target(rotation, 1), 250)).b).toBeLessThan(.3)
  const stepped = await scene(page, 'animation-timing-function', 'match-easing-to-intent')
  await expect(target(stepped)).toHaveCSS('animation-timing-function', 'linear')
  expect((await seek(target(stepped), 249)).x).toBeCloseTo(24, 1)
  expect((await seek(target(stepped), 251)).x).toBeCloseTo(42, 1)
  const demo = example(page, 'animation-timing-function', 'apply-conditionally'), frame = await ready(demo)
  await viewport(demo, 390); await expect(target(frame)).toHaveCSS('animation-timing-function', 'ease-out')
  await viewport(demo, 900); await expect(target(frame)).toHaveCSS('animation-timing-function', 'linear')
  await print(page, browserName, target(frame))
})

for (const route of routes) {
  test(`animations composition: ${route}`, async ({ page }, testInfo) => {
    const failures: string[] = []
    page.on('pageerror', error => failures.push(error.message))
    page.on('console', message => { if (message.type() === 'error' && /hydration|hydrate|mismatch/i.test(message.text())) failures.push(message.text()) })
    await page.goto(`/en/reference/${route}`)
    await page.addStyleTag({ content: 'nextjs-portal { visibility: hidden }' })
    for (const [index, demo] of (await page.locator('[data-demo-case]').all()).entries()) {
      const frame = await ready(demo)
      const dark = await page.locator('html').evaluate(e => e.classList.contains('dark'))
      await expect(frame.locator('html')).toHaveAttribute('class', dark ? 'dark' : 'light')
      expect(await frame.locator('body').evaluate(e => e.scrollWidth - e.clientWidth)).toBeLessThanOrEqual(1)
      for (const item of await frame.locator('[data-target]').all()) await expect(item).toHaveAttribute('data-appearance', 'plain')
      await demo.evaluate(element => window.scrollTo(0, element.getBoundingClientRect().top + window.scrollY - 96))
      await page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))))
      await demo.screenshot({ path: testInfo.outputPath(`demo-${index}.png`), scale: 'css' })
    }
    expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
    expect(failures).toEqual([])
    await page.evaluate(() => window.scrollTo(0, 0))
    await page.screenshot({ path: testInfo.outputPath('page.png'), fullPage: true, scale: 'css' })
  })
}
