import { expect, test, type FrameLocator, type Locator, type Page } from '@playwright/test'

const example = (page: Page, route: string, section: string) => page.locator(`[data-demo-case="${route}#${section}"]`)
async function ready(demo: Locator) {
  await demo.scrollIntoViewIfNeeded()
  await expect(demo.locator('iframe')).toHaveAttribute('data-ready', 'true')
  await demo.locator('iframe').evaluate(async (element: HTMLIFrameElement) => { await element.contentDocument!.fonts.ready })
  return demo.frameLocator('iframe')
}
const box = (element: Locator) => element.evaluate(node => {
  const bounds = node.getBoundingClientRect()
  return { width: bounds.width, height: bounds.height, left: bounds.left, top: bounds.top }
})
async function sizeReading(frame: FrameLocator, id: string) {
  const bounds = await box(frame.locator(`#${id}`))
  await expect(frame.locator(`[data-size-readout="${id}"]`)).toHaveText(`${Math.round(bounds.width * 10) / 10} × ${Math.round(bounds.height * 10) / 10} px`)
}
async function sourceFocus(page: Page, frame: FrameLocator, prefix = '') {
  const buttons = frame.locator(`#${prefix}layout`).getByRole('button')
  await buttons.filter({ hasText: 'Source 1' }).focus()
  await page.keyboard.press('Tab')
  await expect(buttons.filter({ hasText: 'Source 2' })).toBeFocused()
  await expect(buttons.filter({ hasText: 'Source 2' })).toHaveCSS('outline-width', '2px')
  await expect(buttons.filter({ hasText: 'Source 2' })).toHaveCSS('outline-offset', '3px')
  await page.keyboard.press('Tab')
  await expect(buttons.filter({ hasText: 'Source 3' })).toBeFocused()
}

test('flex shorthand keeps fixed sizes and only flexes inside a flex parent', async ({ page }) => {
  await page.goto('/en/reference/flex')
  const fill = await ready(example(page, 'flex', 'let-an-item-fill-remaining-space'))
  const container = await box(fill.locator('#layout'))
  expect((await box(fill.locator('#peer'))).width).toBe(96)
  expect((await box(fill.locator('#target'))).width).toBeCloseTo(container.width - 112, 1)
  await sizeReading(fill, 'target')
  const fixed = await ready(example(page, 'flex', 'prevent-an-item-from-flexing'))
  expect(await box(fixed.locator('#target'))).toMatchObject({ width: 48, height: 48 })
  await expect(fixed.locator('#target')).toHaveCSS('flex', '0 0 auto')
  const explicit = await ready(example(page, 'flex', 'set-grow-shrink-and-basis-together'))
  expect((await box(explicit.locator('#target'))).width).toBe(72)
  const parent = await ready(example(page, 'flex', 'remember-the-parent-display'))
  const blockTarget = await box(parent.locator('#example-0-target')), blockPeer = await box(parent.locator('#example-0-peer'))
  const flexTarget = await box(parent.locator('#example-1-target')), flexPeer = await box(parent.locator('#example-1-peer'))
  expect(blockTarget.width).toBe(96)
  expect(blockPeer.top).toBeGreaterThan(blockTarget.top)
  expect(flexTarget.top).toBe(flexPeer.top)
  expect(flexTarget.width).toBeGreaterThan(96)
  const demo = example(page, 'flex', 'apply-conditionally'), frame = await ready(demo)
  await demo.getByLabel('Viewport', { exact: true }).fill('300')
  await expect.poll(async () => (await box(frame.locator('#target'))).width).toBe(96)
  await demo.getByLabel('Viewport', { exact: true }).fill('900')
  await expect(frame.locator('#target')).toHaveCSS('flex-grow', '1')
  expect((await box(frame.locator('#target'))).width).toBeGreaterThan(600)
  await sizeReading(frame, 'target')
})

test('basis distinguishes percentages, intrinsic sizes, container tokens and column height', async ({ page }) => {
  await page.goto('/en/reference/flex-basis')
  const start = await ready(example(page, 'flex-basis', 'set-the-starting-size-of-a-flex-item'))
  expect((await box(start.locator('#target'))).width).toBe(96)
  const intrinsic = await ready(example(page, 'flex-basis', 'use-content-or-parent-sized-basis-values'))
  const full = await box(intrinsic.locator('#example-0-target'))
  expect(full.width).toBe((await box(intrinsic.locator('#example-0-layout'))).width)
  const fit = await box(intrinsic.locator('#example-1-target')), max = await box(intrinsic.locator('#example-2-target'))
  expect(full.width).toBeGreaterThan(fit.width)
  expect(fit.width).toBeCloseTo(max.width, 1)
  await expect(intrinsic.locator('#example-1-target')).toHaveCSS('flex-basis', 'fit-content')
  // Intrinsic width can change without resizing the iframe or its body.
  await intrinsic.locator('#example-1-target').evaluate(element => { element.textContent = 'Design system assets' })
  expect((await box(intrinsic.locator('#example-1-target'))).width).toBeGreaterThan(fit.width)
  await sizeReading(intrinsic, 'example-1-target')
  const token = await ready(example(page, 'flex-basis', 'use-container-basis-values'))
  await expect(token.locator('#target')).toHaveCSS('flex-basis', '448px')
  expect((await box(token.locator('#target'))).width).toBeCloseTo(Math.min(448, (await box(token.locator('#layout'))).width - 96), 1)
  const column = await ready(example(page, 'flex-basis', 'prefer-shorthand-for-complete-flex-behavior'))
  expect((await box(column.locator('#target'))).height).toBe(72)
  expect((await box(column.locator('#peer'))).height).toBe(152)
  await expect(column.locator('[data-layout-axis]')).toHaveText('Main axis · block')
  const demo = example(page, 'flex-basis', 'apply-conditionally'), frame = await ready(demo)
  await demo.getByLabel('Viewport', { exact: true }).fill('300')
  expect((await box(frame.locator('#target'))).width).toBe((await box(frame.locator('#layout'))).width)
  expect((await box(frame.locator('#peer'))).top).toBeGreaterThan((await box(frame.locator('#target'))).top)
  await demo.getByLabel('Viewport', { exact: true }).fill('900')
  await expect.poll(async () => (await box(frame.locator('#target'))).width).toBe(96)
  expect((await box(frame.locator('#peer'))).top).toBe((await box(frame.locator('#target'))).top)
})

test('growth distributes only positive free space and leaves opted-out items at their basis', async ({ page }) => {
  await page.goto('/en/reference/flex-grow')
  const grow = await ready(example(page, 'flex-grow', 'let-an-item-grow'))
  const extra = (await box(grow.locator('#layout'))).width - 16 - 128
  expect((await box(grow.locator('#target'))).width).toBeCloseTo(64 + extra / 3, 1)
  expect((await box(grow.locator('#peer'))).width).toBeCloseTo(64 + extra * 2 / 3, 1)
  await sizeReading(grow, 'target')
  await sizeReading(grow, 'peer')
  const zero = await ready(example(page, 'flex-grow', 'keep-an-item-at-its-basis'))
  expect((await box(zero.locator('#target'))).width).toBe(96)
  const demo = example(page, 'flex-grow', 'apply-conditionally'), frame = await ready(demo)
  await demo.getByLabel('Viewport', { exact: true }).fill('300')
  await expect.poll(async () => (await box(frame.locator('#target'))).width).toBe(80)
  await demo.getByLabel('Viewport', { exact: true }).fill('900')
  expect((await box(frame.locator('#target'))).width).toBe((await box(frame.locator('#layout'))).width - 96)
  await sizeReading(frame, 'target')
})

test('shrink factors use the real basis and fixed media keeps its width', async ({ page }) => {
  await page.goto('/en/reference/flex-shrink')
  const shrink = await ready(example(page, 'flex-shrink', 'allow-an-item-to-shrink'))
  expect((await box(shrink.locator('#target'))).width).toBe(176)
  expect((await box(shrink.locator('#peer'))).width).toBe(88)
  await sizeReading(shrink, 'target')
  await sizeReading(shrink, 'peer')
  const media = await ready(example(page, 'flex-shrink', 'prevent-fixed-media-from-shrinking'))
  expect(await box(media.locator('#target'))).toMatchObject({ width: 48, height: 48 })
  expect((await box(media.locator('#peer'))).width).toBe(216)
  expect(await media.locator('#peer').evaluate(element => element.scrollWidth - element.clientWidth)).toBeLessThanOrEqual(1)
  const demo = example(page, 'flex-shrink', 'apply-conditionally'), frame = await ready(demo)
  await demo.getByLabel('Viewport', { exact: true }).fill('340')
  await expect.poll(async () => (await box(frame.locator('#target'))).width).toBe(176)
  await demo.getByLabel('Viewport', { exact: true }).fill('900')
  await expect.poll(async () => (await box(frame.locator('#target'))).width).toBe(192)
  expect((await box(frame.locator('#peer'))).width).toBe(72)
  await sizeReading(frame, 'target')
})

test('wrapping forms real lines, preserves widths and reverses only line stacking', async ({ page }) => {
  await page.goto('/en/reference/flex-wrap')
  const wrapped = await ready(example(page, 'flex-wrap', 'allow-items-to-wrap'))
  const first = await box(wrapped.locator('#item-1')), third = await box(wrapped.locator('#item-3')), fourth = await box(wrapped.locator('#item-4'))
  expect(first.width).toBe(96)
  expect(third.top).toBe(first.top)
  expect(fourth.top - first.top).toBe(76)
  const single = await ready(example(page, 'flex-wrap', 'keep-items-on-one-line'))
  await expect(single.locator('#layout')).toHaveAccessibleName('Single-line collection')
  expect((await box(single.locator('#item-5'))).top).toBe((await box(single.locator('#item-1'))).top)
  expect(await single.locator('#layout').evaluate(element => element.scrollWidth > element.clientWidth)).toBe(true)
  await single.locator('#layout').focus()
  await expect(single.locator('#layout')).toBeFocused()
  await single.locator('#layout').evaluate(element => element.scrollBy({ left: 120, behavior: 'instant' }))
  expect(await single.locator('#layout').evaluate(element => element.scrollLeft)).toBe(120)
  const reverse = await ready(example(page, 'flex-wrap', 'reverse-wrap-direction'))
  expect((await box(reverse.locator('#item-1'))).top).toBeGreaterThan((await box(reverse.locator('#item-4'))).top)
  expect((await box(reverse.locator('#item-1'))).left).toBeLessThan((await box(reverse.locator('#item-2'))).left)
  const demo = example(page, 'flex-wrap', 'apply-conditionally'), frame = await ready(demo)
  await demo.getByLabel('Viewport', { exact: true }).fill('300')
  await expect(frame.locator('#layout')).toHaveCSS('flex-wrap', 'nowrap')
  await demo.getByLabel('Viewport', { exact: true }).fill('900')
  await expect(frame.locator('#layout')).toHaveCSS('flex-wrap', 'wrap')
  expect((await box(frame.locator('#item-4'))).top).toBeGreaterThan((await box(frame.locator('#item-1'))).top)
  await sizeReading(frame, 'layout')
})

test('direction changes axes and reverses positions without changing focus order', async ({ page }) => {
  await page.goto('/en/reference/flex-direction')
  const row = await ready(example(page, 'flex-direction', 'lay-out-items-in-a-row'))
  expect((await box(row.locator('#item-1'))).top).toBe((await box(row.locator('#item-3'))).top)
  expect((await box(row.locator('#item-1'))).left).toBeLessThan((await box(row.locator('#item-3'))).left)
  const column = await ready(example(page, 'flex-direction', 'stack-items-in-a-column'))
  expect((await box(column.locator('#item-2'))).top - (await box(column.locator('#item-1'))).top).toBe(80)
  const reverse = await ready(example(page, 'flex-direction', 'reverse-visual-order'))
  expect((await box(reverse.locator('#example-0-item-1'))).left).toBeGreaterThan((await box(reverse.locator('#example-0-item-3'))).left)
  expect((await box(reverse.locator('#example-1-item-1'))).top).toBeGreaterThan((await box(reverse.locator('#example-1-item-3'))).top)
  await sourceFocus(page, reverse, 'example-0-')
  await sourceFocus(page, reverse, 'example-1-')
  const demo = example(page, 'flex-direction', 'apply-conditionally'), frame = await ready(demo)
  await demo.getByLabel('Viewport', { exact: true }).fill('300')
  await expect(frame.locator('[data-layout-axis]')).toHaveText('Main axis · block')
  expect((await box(frame.locator('#layout'))).height).toBe(216)
  await demo.getByLabel('Viewport', { exact: true }).fill('900')
  await expect(frame.locator('[data-layout-axis]')).toHaveText('Main axis · inline')
  expect((await box(frame.locator('#layout'))).height).toBe(64)
  await sizeReading(frame, 'layout')
})

test('order sorts flex and grid items while keyboard traversal keeps the source sequence', async ({ page }) => {
  await page.goto('/en/reference/order')
  const sorted = await ready(example(page, 'order', 'change-visual-order'))
  for (const prefix of ['example-0-', 'example-1-']) {
    expect((await box(sorted.locator(`#${prefix}item-3`))).left).toBeLessThan((await box(sorted.locator(`#${prefix}target`))).left)
    expect((await box(sorted.locator(`#${prefix}target`))).left).toBeLessThan((await box(sorted.locator(`#${prefix}peer`))).left)
  }
  const meaningful = await ready(example(page, 'order', 'keep-source-order-meaningful'))
  await sourceFocus(page, meaningful)
  const demo = example(page, 'order', 'apply-conditionally'), frame = await ready(demo)
  await demo.getByLabel('Viewport', { exact: true }).fill('300')
  await expect(frame.locator('#target')).toHaveCSS('order', '2')
  expect((await box(frame.locator('#target'))).left).toBeGreaterThan((await box(frame.locator('#item-3'))).left)
  await demo.getByLabel('Viewport', { exact: true }).fill('900')
  await expect(frame.locator('#target')).toHaveCSS('order', '0')
  expect((await box(frame.locator('#target'))).left).toBeLessThan((await box(frame.locator('#peer'))).left)
})

for (const route of ['flex', 'flex-basis', 'flex-grow', 'flex-shrink', 'flex-wrap', 'flex-direction', 'order']) {
  test(`flexbox composition: ${route}`, async ({ page }, testInfo) => {
    const failures: string[] = []
    page.on('pageerror', error => failures.push(error.message))
    page.on('console', message => { if (message.type() === 'error' && /hydration|hydrate|mismatch/i.test(message.text())) failures.push(message.text()) })
    await page.goto(`/en/reference/${route}`)
    await page.addStyleTag({ content: 'nextjs-portal { visibility: hidden }' })
    for (const [index, demo] of (await page.locator('.site-demo').all()).entries()) {
      if (await demo.locator('iframe').count()) await ready(demo)
      await demo.evaluate(element => window.scrollTo(0, element.getBoundingClientRect().top + window.scrollY - 96))
      await page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))))
      await demo.screenshot({ path: testInfo.outputPath(`demo-${index}.png`), scale: 'css' })
    }
    expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
    expect(failures).toEqual([])
    await page.evaluate(() => window.scrollTo(0, 0))
    await page.screenshot({ path: testInfo.outputPath('page.png'), fullPage: true, scale: 'css' })
  })
}
